import string
import re
import unicodedata
import sys

patterns = {
    '[àáảãạăắằẵặẳâầấậẫẩ]': 'a',
    '[đ]': 'd',
    '[èéẻẽẹêềếểễệ]': 'e',
    '[ìíỉĩị]': 'i',
    '[òóỏõọôồốổỗộơờớởỡợ]': 'o',
    '[ùúủũụưừứửữự]': 'u',
    '[ỳýỷỹỵ]': 'y'
}


def remove_accent(text):
    """
    Convert from 'Tiếng Việt' into 'Tieng Viet'
    :param text: input string to be converted
    :return Return: string converted
    """
    output = text
    for regex, replace in patterns.items():
        output = re.sub(regex, replace, output)
        # deal with upper case
        output = re.sub(regex.upper(), replace.upper(), output)
    return output

districtListHCM = [["q10", "Quận 10"],
                   ["q 10", "Quận 10"],
                   ["q\.10", "Quận 10"],
                   ["q\. 10", "Quận 10"],
                   ["quan 10", "Quận 10"],
                   ["quan\.10", "Quận 10"],
                   ["quan\. 10", "Quận 10"],
                   ["q11", "Quận 11"],
                   ["q 11", "Quận 11"],
                   ["q\.11", "Quận 11"],
                   ["q\. 11", "Quận 11"],
                   ["quan 11", "Quận 11"],
                   ["quan\.11", "Quận 11"],
                   ["quan\. 11", "Quận 11"],
                   ["q12", "Quận 12"],
                   ["q 12", "Quận 12"],
                   ["q\.12", "Quận 12"],
                   ["q\. 12", "Quận 12"],
                   ["quan 12", "Quận 12"],
                   ["quan\.12", "Quận 12"],
                   ["quan\. 12", "Quận 12"],
                   ["q1", "Quận 1"],
                   ["q 1", "Quận 1"],
                   ["q\.1", "Quận 1"],
                   ["q\. 1", "Quận 1"],
                   ["quan 1", "Quận 1"],
                   ["quan\.1", "Quận 1"],
                   ["quan\. 1", "Quận 1"],
                   ["q2", "Quận 2"],
                   ["q 2", "Quận 2"],
                   ["q\.2", "Quận 2"],
                   ["q\. 2", "Quận 2"],
                   ["quan 2", "Quận 2"],
                   ["quan\.2", "Quận 2"],
                   ["quan\. 2", "Quận 2"],
                   ["q3", "Quận 3"],
                   ["q 3", "Quận 3"],
                   ["q\.3", "Quận 3"],
                   ["q\. 3", "Quận 3"],
                   ["quan 3", "Quận 3"],
                   ["quan\.3", "Quận 3"],
                   ["quan\. 3", "Quận 3"],
                   ["q4", "Quận 4"],
                   ["q 4", "Quận 4"],
                   ["q\.4", "Quận 4"],
                   ["q\. 4", "Quận 4"],
                   ["quan 4", "Quận 4"],
                   ["quan\.4", "Quận 4"],
                   ["quan\. 4", "Quận 4"],
                   ["q5", "Quận 5"],
                   ["q 5", "Quận 5"],
                   ["q\.5", "Quận 5"],
                   ["q\. 5", "Quận 5"],
                   ["quan 5", "Quận 5"],
                   ["quan\.5", "Quận 5"],
                   ["quan\. 5", "Quận 5"],
                   ["q6", "Quận 6"],
                   ["q 6", "Quận 6"],
                   ["q\.6", "Quận 6"],
                   ["q\. 6", "Quận 6"],
                   ["quan 6", "Quận 6"],
                   ["quan\.6", "Quận 6"],
                   ["quan\. 6", "Quận 6"],
                   ["q7", "Quận 7"],
                   ["q 7", "Quận 7"],
                   ["q\.7", "Quận 7"],
                   ["q\. 7", "Quận 7"],
                   ["quan 7", "Quận 7"],
                   ["quan\.7", "Quận 7"],
                   ["quan\. 7", "Quận 7"],
                   ["q8", "Quận 8"],
                   ["q 8", "Quận 8"],
                   ["q\.8", "Quận 8"],
                   ["q\. 8", "Quận 8"],
                   ["quan 8", "Quận 8"],
                   ["quan\.8", "Quận 8"],
                   ["quan\. 8", "Quận 8"],
                   ["q9", "Quận 9"],
                   ["q 9", "Quận 9"],
                   ["q\.9", "Quận 9"],
                   ["q\. 9", "Quận 9"],
                   ["quan 9", "Quận 9"],
                   ["quan\.9", "Quận 9"],
                   ["quan\. 9", "Quận 9"],
                   ["GV", "Quận Gò Vấp"],
                   ["Go Vap", "Quận Gò Vấp"],
                   ["qGo Vap", "Quận Gò Vấp"],
                   ["qGV", "Quận Gò Vấp"],
                   ["q Go Vap", "Quận Gò Vấp"],
                   ["q GV", "Quận Gò Vấp"],
                   ["q\.Go Vap", "Quận Gò Vấp"],
                   ["q\.Gv", "Quận Gò Vấp"],
                   ["q\. Go Vap", "Quận Gò Vấp"],
                   ["q\. GV", "Quận Gò Vấp"],
                   ["quan Go Vap", "Quận Gò Vấp"],
                   ["quan Gv", "Quận Gò Vấp"],
                   ["quan\.Go Vap", "Quận Gò Vấp"],
                   ["quan\.Gv", "Quận Gò Vấp"],
                   ["quan\. Go Vap", "Quận Gò Vấp"],
                   ["quan\. Gv", "Quận Gò Vấp"],
                   ["BT", "Quận Bình Thạnh"],
                   ["Binh Thanh", "Quận Bình Thạnh"],
                   ["qBinh Thanh", "Quận Bình Thạnh"],
                   ["qBT", "Quận Bình Thạnh"],
                   ["q Binh Thanh", "Quận Bình Thạnh"],
                   ["q BT", "Quận Bình Thạnh"],
                   ["q\.Binh Thanh", "Quận Bình Thạnh"],
                   ["q\.BT", "Quận Bình Thạnh"],
                   ["q\. Binh Thanh", "Quận Bình Thạnh"],
                   ["q\. BT", "Quận Bình Thạnh"],
                   ["quan Binh Thanh", "Quận Bình Thạnh"],
                   ["quan BT", "Quận Bình Thạnh"],
                   ["quan\.Binh Thanh", "Quận Bình Thạnh"],
                   ["quan\.BT", "Quận Bình Thạnh"],
                   ["quan\. Binh Thanh", "Quận Bình Thạnh"],
                   ["quan\. BT", "Quận Bình Thạnh"],
                   ["Binh Tan", "Quận Bình Tân"],
                   ["BT", "Quận Bình Tân"],
                   ["qBinh Tan", "Quận Bình Tân"],
                   ["qBT", "Quận Bình Tân"],
                   ["q Binh Tan", "Quận Bình Tân"],
                   ["q BT", "Quận Bình Tân"],
                   ["q\.Binh Tan", "Quận Bình Tân"],
                   ["q\.BT", "Quận Bình Tân"],
                   ["q\. Binh Tan", "Quận Bình Tân"],
                   ["q\. BT", "Quận Bình Tân"],
                   ["quan Binh Tan", "Quận Bình Tân"],
                   ["quan BT", "Quận Bình Tân"],
                   ["quan\.Binh Tan", "Quận Bình Tân"],
                   ["quan\.BT", "Quận Bình Tân"],
                   ["quan\. Binh Tan", "Quận Bình Tân"],
                   ["quan\. BT", "Quận Bình Tân"],
                   ["Tan Binh", "Quận Tân Bình"],
                   ["qTan Binh", "Quận Tân Bình"],
                   ["q Tan Binh", "Quận Tân Bình"],
                   ["q\.Tan Binh", "Quận Tân Bình"],
                   ["q\. Tan Binh", "Quận Tân Bình"],
                   ["quan Tan Binh", "Quận Tân Bình"],
                   ["quan\.Tan Binh", "Quận Tân Bình"],
                   ["quan\. Tan Binh", "Quận Tân Bình"],
                   ["PN", "Quận Phú Nhuận"],
                   ["qPN", "Quận Phú Nhuận"],
                   ["q PN", "Quận Phú Nhuận"],
                   ["q\.PN", "Quận Phú Nhuận"],
                   ["q\. PN", "Quận Phú Nhuận"],
                   ["quan PN", "Quận Phú Nhuận"],
                   ["quan\.PN", "Quận Phú Nhuận"],
                   ["quan\. PN", "Quận Phú Nhuận"],
                   ["Phu Nhuan", "Quận Phú Nhuận"],
                   ["qPhu Nhuan", "Quận Phú Nhuận"],
                   ["q Phu Nhuan", "Quận Phú Nhuận"],
                   ["q\.Phu Nhuan", "Quận Phú Nhuận"],
                   ["q\. Phu Nhuan", "Quận Phú Nhuận"],
                   ["quan Phu Nhuan", "Quận Phú Nhuận"],
                   ["quan\.Phu Nhuan", "Quận Phú Nhuận"],
                   ["quan\. Phu Nhuan", "Quận Phú Nhuận"],
                   ["PN", "Quận Phú Nhuận"],
                   ["qPN", "Quận Phú Nhuận"],
                   ["q PN", "Quận Phú Nhuận"],
                   ["q\.PN", "Quận Phú Nhuận"],
                   ["q\. PN", "Quận Phú Nhuận"],
                   ["quan PN", "Quận Phú Nhuận"],
                   ["quan\.PN", "Quận Phú Nhuận"],
                   ["quan\. PN", "Quận Phú Nhuận"],
                   ["Tan Phu", "Quận Tân Phú"],
                   ["qTan Phu", "Quận Tân Phú"],
                   ["q Tan Phu", "Quận Tân Phú"],
                   ["q\.Tan Phu", "Quận Tân Phú"],
                   ["q\. Tan Phu", "Quận Tân Phú"],
                   ["quan Tan Phu", "Quận Tân Phú"],
                   ["quan\.Tan Phu", "Quận Tân Phú"],
                   ["quan\. Tan Phu", "Quận Tân Phú"],
                   ["qTP", "Quận Tân Phú"],
                   ["q TP", "Quận Tân Phú"],
                   ["q\.TP", "Quận Tân Phú"],
                   ["q\. TP", "Quận Tân Phú"],
                   ["quan TP", "Quận Tân Phú"],
                   ["quan\.TP", "Quận Tân Phú"],
                   ["quan\. TP", "Quận Tân Phú"],
                   ["Nha Be", "Huyện Nhà Bè"],
                   ["qNha Be", "Huyện Nhà Bè"],
                   ["q Nha Be", "Huyện Nhà Bè"],
                   ["q\.Nha Be", "Huyện Nhà Bè"],
                   ["q\. Nha Be", "Huyện Nhà Bè"],
                   ["quan Nha Be", "Huyện Nhà Bè"],
                   ["quan\.Nha Be", "Huyện Nhà Bè"],
                   ["quan\. Nha Be", "Huyện Nhà Bè"],
                   ["Nha Be", "Huyện Nhà Bè"],
                   ["hNha Be", "Huyện Nhà Bè"],
                   ["h Nha Be", "Huyện Nhà Bè"],
                   ["h\.Nha Be", "Huyện Nhà Bè"],
                   ["h\. Nha Be", "Huyện Nhà Bè"],
                   ["quan Nha Be", "Huyện Nhà Bè"],
                   ["huyen\.Nha Be", "Huyện Nhà Bè"],
                   ["huyen\. Nha Be", "Huyện Nhà Bè"],
                   ["NB", "Huyện Nhà Bè"],
                   ["qNB", "Huyện Nhà Bè"],
                   ["q NB", "Huyện Nhà Bè"],
                   ["q\.NB", "Huyện Nhà Bè"],
                   ["q\. NB", "Huyện Nhà Bè"],
                   ["quan NB", "Huyện Nhà Bè"],
                   ["quan\.NB", "Huyện Nhà Bè"],
                   ["quan\. NB", "Huyện Nhà Bè"],
                   ["NB", "Huyện Nhà Bè"],
                   ["hNB", "Huyện Nhà Bè"],
                   ["h NB", "Huyện Nhà Bè"],
                   ["h\.NB", "Huyện Nhà Bè"],
                   ["h\. NB", "Huyện Nhà Bè"],
                   ["huyen NB", "Huyện Nhà Bè"],
                   ["huyen\.NB", "Huyện Nhà Bè"],
                   ["huyen\. NB", "Huyện Nhà Bè"],
                   ["Thu Duc", "Quận Thủ Đức"],
                   ["qThu Duc", "Quận Thủ Đức"],
                   ["q Thu Duc", "Quận Thủ Đức"],
                   ["q\.Thu Duc", "Quận Thủ Đức"],
                   ["q\. Thu Duc", "Quận Thủ Đức"],
                   ["quan Thu Duc", "Quận Thủ Đức"],
                   ["quan\.Thu Duc", "Quận Thủ Đức"],
                   ["quan\. Thu Duc", "Quận Thủ Đức"],
                   ["TD", "Quận Thủ Đức"],
                   ["qTD", "Quận Thủ Đức"],
                   ["q TD", "Quận Thủ Đức"],
                   ["q\.TD", "Quận Thủ Đức"],
                   ["q\. TD", "Quận Thủ Đức"],
                   ["quan TD", "Quận Thủ Đức"],
                   ["quan\.TD", "Quận Thủ Đức"],
                   ["quan\. TD", "Quận Thủ Đức"],
                   ["Binh Chanh", "Huyện Bình Chánh"],
                   ["qBinh Chanh", "Huyện Bình Chánh"],
                   ["q Binh Chanh", "Huyện Bình Chánh"],
                   ["q\.Binh Chanh", "Huyện Bình Chánh"],
                   ["q\. Binh Chanh", "Huyện Bình Chánh"],
                   ["quan Binh Chanh", "Huyện Bình Chánh"],
                   ["quan\.Binh Chanh", "Huyện Bình Chánh"],
                   ["quan\. Binh Chanh", "Huyện Bình Chánh"],
                   ["Binh Chanh", "Huyện Bình Chánh"],
                   ["hBinh Chanh", "Huyện Bình Chánh"],
                   ["h Binh Chanh", "Huyện Bình Chánh"],
                   ["h\.Binh Chanh", "Huyện Bình Chánh"],
                   ["h\. Binh Chanh", "Huyện Bình Chánh"],
                   ["huyen Binh Chanh", "Huyện Bình Chánh"],
                   ["huyen\.Binh Chanh", "Huyện Bình Chánh"],
                   ["huyen\. Binh Chanh", "Huyện Bình Chánh"],
                   ["BC", "Huyện Bình Chánh"],
                   ["qBC", "Huyện Bình Chánh"],
                   ["q BC", "Huyện Bình Chánh"],
                   ["q\.BC", "Huyện Bình Chánh"],
                   ["q\. BC", "Huyện Bình Chánh"],
                   ["quan BC", "Huyện Bình Chánh"],
                   ["quan\.BC", "Huyện Bình Chánh"],
                   ["quan\. BC", "Huyện Bình Chánh"],
                   ["BC", "Huyện Bình Chánh"],
                   ["hBC", "Huyện Bình Chánh"],
                   ["h BC", "Huyện Bình Chánh"],
                   ["h\.BC", "Huyện Bình Chánh"],
                   ["h\. BC", "Huyện Bình Chánh"],
                   ["huyen BC", "Huyện Bình Chánh"],
                   ["huyen\.BC", "Huyện Bình Chánh"],
                   ["huyen\. BC", "Huyện Bình Chánh"],
                   ["Binh Chanh", "Huyện Bình Chánh"],
                   ["qBinh Chanh", "Huyện Bình Chánh"],
                   ["q Binh Chanh", "Huyện Bình Chánh"],
                   ["q\.Binh Chanh", "Huyện Bình Chánh"],
                   ["q\. Binh Chanh", "Huyện Bình Chánh"],
                   ["quan Binh Chanh", "Huyện Bình Chánh"],
                   ["quan\.Binh Chanh", "Huyện Bình Chánh"],
                   ["quan\. Binh Chanh", "Huyện Bình Chánh"],
                   ["Cu Chi", "Huyện Củ Chi"],
                   ["hCu Chi", "Huyện Củ Chi"],
                   ["h Cu Chi", "Huyện Củ Chi"],
                   ["h\.Cu Chi", "Huyện Củ Chi"],
                   ["h\. Cu Chi", "Huyện Củ Chi"],
                   ["huyen Cu Chi", "Huyện Củ Chi"],
                   ["huyen\.Cu Chi", "Huyện Củ Chi"],
                   ["huyen\. Cu Chi", "Huyện Củ Chi"],
                   ["CC", "Huyện Củ Chi"],
                   ["qCC", "Huyện Củ Chi"],
                   ["q CC", "Huyện Củ Chi"],
                   ["q\.CC", "Huyện Củ Chi"],
                   ["q\. CC", "Huyện Củ Chi"],
                   ["quan CC", "Huyện Củ Chi"],
                   ["quan\.CC", "Huyện Củ Chi"],
                   ["quan\. CC", "Huyện Củ Chi"],
                   ["CC", "Huyện Củ Chi"],
                   ["hCC", "Huyện Củ Chi"],
                   ["h CC", "Huyện Củ Chi"],
                   ["h\.CC", "Huyện Củ Chi"],
                   ["h\. CC", "Huyện Củ Chi"],
                   ["huyen CC", "Huyện Củ Chi"],
                   ["huyen\.CC", "Huyện Củ Chi"],
                   ["huyen\. CC", "Huyện Củ Chi"],
                   ["Hoc Mon", "Huyện Hóc Môn"],
                   ["hHoc Mon", "Huyện Hóc Môn"],
                   ["h Hoc Mon", "Huyện Hóc Môn"],
                   ["h\.Hoc Mon", "Huyện Hóc Môn"],
                   ["h\. Hoc Mon", "Huyện Hóc Môn"],
                   ["huyen Hoc Mon", "Huyện Hóc Môn"],
                   ["huyen\.Hoc Mon", "Huyện Hóc Môn"],
                   ["huyen\. Hoc Mon", "Huyện Hóc Môn"],
                   ["HM", "Huyện Hóc Môn"],
                   ["qHM", "Huyện Hóc Môn"],
                   ["q HM", "Huyện Hóc Môn"],
                   ["q\.HM", "Huyện Hóc Môn"],
                   ["q\. HM", "Huyện Hóc Môn"],
                   ["quan HM", "Huyện Hóc Môn"],
                   ["quan\.HM", "Huyện Hóc Môn"],
                   ["quan\. HM", "Huyện Hóc Môn"],
                   ["HM", "Huyện Hóc Môn"],
                   ["hHM", "Huyện Hóc Môn"],
                   ["h HM", "Huyện Hóc Môn"],
                   ["h\.HM", "Huyện Hóc Môn"],
                   ["h\. HM", "Huyện Hóc Môn"],
                   ["huyen HM", "Huyện Hóc Môn"],
                   ["huyen\.HM", "Huyện Hóc Môn"],
                   ["huyen\. HM", "Huyện Hóc Môn"]]


wardListHCM = [["Tan Dinh","Phường Tân Định"],
["Da Kao","Phường Đa Kao"],
["Dakao","Phường Đa Kao"],
["Ben Nghe","Phường Bến Nghé"],
["Ben Thanh","Phường Bến Thành"],
["phuong Nguyen Thai Binh","Phường Nguyễn Thái Bình"],
["P. Nguyen Thai Binh","Phường Nguyễn Thái Bình"],
["Nguyen Thai Binh ward","Phường Nguyễn Thái Bình"],
["Pham Ngu Lao","Phường Phạm Ngũ Lão"],
["Ong Lanh","Phường Cầu Ông Lãnh"],
["phuong Co Giang","Phường Cô Giang"],
["Co Giang","Phường Cô Giang"],
["Nguyen Cu Trinh","Phường Nguyễn Cư Trinh"],
["Cau Kho","Phường Cầu Kho"],
["Tan Son Nhi","Phường Tân Sơn Nhì"],
["p.10", "Phường 10"],
["p\.10", "Phường 10"],
["p.\ 10", "Phường 10"],
["phuong 10", "Phường 10"],
["ward 10", "Phường 10"],
["10 ward", "Phường 10"],
["p.11", "Phường 11"],
["p\.11", "Phường 11"],
["p.\ 11", "Phường 11"],
["phuong 11", "Phường 11"],
["Ward 11", "Phường 11"],
["11 Ward", "Phường 11"],
["p.12", "Phường 12"],
["p\.12", "Phường 12"],
["p.\ 12", "Phường 12"],
["phuong 12", "Phường 12"],
["ward 12", "Phường 12"],
["12 ward", "Phường 12"],
["p.13", "Phường 13"],
["p\.13", "Phường 13"],
["p.\ 13", "Phường 13"],
["phuong 13", "Phường 13"],
["Ward 13", "Phường 13"],
["13 ward", "Phường 13"],
["p.14", "Phường 14"],
["p\.14", "Phường 14"],
["p.\ 14", "Phường 14"],
["phuong 14", "Phường 14"],
["ward 14", "Phường 14"],
["14 ward", "Phường 14"],
["p.15", "Phường 15"],
["p\.15", "Phường 15"],
["p.\ 15", "Phường 15"],
["phuong 15", "Phường 15"],
["ward 15", "Phường 15"],
["15 ward", "Phường 15"],
["p.16", "Phường 16"],
["p\.16", "Phường 16"],
["p.\ 16", "Phường 16"],
["phuong 16", "Phường 16"],
["ward 16", "Phường 16"],
["16 ward", "Phường 16"],
["p.17", "Phường 17"],
["p\.17", "Phường 17"],
["p.\ 17", "Phường 17"],
["phuong 17", "Phường 17"],
["ward 17", "Phường 17"],
["17 ward", "Phường 17"],
["p.18", "Phường 18"],
["p\.18", "Phường 18"],
["p.\ 18", "Phường 18"],
["phuong 18", "Phường 18"],
["ward 18", "Phường 18"],
["18 ward", "Phường 18"],
["p.19", "Phường 19"],
["p\.19", "Phường 19"],
["p.\ 19", "Phường 19"],
["phuong 19", "Phường 19"],
["ward 19", "Phường 19"],
["19 ward", "Phường 19"],
["p.20", "Phường 20"],
["p\.20", "Phường 20"],
["p.\ 20", "Phường 20"],
["phuong 20", "Phường 20"],
["ward 20", "Phường 20"],
["20 ward", "Phường 20"],
["p.21", "Phường 21"],
["p\.21", "Phường 21"],
["p.\ 21", "Phường 21"],
["phuong 21", "Phường 21"],
["ward 21", "Phường 21"],
["21 ward", "Phường 21"],
["p.22", "Phường 22"],
["p\.22", "Phường 22"],
["p.\ 22", "Phường 22"],
["phuong 22", "Phường 22"],
["ward 22", "Phường 22"],
["22 ward", "Phường 22"],
["p.23", "Phường 23"],
["p\.23", "Phường 23"],
["p.\ 23", "Phường 23"],
["phuong 23", "Phường 23"],
["ward 23", "Phường 23"],
["23 ward", "Phường 23"],
["p.24", "Phường 24"],
["p\.24", "Phường 24"],
["p.\ 24", "Phường 24"],
["phuong 24", "Phường 24"],
["ward 24", "Phường 24"],
["24 ward", "Phường 24"],
["p.25", "Phường 25"],
["p\.25", "Phường 25"],
["p.\ 25", "Phường 25"],
["phuong 25", "Phường 25"],
["ward 25", "Phường 25"],
["25 ward", "Phường 25"],
["p.26", "Phường 26"],
["p\.26", "Phường 26"],
["p.\ 26", "Phường 26"],
["phuong 26", "Phường 26"],
["ward 26", "Phường 26"],
["26 ward", "Phường 26"],
["p.27", "Phường 27"],
["p\.27", "Phường 27"],
["p.\ 27", "Phường 27"],
["phuong 27", "Phường 27"],
["ward 27", "Phường 27"],
["27 ward", "Phường 27"],
["p.28", "Phường 28"],
["p\.28", "Phường 28"],
["p.\ 28", "Phường 28"],
["phuong 28", "Phường 28"],
["ward 28", "Phường 28"],
["28 ward", "Phường 28"],
["p.29", "Phường 29"],
["p\.29", "Phường 29"],
["p.\ 29", "Phường 29"],
["phuong 29", "Phường 29"],
["ward 29", "Phường 29"],
["29 ward", "Phường 29"],
["p.30", "Phường 30"],
["p\.30", "Phường 30"],
["p.\ 30", "Phường 30"],
["phuong 30", "Phường 30"],
["ward 30", "Phường 30"],
["30 ward", "Phường 30"],
["p.1", "Phường 1"],
["p\.1", "Phường 1"],
["p.\ 1", "Phường 1"],
["phuong 01", "Phường 1"],
["phuong 1", "Phường 1"],
["ward 01", "Phường 1"],
["ward 1", "Phường 1"],
["01 ward", "Phường 1"],
["1 ward", "Phường 1"],
["p.2", "Phường 2"],
["p\.2", "Phường 2"],
["p.\ 2", "Phường 2"],
["phuong 2", "Phường 2"],
["phuong 02", "Phường 2"],
["Ward 02", "Phường 2"],
["ward 2", "Phường 2"],
["2 ward", "Phường 2"],
["02 ward", "Phường 2"],
["p.3", "Phường 3"],
["p\.3", "Phường 3"],
["p.\ 3", "Phường 3"],
["phuong 3", "Phường 3"],
["phuong 03", "Phường 3"],
["3 Ward", "Phường 3"],
["ward 03", "Phường 3"],
["ward 3", "Phường 3"],
["03 ward", "Phường 3"],
["xa Binh Hung","Xã Bình Hưng"],
["p.4", "Phường 4"],
["p\.4", "Phường 4"],
["p.\ 4", "Phường 4"],
["phuong 04", "Phường 4"],
["phuong 4", "Phường 4"],
["4 Ward", "Phường 4"],
["ward 04", "Phường 4"],
["ward 4", "Phường 4"],
["p.5", "Phường 5"],
["p\.5", "Phường 5"],
["p.\ 5", "Phường 5"],
["phuong 5", "Phường 5"],
["phuong 05", "Phường 5"],
["Ward 05", "Phường 5"],
["ward 5", "Phường 5"],
["5 ward", "Phường 5"],
["p.6", "Phường 6"],
["p\.6", "Phường 6"],
["p.\ 6", "Phường 6"],
["phuong 6", "Phường 6"],
["phuong 06", "Phường 6"],
["Ward 06", "Phường 6"],
["ward 6", "Phường 6"],
["6 ward", "Phường 6"],
["p.7", "Phường 7"],
["p\.7", "Phường 7"],
["p.\ 7", "Phường 7"],
["phuong 7", "Phường 7"],
["Ward 07", "Phường 7"],
["Ward 7", "Phường 7"],
["7 ward", "Phường 7"],
["p.8", "Phường 8"],
["p\.8", "Phường 8"],
["p.\ 8", "Phường 8"],
["phuong 8", "Phường 8"],
["phuong 08", "Phường 8"],
["Ward 08", "Phường 8"],
["Ward 8", "Phường 8"],
["8 ward", "Phường 8"],
["p.9", "Phường 9"],
["p\.9", "Phường 9"],
["p.\ 9", "Phường 9"],
["phuong 9", "Phường 9"],
["phuong 09", "Phường 9"],
["Ward 9", "Phường 9"],
["ward 09", "Phường 9"],
["9 ward", "Phường 9"],
["Thao Dien","Phường Thảo Điền"],
['phuong An Phu',"Phường An Phú"],
['An Phu ward',"Phường An Phú"],
["phuong Binh An","Phường Bình An"],
["Binh An","Phường Bình An"],
["phuong Binh Trung Dong","Phường Bình Trưng Đông"],
["phuong Binh Trung Dong","Phường Bình Trưng Đông"],
["Binh Trung Tay","Phường Bình Trưng Tây"],
["Binh Khanh","Phường Bình Khánh"],
["An Khanh","Phường An Khánh"],
["Cat Lai","Phường Cát Lái"],
["Thanh My Loi","Phường Thạnh Mỹ Lợi"],
["An Loi Dong","Phường An Lợi Đông"],
["Thu Thiem","Phường Thủ Thiêm"],
["Tay Thanh","Phường Tây Thạnh"],
["Son Ky","Phường Sơn Kỳ"],
["Tan Quy","Phường Tân Quý"],
["Tan Thanh","Phường Tân Thành"],
["Phu Tho Hoa","Phường Phú Thọ Hòa"],
["Phu Thanh","Phường Phú Thạnh"],
["Phu Trung","Phường Phú Trung"],
["Hoa Thanh","Phường Hòa Thạnh"],
["phuong Hiep Tan","Phường Hiệp Tân"],
["Tan Thoi Hoa","Phường Tân Thới Hòa"],
["Thanh Xuanh","Phường Thạnh Xuân"],
["Thanh Loc","Phường Thạnh Lộc"],
["Hiep Thanh","Phường Hiệp Thành"],
["Thoi An","Phường Thới An"],
["Tan Chanh Hiep","Phường Tân Chánh Hiệp"],
["An Phu Dong", "Phường An Phú Đông"],
["Tan Thoi Hiep", "Phường Tân Thới Hiệp"],
["Trung My Tay","Phường Trung Mỹ Tây"],
["Tan Hung Thuan", "Phường Tân Hưng Thuận"],
["Dong Hung Thuan", "Phường Đông Hưng Thuận"],
["Tan Thoi Nhat","Phường Tân Thới Nhất"],
["Linh Xuan","Phường Linh Xuân"],
["Binh Chieu", "Phường Bình Chiểu"],
["Linh Trung","Phường Linh Trung"],
["Tam Binh","Phường Tam Bình"],
["Tam Phu","Phường Tam Phú"],["phuong Hiep Binh Phuoc","Phường Hiệp Bình Phước"],
["Hiep Binh Phuoc","Phường Hiệp Bình Phước"],
["Hiep Binh Chanh","Phường Hiệp Bình Chánh"],
["Linh Chieu", "Phường Linh Chiểu"],
["Linh Tay", "Phường Linh Tây"],
["Linh Dong", "Phường Linh Đông"],
["Binh Tho","Phường Bình Thọ"],
["Truong Tho","Phường Trường Thọ"],
["Long Binh","Phường Long Bình"],
["Phường Long","Thạnh Mỹ"],
["Hiep Phu","Phường Hiệp Phú"],
["Tang Nhon Phu A","Phường Tăng Nhơn Phú A"],
["Tang Nhon Phu B","Phường Tăng Nhơn Phú B"],
["Phuoc Long B","Phường Phước Long B"],
["Phuoc Long A","Phường Phước Long A"],
["Truong Thanh","Phường Trường Thạnh"],
["Long Phuoc", "Phường Long Phước"],
["Long Truong","Phường Long Trường"],
["Phuoc Binh","Phường Phước Bình"],
["Phu Huu","Phường Phú Hữu"],
["Binh Hung Hoa A","Phường Bình Hưng Hoà A"],
["Binh Hung Hoa B","Phường Bình Hưng Hoà B"],
["Binh Hung Hoa","Phường Bình Hưng Hòa"],
["Binh Hung","Xã Bình Hưng"],
["xa Binh Hung","Xã Bình Hưng"],
["Binh Tri Dong A","Phường Bình Trị Đông A"],
["Binh Tri Dong B","Phường Bình Trị Đông B"],
["Binh Tri Dong","Phường Bình Trị Đông"],
["Tan Tao A","Phường Tân Tạo A"],
["Tan Tao","Phường Tân Tạo"],
["An Lac A","Phường An Lạc A"],
["An Lac","Phường An Lạc"],
["Tan Thuan Dong","Phường Tân Thuận Đông"],
["Tan Thuan Tay","Phường Tân Thuận Tây"],
["Tan Kieng","Phường Tân Kiểng"],
["Tan Hung","Phường Tân Hưng"],
["Binh Thuan","Phường Bình Thuận"],
["Tan Quy","Phường Tân Quy"],
["P.Phu Thuan","Phường Phú Thuận"],
["Tan Phong","Phường Tân Phong"],
['phu my hung','Khu đô thị Phú Mỹ Hưng'],
["Phu My","Phường Phú Mỹ"],
["TT.Cu Chi","Thị trấn Củ Chi"],
["xa Phu My Hung","Xã Phú Mỹ Hưng"],
["xa An Phu","Xã An Phú"],
["Trung Lap Thuong","Xã Trung Lập Thượng"],
["An Nhon Tay","Xã An Nhơn Tây"],
["Thuan Duc","Xã Nhuận Đức"],
["Pham Van Coi","Xã Phạm Văn Cội"],
["Phu Hoa","Xã Phú Hòa Đông"],
["Trung Lap Ha","Xã Trung Lập Hạ"],
["Trung An","Xã Trung An"],
["Phuoc Thanh","Xã Phước Thạnh"],
["Phuoc Hiep","Xã Phước Hiệp"],
["Tan An Hoi","Xã Tân An Hội"],
["Phuoc Vinh An","Xã Phước Vĩnh An"],
["Thai My","Xã Thái Mỹ"],
["Tan Thanh Tay","Xã Tân Thạnh Tây"],
["Hoa Phu","Xã Hòa Phú"],
["Tan Thanh Dong","Xã Tân Thạnh Đông"],
["Binh My","Xã Bình Mỹ"],
["Tan Phu Trung","Xã Tân Phú Trung"],
["Tan Thong Hoi","Xã Tân Thông Hội"],
["Hoc Mon","Thị trấn Hóc Môn"],
["Tan Hiep","Xã Tân Hiệp"],
["Nhi Binh","Xã Nhị Bình"],
["Dong Thanh","Xã Đông Thạnh"],
["Tan Thoi Nhi","Xã Tân Thới Nhì"],
["Thoi Tam Thon","Xã Thới Tam Thôn"],
["Xuan Thoi Son","Xã Xuân Thới Sơn"],
["Tan Xuan","Xã Tân Xuân"],
["Xuan Thoi Dong","Xã Xuân Thới Đông"],
["Trung Chanh","Xã Trung Chánh"],
["Xuan Thoi Thuong","Xã Xuân Thới Thượng"],
["Ba Diem","Xã Bà Điểm"],
["Tan Tuc","Thị trấn Tân Túc"],
["Pham Van Hai","Xã Phạm Văn Hai"],
["Vinh Loc A","Xã Vĩnh Lộc A"],
["Vinh Loc B","Xã Vĩnh Lộc B"],
["Binh Loi","Xã Bình Lợi"],
["Le Minh Xuan","Xã Lê Minh Xuân"],
["Tan Nhut","Xã Tân Nhựt"],
["Tan Kien","Xã Tân Kiên"],
["Phong Phu","Xã Phong Phú"],
["An Phu Tay","Xã An Phú Tây"],
["Hung Long","Xã Hưng Long"],
["Da Phuoc","Xã Đa Phước"],
["Tan Quy Tay","Xã Tân Quý Tây"],
["Quy Duc","Xã Quy Đức"],
["Nha Be","Thị trấn Nhà Bè"],
["Phuoc Kien","Xã Phước Kiển"],
["Phuoc Loc","Xã Phước Lộc"],
["Nhon Duc","Xã Nhơn Đức"],
["Phu Xuan","Xã Phú Xuân"],
["Long Thoi","Xã Long Thới"],
["Hiep Phuoc","Xã Hiệp Phước"],
["Can Thanh","Thị trấn Cần Thạnh"],
["Binh Khanh","Xã Bình Khánh"],
["Tam Thon Hiep","Xã Tam Thôn Hiệp"],
["An Thoi Dong","Xã An Thới Đông"],
["Thanh An","Xã Thạnh An"],
["Long Hoa","Xã Long Hòa"],
["Binh Chanh","Xã Bình Chánh"],
["Ly Nhon","Xã Lý Nhơn"],
["Tan Phu","Phường Tân Phú"]]

##---------------------------------------------------------------------------------------------------------------------##

streetListHCM = [["Alexandre","Alexandre de Rhodes"], ["huyen quang","Huyền Quang"],	["nguyen hau","Nguyễn Hậu"], 
["phan ke binh","Phan Kế Bính"],['ba le chan',"Bà lê Chân"], ['huyen chan cong chua','Huyền Chân Công Chúa'], 
['dai lo nguyen hue','Nguyễn Huệ'], ['nguyen hue','Nguyễn Huệ'],['phan liem','Phan Liêm'], 
['ben chuong duong','Bến Chương Dương'],['huynh khuong ninh','Huỳnh Khương Ninh'],
['duong nguyen huu canh','Nguyễn Hữu Cảnh'],['nguyen huu canh','Nguyễn Hữu Cảnh'],	['phan ngu','Phan Ngữ'],
['duong bui thi xuan','Bùi Thị Xuân'],['bui thi xuan','Bùi Thị Xuân'],['huynh thuc khang','Huỳnh Thúc Kháng'],
['nguyen huu cau','Nguyễn Hữu Cầu'],	['phan ton','Phan Tôn'], ['duong bui vien','Bùi Viện'],['bui vien','Bùi Viện'], 
['khanh hoi','Khánh Hội'],['nguyen huy tu','Nguyễn Huy Tự'],['phan van dat','Phan Văn Đạt'], ['cach mang thang tam','Cách Mạnh Thánh 8'],
['cach mang thang 8','Cách Mạnh Thánh 8'],	['duong ky con', 'Ký Con'],
['ki con', 'Ký Con'],['ky con', 'Ký Con'],	['nguyen khac nhu','Nguyễn Khắc Nhu'],	
['phan van truong','Phan Văn Trường'],['duong le lai','Lê Lai'],
['duong le anh xuan','Lê Anh Xuân'],['le anh xuan','Lê Anh Xuân'],['nguyen phi khanh','Nguyễn Phi Khanh'],
['pho duc chinh','Phó Đức Chính'], ['cao ba nha','Cao Bá Nhạ'],['le cong kieu','Lê Công Kiều'],	
['nguyen sieu','Nguyễn Siêu'],	['phung khac khoan','Phùng Khắc Khoan'],['cao ba quat','Cao Bá Quát'],	
['dai lo le duan','Lê Duẩn'],	['le duan','Lê Duẩn'],['duong nguyen cong tru','Nguyễn Công Trứ'],
['nguyen cong tru','Nguyễn Công Trứ'],	['duong nguyen thai binh','Nguyễn Thái Bình'],
['nguyen thai binh street','Nguyễn Thái Bình'],['nguyen thai binh st','Nguyễn Thái Bình'],
['suong nguyet anh','Sương Nguyệt Ánh'], ['cay diep','Cây Điệp'], ['duong calmette','Calmette'],['calmette','Calmette'],
['le lai','Lê Lai'],	['duong nguyen thi minh khai','Nguyễn Thị Minh Khai'],['nguyen thai hoc','Nguyễn Thái Học'],	
['thach thi thanh','Thạch Thị Thanh'], ['duong thai van lung','Thái Văn Lung'], ['duong diep minh chau','Diệp Minh Châu'],
['diep minh chau','Diệp Minh Châu'],['binh gia','Bình Giã'],['duong binh gia','Bình Giã'],
['chu manh chinh','Chu Mạnh Chinh'],['duong le loi','Lê Lợi'],['le loi','Lê Lợi'],	
['nguyen thanh y','Nguyễn Thành Ý'],['thai van lung','Thái Văn Lung'],['dai lo tran hung dao','Trần Hưng Đạo'],
['co bac','Cô Bắc'],	['duong le thanh ton','Lê Thánh Tôn'],['le thanh ton','Lê Thánh Tôn'],	['tran hung dao','Trần Hưng Đạo'], 
['nguyen thi luu','Nguyễn Thị Lựu'],['thi sach','Thi Sách'],['co giang','Cô Giang'], 
['duong le thi hong gam','Lê Thị Hồng Gấm'],['le thi hong gam','Lê Thị Hồng Gấm'],	
['nguyen thi minh khai','Nguyễn Thị Minh Khai'],['duong thu khoa huan','Thủ Khoa Huân'],
['thu khoa huan','Thủ Khoa Huân'], ['thu khoan huan','Thủ Khoa Huân'], ['duong cong quynh','Cống Quỳnh'], 
['cong quynh','Cống Quỳnh'],['le thi rieng','Lê Thị Riêng'],['nguyen thi nghia','Nguyễn Thị Nghĩa'],	
['duong ton duc thang','Tôn Đức Thắng'],['ton duc thang','Tôn Đức Thắng'], ['cong truong lam son','Công Trường Lam Sơn'],	
['le van huu','Lê Văn Hưu'],	['nguyen thien thuat','Nguyễn Thiện Thuật'],['ton that dam','Tôn Thất Đạm'],
['cong truong me linh','Công Trường Mê Linh'],	['luong huu khanh','Lương Hữu Khánh'],['nguyen thiep','Nguyễn Thiệp'],	
['ton that thiep','Tôn Thất Thiệp'], ['cong truong paris','Công Trường Paris'],	['luu van lang','Lưu Văn Lang'],	
['duong nguyen trai','Nguyễn Trãi'],['nguyen trai','Nguyễn Trãi'], ['duong ton that tung','Tôn Thất Tùng'],
['ton that tung','Tôn Thất Tùng'],['dang dung','Đặng Dung'],	['ly chien thang','Lý Chiến Thắng'],
['nguyen trung ngan','Nguyễn Trung Ngạn'],['tran cao van','Trần Cao Vân'], 
['dang tat','Đặng Tất'],	['duong ly tu trong','Lý Tự Trọng'], ['ly tu trong','Lý Tự Trọng'],	
['duong ly thai to','Lý Thái Tổ'], ['ly thai to','Lý Thái Tổ'],	['duong nguyen trung truc','Nguyễn Trung Trực'],
['nguyen trung truc','Nguyễn Trung Trực'],	['tran dinh xu','Trần Đình Xu'],
['dang thi nhu','Đặng Thị Nhu'],	['ly van phuc','Lý Văn Phức'],	['nguyen van binh','Nguyễn Văn Bình'],	
['tran doan khanh','Trần Doãn Khanh'], ['duong dang tran con','Đặng Trần Côn'],['dang tran con','Đặng Trần Côn'],
['ma lo','Mã Lộ'],	['nguyen van chiem','Nguyễn Văn Chiêm'],
['de tham','Đề Thám'],	['mac dinh chi','Mạc Đĩnh Chi'],['nguyen van cu','Nguyễn Văn Cừ'],	
['tran khac chan','Trần Khắc Chân'],['duong dien bien phu','Điện Biên Phủ'],['dien bien phu','Điện Biên Phủ'],	
['mac thi buoi','Mặc Thị Bưởi'],['nguyen van duom','Nguyễn Văn Đượm'],	['tran khanh du','Trần Khánh Dư'],
['dinh cong tranh','Đinh Công Tránh'],	['duong mai thi luu','Mai Thị Lựu'],['mai thi luu','Mai Thị Lựu'],	
['nguyen van giai','Nguyễn Văn Giai'], ['duong dong du','Đông Du'],	
['tran nhat duat','Trần Nhật Duật'], ['dinh tien hoang','Đinh Tiên Hoàng'],	
['nam ky khoi nghia','Nam Kỳ Khởi Nghĩa'],['nguyen van nghia','Nguyễn Văn Nghĩa'],['tran quang khai','Trần Quang Khải'],
['nam quoc cang','Nam Quốc Cang'],	['nguyen van nguyen','Nguyễn Văn Nguyên'],
['tran quoc toan','Trần Quốc Toản'], ['dong du','Đông Du'],	['ngo duc ke','Ngô Đức Kế'],
['nguyen van nguyen','Nguyễn Văn Nguyễn'],['tran quy khoach','Trần Quý Khoách'], ['dong khoi','Đồng Khởi'],	
['ngo quyen','Ngô Quyền'],	['nguyen van thu','Nguyễn Văn Thủ'],['trinh van can','Trịnh Văn Cấn'], 
['duong hai ba trung','Hai Bà Trưng'],['hai ba trung','Hai Bà Trưng'],	['duong ngo van nam','Ngô Văn Năm'],
['ngo van nam','Ngô Văn Năm'],['duong nguyen van trang','Nguyễn Văn Tráng'],	['nguyen van trang','Nguyễn Văn Tráng'],['trinh van can','Trịnh Văn Cẩn'],
['hai trieu','Hải Triều'],	['nguyen an ninh','Nguyễn An Ninh'],['nguyen van troi','Nguyễn Văn Trỗi'],	
['duong truong dinh','Trương Định'],	['truong dinh','Trương Định'],['ham nghi','Hàm Nghi'],	
['nguyen binh khiem','Nguyễn Bỉnh Khiêm'],	['duong Pasteur','Pasteur'], ['Pasteur','Pasteur'],	
['truong han sieu','Trương Hán Siêu'], ['han thuyen','Hàn Thuyên'],	['nguyen canh chan','Nguyễn Cảnh Chân'],	
['pham hong thai','Phạm Hồng Thái'],	['duong vo thi sau','Võ Thị Sáu'],['vo thi sau','Võ Thị Sáu'], 
['ho hao hon','Hồ Hảo Hớn'],['nguyen cong chu','Nguyễn Công Chứ'],	['pham ngoc thach','Phạm Ngọc Thạch'],	
['vo van kiet','Võ Văn Kiệt'],['duong ho huan nghiep','Hồ Huấn Nghiệp'],['ho huan nghiep','Hồ Huấn Nghiệp'],
['duong nguyen cu trinh','Nguyễn Cư Trinh'],['nguyen cu trinh','Nguyễn Cư Trinh'],	
['duong pham ngu lao','Phạm Ngũ Lão'],['pham ngu lao','Phạm Ngũ Lão'],	['vo van tan','Võ Văn Tần'],
['ho tung mau','Hồ Tùng Mậu'],	['nguyen cuu van','Nguyễn Cửu Vân'],	['pham viet chanh','Phạm Viết Chánh'],	
['yersin','Yersin'],['hoa my', 'Hòa Mỹ'],	['duong nguyen dinh chieu','Nguyễn Đình Chiểu'],
['nguyen dinh chieu','Nguyễn Đình Chiểu'],	['phan boi chau','Phan Bội Châu'],	
['hoang sa','Hoàng Sa'],	
['phan chu chinh','Phan Chu Chinh'], ['duong 26 thang 3','Đường 26 Tháng 3'], ['duong 26/3','Đường 26 Tháng 3'],

#duong so:
['duong so 490','Đường số 490'], ['duong so 456','Đường số 456'], ['duong so 366','Đường số 366'],
['duong so 82','Đường số 82'], ['road 64', 'Đường số 64'],
['duong so 66','Đường số 66'], ['duong so 65','Đường số 65'], ['duong so 64','Đường số 64'],
['duong so 63','Đường số 63'], ['duong so 62','Đường số 62'], ['duong so 61','Đường số 61'],
['duong so 60','Đường số 60'],['duong so 59','Đường số 59'],['duong so 58','Đường số 58'],
['duong so 57','Đường số 57'],['duong so 56','Đường số 56'],['duong so 55','Đường số 55'],
['duong so 54','Đường số 54'],['duong so 53','Đường số 53'],['duong so 52','Đường số 52'],
['duong so 51','Đường số 51'],['duong so 50','Đường số 50'],['duong so 49','Đường số 49'],
['duong so 48','Đường số 48'],['duong so 47','Đường số 47'],['duong so 46','Đường số 46'],
['duong so 45','Đường số 45'],['duong so 44','Đường số 44'],['duong so 43','Đường số 43'],
['duong so 42','Đường số 42'],['duong so 41','Đường số 41'],['duong so 40','Đường số 40'],
['duong so 39','Đường số 39'],['duong so 38','Đường số 38'],['duong so 37','Đường số 37'],
['duong so 36','Đường số 36'],['duong so 35','Đường số 35'],['duong so 34','Đường số 34'],
['duong so 33','Đường số 33'],['duong so 32','Đường số 32'],['duong so 31','Đường số 31'],
['duong so 30','Đường số 30'],['duong so 29','Đường số 29'],['duong so 28','Đường số 28'],
['duong so 27','Đường số 27'],['duong so 26','Đường số 26'],['duong so 25','Đường số 25'],
['duong so 24','Đường số 24'],['duong so 23','Đường số 23'],['duong so 22','Đường số 22'],
['duong so 21','Đường số 21'],['duong so 20','Đường số 20'],['duong so 19','Đường số 19'],
['duong so 18','Đường số 18'],['duong so 17','Đường số 17'],['duong so 16','Đường số 16'],
['duong so 15','Đường số 15'],['duong so 14','Đường số 14'],['duong so 13','Đường số 13'],
['duong so 12','Đường số 12'],['duong so 11','Đường số 11'],['duong so 10','Đường số 10'],
['duong so 9','Đường số 9'],['duong so 8','Đường số 8'],['duong so 7','Đường số 7'],
['duong so 6','Đường số 6'],['duong so 5','Đường số 5'],['duong so 4','Đường số 4'],
['duong so 3','Đường số 3'],['duong so 2','Đường số 2'],['duong so 1','Đường số 1'],
['street no. 20','Đường số 20'], ['street no. 19','Đường số 19'], ['street no. 18','Đường số 18'],
['street no. 17','Đường số 17'], ['street no. 16','Đường số 16'], ['street no. 15','Đường số 15'],
['street no. 14','Đường số 14'],['street no. 13','Đường số 13'], ['street no. 12','Đường số 12'],
['street no. 11','Đường số 11'], ['street no. 10','Đường số 10'], ['street no. 9','Đường số 9'],
['street no. 8','Đường số 8'],['street no. 7','Đường số 7'],['street no. 6','Đường số 6'],
['street no. 5','Đường số 5'],['street no. 4','Đường số 4'],['street no. 3','Đường số 3'], 
['street no. 2','Đường số 2'],['street no. 1','Đường số 1'],
['street number 60','Đường số 60'],['street number 59','Đường số 59'],['street number 58','Đường số 58'],
['street number 57','Đường số 57'],['street number 56','Đường số 56'],['street number 55','Đường số 55'],
['street number 54','Đường số 54'],['street number 53','Đường số 53'],['street number 52','Đường số 52'],
['street number 51','Đường số 51'],['street number 50','Đường số 50'],['street number 49','Đường số 49'],
['street number 48','Đường số 48'],['street number 47','Đường số 47'],['street number 46','Đường số 46'],
['street number 45','Đường số 45'],['street number 44','Đường số 44'],['street number 43','Đường số 43'],
['street number 42','Đường số 42'],['street number 41','Đường số 41'],['street number 40','Đường số 40'],
['street number 39','Đường số 39'],['street number 38','Đường số 38'],['street number 37','Đường số 37'],
['street number 36','Đường số 36'],['street number 35','Đường số 35'],['street number 34','Đường số 34'],
['street number 33','Đường số 33'],['street number 32','Đường số 32'],['street number 31','Đường số 31'],
['street number 30','Đường số 30'],['street number 29','Đường số 29'],['street number 28','Đường số 28'],
['street number 27','Đường số 27'],['street number 26','Đường số 26'],['street number 25','Đường số 25'],
['street number 24','Đường số 24'],['street number 23','Đường số 23'],['street number 22','Đường số 22'],
['street number 21','Đường số 21'],
['street number 20','Đường số 20'], ['street number 19','Đường số 19'], ['street number 18','Đường số 18'],
['street number 17','Đường số 17'], ['street number 16','Đường số 16'], ['street number 15','Đường số 15'],
['street number 14','Đường số 14'],['street number 13','Đường số 13'], ['street number 12','Đường số 12'],
['street number 11','Đường số 11'], ['street number 10','Đường số 10'], ['street number 9','Đường số 9'],
['street number 8','Đường số 8'],['street number 7','Đường số 7'],['street number 6','Đường số 6'],
['street number 5','Đường số 5'],['street number 4','Đường số 4'],['street number 3','Đường số 3'], 
['street number 2','Đường số 2'],['street number 1','Đường số 1'],
['street 60','Đường số 60'],['street 59','Đường số 59'],['street 58','Đường số 58'],
['street 57','Đường số 57'],['street 56','Đường số 56'],['street 55','Đường số 55'],
['street 54','Đường số 54'],['street 53','Đường số 53'],['street 52','Đường số 52'],
['street 51','Đường số 51'],['street 50','Đường số 50'],['street 49','Đường số 49'],
['street 48','Đường số 48'],['street 47','Đường số 47'],['street 46','Đường số 46'],
['street 45','Đường số 45'],['street 44','Đường số 44'],['street 43','Đường số 43'],
['street 42','Đường số 42'],['street 41','Đường số 41'],['street 40','Đường số 40'],
['street 39','Đường số 39'],['street 38','Đường số 38'],['street 37','Đường số 37'],
['street 36','Đường số 36'],['street 35','Đường số 35'],['street 34','Đường số 34'],
['street 33','Đường số 33'],['street 32','Đường số 32'],['street 31','Đường số 31'],
['street 30','Đường số 30'],['street 29','Đường số 29'],['street 28','Đường số 28'],
['street 27','Đường số 27'],['street 26','Đường số 26'],['street 25','Đường số 25'],
['street 24','Đường số 24'],['street 23','Đường số 23'],['street 22','Đường số 22'],
['street 21','Đường số 21'],
['street 20','Đường số 20'], ['street 19','Đường số 19'], ['street 18','Đường số 18'],
['street 17','Đường số 17'], ['street 16','Đường số 16'], ['street 15','Đường số 15'],
['street 14','Đường số 14'],['street 13','Đường số 13'], ['street 12','Đường số 12'],
['street 11','Đường số 11'], ['street 10','Đường số 10'], ['street 9','Đường số 9'],
['street 8','Đường số 8'],['street 7','Đường số 7'],['street 6','Đường số 6'],
['street 5','Đường số 5'],['street 4','Đường số 4'],['street 3','Đường số 3'], 
['street 2','Đường số 2'],['street 1','Đường số 1'],
#quan 10
['ba hat','Bà Hạt'],['ho ba kien','Hồ Bá Kiện'],['tam dao','Tam Đảo'],['ba vi','Ba Vì'],['ho thi ky','Hồ Thị Kỷ'],	 
['tan phuoc','Tân Phước'],['bac hai','Bắc Hải'],['hoa binh','Hòa Bình'], ['thanh thai','Thành Thái'],
['bach dang','Bạch Đằng'],	 ['hoa hao','Hòa Hảo'],['that son','Thất Sơn'],
['bach ma','Bạch Mã'],['hoa hung','Hòa Hưng'],['thien phuoc','Thiên Phước'],
['hoang du khuong','Hoàng Dư Khương'],['to hien thanh','Tô Hiến Thành'],
['buu long','Bửu Long'],['hoang van thu','Hoàng Văn Thụ'],['nguyen gian thanh','Nguyễn Giản Thanh'],	 
['hong linh','Hồng Lĩnh'],	['nguyen lam','Nguyễn Lâm'],['duong cuu long','Cửu Long'],
['chau thoi','Châu Thới'],	['hung long','Hưng Long'],	['nguyen ngoc loc','Nguyễn Ngọc Lộc'],
['cuu long','Cửu Long'],['tran quoc dung','Trần Quốc Dung'],['dao duy tu','Đào Duy Từ'],
['huong giang','Hương Giang'],['tran quy','Trần Quý'],['dao nguyen pho','Đào Nguyên Phổ'],	 
['nguyen tieu la','Nguyễn Tiểu La'],['tran thien chanh','Trần Thiện Chánh'], ['dat thanh','Đất Thánh'],	 
['ky hoa','Kỳ Hòa'],['lanh binh thang','Lãnh Binh Thăng'],['truong chinh','Trường Chinh'],
['dong nai','Đồng Nai'],['le dai hanh','Lê Đại Hành'],['nguyen van luong','Nguyễn Văn Lượng'],
['duong ba thang hai','Đường 3 Tháng 2'],['duong 3/2','Đường 3 Tháng 2'],['duong 3 thang 2','Đường 3 Tháng 2'],
['nhat tao','Nhật Tảo'],
['vinh vien','Vĩnh Viễn'],['hau thoi','Hầu Thới'],['lu gia','Lữ Gia'],['cong hoa','Cộng Hòa'],

#phu nhuan
['hoa hue','Hoa Huệ'],	['mai van ngoc','Mai Văn Ngọc'],	['phan dinh phung','Phan Đình Phùng'],
['hoa lan','Hoa Lan'],	['mai van nguyen','Mai Văn Nguyễn'],	['phan tay ho','Phan Tây Hồ'],
['cam ba thuoc','Cầm Bá Thước'], ['hoa mai','Hoa Mai'],	['nguyen cong hoan','Nguyễn Công Hoan'],	
['phan xich long','Phan Xích Long'],['co bac','Cô Bắc'],['hoa phuong','Hoa Phượng'],
['nguyen dinh chinh','Nguyễn Đình Chính'],	['pho quang','Phổ Quang'],
['hoa su','Hoa Sứ'],['phung van cung','Phùng Văn Cung'],['duong truong quoc dung','Trương Quốc Dung'],
['cu lao','Cù Lao'],['nguyen kiem','Nguyễn Kiệm'],['tan canh','Tân Cảnh'],
['dao duy anh','Đào Duy Anh'],	['nguyen thai son','Nguyễn Thái Sơn'],	['thich quang duc','Thích Quảng Đức'],
['hoang minh giam','Hoàng Minh Giám'],	['nguyen thi huynh','Nguyễn Thị Huỳnh'],
['dang thai mai','Đặng Thai Mai'],['tran huu trang','Trần Hữu Trang'],
['dang van ngu','Đặng Văn Ngữ'],['ho van hue','Hồ Văn Huê'],['nguyen trong tuyen','Nguyễn Trọng Tuyển'],	
['tran ke xuong','Trần Kế Xương'],['doan thi diem','Đoàn Thị Điểm'],
['hong ha','Hồng Hà'],['nguyen van dau','Nguyễn Văn Đậu'],['tran khac chan','Trần Khắc Chân'],
['hoa cau','Hoa Cau'],['hoa cuc','Hoa Cúc'],['lam son','Lam Sơn'],	['nhieu tu','Nhiêu Tứ'],
['truong dang que','Trương Đăng Quế'],['hoa dao','Hoa Đào'],['le tu tai','Lê Tư Tài'],	['noi\ bo','Nội Bộ'],
['truong quoc dung','Trương Quốc Dung'],['hoa hong','Hoa Hồng'],	['le van si','Lê Văn Sĩ'],	
['phan dang luu','Phan Đăng Lưu'],['nguyen duy cung','Nguyễn Duy Cung'],
#Q binh thanh
['bac binh','Bắc Bình'],['phan van han','Phan Văn Hân'],['nguyen cuu van','Nguyễn Cửu Vân'],['duong binh loi','Bình Lợi'],
['binh quoi','Bình Quới'],['bui dinh tuy','Bùi Đình Túy'],['duong phu my','Phú Mỹ'],['nguyen huy luong','Nguyễn Huy Lượng'],	 
["quoc lo 13","Quốc Lộ 13"],['nguyen huy tuong','Nguyễn Huy Tưởng'],['tam vu','Tầm Vu'],['cong truong hoa binh','Công Trường Hòa Bình'],
['cong truong tu do','Công Trường Tự Do'],['huynh dinh hai','Huỳnh Đình Hai'],['thanh da','Thanh Đa'],
['nguyen ngoc phuong','Nguyễn Ngọc Phương'],['dien hong','Diên Hồng'],['huynh ta bang','Huỳnh Tá Bang'],
['dinh bo linh','Đinh Bộ Lĩnh'],['tran quy cap','Trần Quý Cáp'],['dong da','Đống Đa'],['lai thieu','Lái Thiêu'],	 
['tran van ky','Trần Văn Kỷ'],['ung van khiem','Ung Văn Khiêm'],['nguyen van lac','Nguyễn Văn Lạc'],
['le tu tai','Lê Tự Tài'],['nguyen xi','Nguyễn Xí'],['van thanh bac','Văn Thánh Bắc'],
['nguyen xuan on','Nguyễn Xuân Ôn'],['vo duy ninh','Võ Duy Ninh'],['no trang long','Nơ Trang Long'],['vo thanh trang','Võ Thành Trang'],
['vu huy tan','Vũ Huy Tấn'],['vu ngoc phan','Vũ Ngọc Phan'],['vu tung','Vũ Tùng'],['ngo tat to','Ngô Tất Tố'],	 
['phan chu trinh','Phan Chu Trinh'],['duong xo viet nghe tinh','Xô Viết Nghệ Tĩnh'], ['xo viet nghe tinh','Xô Viết Nghệ Tĩnh'],
['xo viet nghe-tinh','Xô Viết Nghệ Tĩnh'],['yen do','Yên Đỗ'],['phan huy on','Phan Huy Ôn'],


# quan 2
['tran phu','Trần Phú'],['duong an phu - an khanh','An Phú - An Khánh'],['duong an phu','An Phú'], ['an phu street','An Phú'],
['nguyen hoang','Nguyễn Hoàng'],['binh minh','Bình Minh'], ['nguyen quy canh','Nguyễn Quý Cảnh'],
['duong binh trung dong','Bình Trưng Đông'], ['bui ta han','Bùi Tá Hán'],['dai lo dong tay','Đại lộ Đông Tây'],
['dang huu dong','Đặng Hữu Đông'], ['dang huu pho','Đặng Hữu Phố'],
['doan huu trung','Đoàn Hữu Trưng'],['nguyen van kinh','Nguyễn Văn Kỉnh'],
['nguyen van luong','Nguyễn Văn Luông'],['duong song hanh','Song Hành'], ['song hanh','Song Hành'],
['giang van minh','Giang Văn Minh'],['giao hoa','Giao Hoà'],['thai thuan','Thái Thuận'],
['huy hoang','Huy Hoàng'], ['le dinh quan','Lê Đình Quân'],	 ['duong the ky','Thế Kỷ'], ['the ky','Thế Kỷ'],
['thich mat the','Thích Mật Thể'], ['tong huu dinh','Tống Hữu Định'],
['lien tinh lo 25b','Liên Tỉnh Lộ 25B'],['ngo quang huy','Ngô Quang Huy'],
['truc duong','Trúc Đường'],['nguyen ba lan','Nguyễn Bá Lân'],['truong van bang','Trương Văn Bang'],
['nguyen cu di','Nguyễn Cư Dĩ'],	 ['vo truong toan','Võ Trường Toản'],
['bat nan','Bát Nàn'], ['duong binh an','Bình An'], ['duong binh trung','Bình Trưng'], ['bui ta han','Bùi Tá Hân'],
['chuong vang','Chuông Vàng'], ['dang huu pho','Đặng Hữu Phổ'], ['dang nhu mai','Đặng Như Mai'], 
['dang tien dong','Đặng Tiến Đông'],['do quang dau','Đỗ Quang Đẩu'],
['do quang','Đỗ Quang'], ['do xuan hop','Đỗ Xuân Hợp'], ['dong van cong','Đồng Văn Cống'], 
['duong van an','Dương Văn An'],['giang huong','Giang Hương'], ['hoa phuong','Hoa Phượng'],
['hoang the thien','Hoàng Thế Thiện'],['hong ky','Hồng Kỳ'], ['lam quang ky','Lâm Quang Ky'],
['le hien mai','Lê Hiến Mai'], ['le huu kieu','Lê Hữu Kiều'],['le phung hieu','Lê Phụng Hiểu'],
['le thuoc','Lê Thước'],['le van mien','Lê Văn Miến'], ['le van thinh','Lê Văn Thịnh'], ['lien phuong','Liên Phường'],
['luong dinh cua','Lương Định Của'],['mai chi tho','Mai Chí Thọ'],['muong tin','Muồng Tín'],
['nguyen ba huan','Nguyễn Bá Huân'],['nguyen co thach','Nguyễn Cơ Thạch'],['nguyen cu','Nguyễn Cừ'],
['nguyen duy hieu','Nguyễn Duy Hiệu'],['nguyen duy trinh','Nguyễn Duy Trinh'],['nguyen dang giai','Nguyễn Đăng Giai'],
['nguyen dia lo','Nguyễn Địa Lộ'], ['nguyen don tiet','Nguyễn Đôn Tiết'],['nguyen khoa dang','Nguyễn Khoa Đăng'],
['nguyen mong tuan','Nguyễn Mộng Tuân'],['nguyen quy duc','Nguyễn Quý Đức'],['nguyen thanh son','Nguyễn Thanh Sơn'],
['nguyen thi dinh','Nguyễn Thị Định'],['nguyen trong quan','Nguyễn Trọng Quản'],
['nguyen trung nguyet','Nguyễn Trung Nguyệt'],['nguyen tu nghiem','Nguyễn Tư Nghiêm'],['nguyen tuyen','Nguyễn Tuyển'],
['nguyen u di','Nguyễn Ư Dĩ'],['nguyen van giap','Nguyễn Văn Giáp'],['duong nguyen van huong','Nguyễn Văn Hưởng'],
['nguyen van huong','Nguyễn Văn Hưởng'],
['nguyen van kinh','Nguyễn Văn Kỉnh'],['pham cong tru','Phạm Công Trứ'],['pham don le','Phạm Đôn Lễ'],
['pham than duat','Phạm Thận Duật'],['phan ba vanh','Phan Bá Vành'],['quoc huong','Quốc Hương'],
['ta hien','Tạ Hiện'],['than van nhiep','Thân Văn Nhiếp'],['thanh my loi','Thạnh Mỹ Lợi'],
['duong thao dien','Thảo Điền'],['tran luu','Trần Lựu'],
['tran nao','Trần Não'],['tran ngoc dien','Trần Ngọc Diện'],['trinh khac lap','Trịnh Khắc Lập'],
['truong gia mo','Trương Gia Mô'],['truong van bang','Trương Văn Bang'],['vo chi cong','Võ Chí Công'],
['vu tong phan','Vũ Tông Phan'],['xuan thuy','Xuân Thủy'],

#quan 3
['ba huyen thanh quan','Bà Huyện Thanh Quan'], ['doan cong buu','Đoàn Công Bửu'], ['hoa hung','Hòa Hưng'],
['duong ban co','Bàn Cờ'], ['ban co','Bàn Cờ'],['cao thang','Cao Thắng'], ['cong truong quoc te','Công trường quốc tế'],
['duong ho xuan huong','Hồ Xuân Hương'],['ho xuan huong','Hồ Xuân Hương'], ['kenh nhieu loc','Kênh Nhiêu Lộc'],
['huynh tinh cua','Huỳnh Tịnh Của'],['huynh van banh','Huỳnh Văn Bánh'],['ky dong','Kỳ Đồng'],
['le ngo cat','Lê Ngô Cát'],['duong le quy don','Lê Quý Đôn'],['le quy don','Lê Quý Đôn'],
['le van sy','Lê Văn Sỹ'],['ly chinh thang','Lý Chính Thắng'],['ngo thoi nhiem','Ngô Thời Nhiệm'], 
['nguyen tri phuong','Nguyễn Tri Phương'], ['nguyen van mai','Nguyễn Văn Mai'],
['nguyen hien','Nguyễn Hiền'],['nguyen phuc nguyen','Nguyễn Phúc Nguyên'],['nguyen gia thieu','Nguyễn Gia Thiều'],
['nguyen son ha','Nguyễn Sơn Hà'],['nguyen thi dieu','Nguyễn Thị Diệu'], ['nguyen thong','Nguyễn Thông'],
['nguyen thuong hien','Nguyễn Thượng Hiền'],['nguyen van minh','Nguyễn Văn Minh'],['pham dinh toai','Phạm Đình Toái'],
['rach bung binh','Rạch Bùng Binh'],['su thien chieu','Sư Thiện Chiếu'],['tran huy lieu','Trần Huy Liệu'],
['tran minh quyen','Trần Minh Quyền'],['tran quan dieu','Trần Quang Diệu'],
['tran quoc thao','Trần Quốc Thảo'],['tran van dang','Trần Văn Đang'],['truong quyen','Trương Quyền'],
['truong sa','Trường Sa'],['tu xuong','Tú Xương'],['vuon chuoi','Vườn Chuối'],

#quan 4
['ben van don', 'Bến Vân Đồn'],
['dan sinh','Dân Sinh'],['dinh le','Đinh Lễ'],['doan nhu hai','Đoàn Như Hài'],['doan van bo','Đoàn Văn Bơ'],
['le quoc hung','Lê Quốc Hưng'],['le thach','Lê Thạch'],['le van linh','Lê Văn Linh'],['khanh hoi','Khánh Hội'],
['ngo van so','Ngô Văn Sở'],['nguyen huu hao','Nguyễn Hữu Hào'],['nguyen khoai','Nguyễn Khoái'],
['nguyen tat thanh','Nguyễn Tất Thành'],['nguyen than hien','Nguyễn Thần Hiến'],['nguyen truong to','Nguyễn Trường Tộ'],
['tan vinh','Tân Vĩnh'],['ton dan','Tôn Đản'],['ton that thuyet','Tôn Thất Thuyết'],['truong dinh hoi','Trương Đình Hội'],
['vinh hoi','Vĩnh Hội'],['vinh khanh','Vĩnh Khánh'],['xom chieu','Xóm Chiếu'],

#quan 5
['tran tuong cong','Trần Tướng Công'],	['tan hang','Tân Hàng'],['nguyen thi nho','Nguyễn Thị Nhỏ'],	
['ham tu','Hàm Tử'],['tran tuan khai','Trần Tuấn Khải'],['tang bat ho','Tăng Bạt Hổ'],	
['nguyen thi','Nguyễn Thi'],	['hai thuong lan ong','Hải Thượng Lãn Ông'],
['tan da','Tản Đà'],	['nguyen kim','Nguyễn Kim'],	
['ha ton quyen','Hà Tôn Quyền'],['tran nhan ton','Trần Nhân Tôn'],	
['ta uyen','Tạ Uyên'],	['nguyen duy duong','Nguyễn Duy Dương'],	['go cong','Gò Công'],
['su van hanh','Sư Vạn Hạnh'],['nguyen chi thanh','Nguyễn Chí Thanh'],	['gia phu','Gia Phú'],
['tran hoa','Trần Hòa'],	['phuoc hung','Phước Hưng'],	
['nguyen bieu','Nguyễn Biểu'],	['do van suu','Đỗ Văn Sửu'],
['tran dien','Trần Điện'],	['phung hung','Phùng Hưng'],	['nguyen an','Nguyễn Án'],	['do ngoc thach','Đỗ Ngọc Thạch'],
['tran chanh chieu','Trần Chánh Chiếu'],['phu dong thien vuong','Phù Đổng Thiên Vương'],	
['nguyen an khuong','Nguyễn An Khương'],['dang thai than','Đăng Thái Thân'],
['tran van kieu','Trần Văn Kiểu'],	['phu huu','Phú Hữu'],['dao tan','Đào Tấn'],
['tang bat ho','Tăng Bạt Hổ'],	['phu giao','Phú Giáo'],['ngo nhan tinh','Ngô Nhân Tịnh'],	
['duong tu giang','Dương Tử Giang'],['phu dinh','Phú Định'],['ngo gia tu','Ngô Gia Tự'],
['chieu anh cac','Chiêu Anh Các'], ['yet kieu','Yết Kiêu'],	['pho co dieu','Phó Cơ Điều'],	
['nghia thuc','Nghĩa Thục'],['chau van liem','Châu Văn Liêm'],
['xom voi','Xóm Vôi'],	['phan van tri','Phan Văn Trị'],['mac thien tich','Mạc Thiên Tích'],	
['cao dat','Cao Đạt'],['vu chi hieu','Vũ Chí Hiếu'],['phan van khoe','Phan Văn Khỏe'],	
['mac cuu','Mạc Cửu'],	['bui huu nghia','Bùi Hữu Nghĩa'],
['phan phu tien','Phan Phú Tiên'],	
['ly thuong kiet','Lý Thường Kiệt'],['bai say','Bãi Sậy'],
['van tuong','Vạn Tuợng'],	['phan huy chu','Phan Huy Chú'],	
['luu xuan tin','Lưu Xuân Tín'],['bach van','Bạch Vân'],
['van kiep','Vạn Kiếp'],['pham huu chi','Phạm Hữu Chí'],['luong nhu hoc','Lương Nhữ Học'],	
['ba trieu','Bà triệu'],['trinh hoai duc','Trịnh Hoài Đức'],
['pham don','Phạm Đôn'],['le hong phong','Lê Hồng Phong'],['an duong vuong','An Dương Vương'],
['trieu quang phuc','Triệu Quang Phục'],['pham ban','Phạm Bân'],['lao tu','Lão Tử'],
['an diem','An Điềm'],['tran xuan hoa','Trần Xuân Hòa'],['nhieu tam','Nhiêu Tâm'],	
['ky hoa','Ký Hòa'],['duong an binh','An Bình'],['trang tu','Trang Tử'],['nguyen van dung','Nguyễn Văn Đừng'],
['kim bien','Kim Biên'],
['tong duy tan','Tống Duy Tân'],['duong hung long','Hưng Long']	,
['duong tan thanh','Tân Thành'],['huynh man dat','Huỳnh Mẫn Đạt'],['hong bang','Hồng Bàng'],
['duong tan hung','Tân Hưng'],	['nguyen thoi trung','Nguyễn Thời Trung'],	['hung vuong','Hùng Vương'],	
['hoc lac','Học Lạc'],['tran binh trong','Trần Bình Trọng'],
#quan 6
['nguyen huu than','Nguyễn Hữu Thận'], ['ba hom','Bà Hom'], ['nguyen ngoc cung','Nguyễn Ngọc Cung'],
['ba ky','Bà Ký'],['nguyen pham tuan','Nguyễn Phạm Tuân'],['ba lai','Bà Lài'], ['ben lo gom','Bến Lò Gốm'],
['nguyen xuan phung','Nguyễn Xuân Phụng'], ['ben phu lam','Bến Phú Lâm'],['pham dinh ho','Phạm Đình Hổ'],
['pham phu thu','Phạm Phú Thứ'], ['binh tay','Bình Tây'],['pham van chi','Phạm Văn Chí'],
['binh tien','Bình Tiên'],['gia phu','Gia Phú'],['phan anh','Phan Anh'],['buu dinh','Bửu Đình'],
['hau giang','Hậu Giang'],['phan van khoe','Phan Văn Khỏe'],['cao van lau','Cao Văn Lầu'],
['hoang le kha','Hoàng Lê Kha'],['phung hung','Phùng Hưng'],['chanh hung','Chánh Hưng'],
['duong cho lon','Chợ Lớn'],
['cho lon','Chợ Lớn'],['tan hoa','Tân Hóa'],['chu van an','Chu Văn An'],['kinh duong vuong','Kinh Dương Vương'],	 
['tan hoa dong','Tân Hòa Đông'],['cu xa phu lam a','Cư xá Phú Lâm A'],['le quang sung','Lê Quang Sung'],
['thap muoi','Tháp Mười'],['cu xa phu lam b','Cư xá Phú Lâm B'],['le tan ke','Lê Tấn Kế'],['tien che','Tiền Chế'],
['cu xa phu lam d','Cư xá Phú Lâm D'],['le truc','Lê Trực'],
['dang nguyen can','Đặng Nguyên Cẩn'],['le tuan mau','Lê Tuấn Mậu'],['tran trung lap','Trần Trung Lập'],
['lo gom','Lò Gốm'],['tran van kieu','Trần Văn Kiểu'],['ly chieu hoang','Lý Chiêu Hoàng'],['trang tu','Trang Tử'],
['mai xuan thuong','Mai Xuân Thưởng'],['van than','Văn Thân'],
['minh phung','Minh Phụng'],['van thanh','Văn Thánh'],
['vanh dai','Vành Đai'],['nguyen dinh chi','Nguyễn Đình Chi'],

#quan 7
['bac nam','Bắc Nam'],['Bertrand Russell','Bertrand Russell'],['bo tay','Bờ Tây'],['bui van doan','Bùi Bằng Đoàn'],
['cau tan thuan 2', 'Cầu Tân Thuận 2'],['chuyen dung','Chuyên Dùng'],['dang dai do','Đặng Đại Độ'],
['dang duc thuat','Đặng Đức Thuật'],['dao su tich','Đào Sư Tích'],['dao tri noi\ dai','Đào Trí Nối dài'],['dao tri', 'Đào Trí'],
['do doc tuyet','Đô Đốc Tuyết'],['khu my kim','Khu Mỹ Kim'],['le van thiem','Lê Văn Thiêm'],
['Morison','Morison'],['my thai','Mỹ Thái'],['my vien','Mỹ Viên'],['nam quang 1','Nam Quang 1'],
['nam thong 1','Nam Thông 1'], ['nam thong 3','Nam Thông 3'], ['nguyen cao nam','Nguyễn Cao Nam'],
['nguyen dong chi','Nguyễn Đổng Chi'],['nguyen duc canh','Nguyễn Đức Cảnh'],['nguyen khac vien','Nguyễn Khắc Viện'],
['nguyen phan chanh','Nguyễn Phan Chánh'],['nguyen van tiet','Nguyễn Văn Tiết'],['o doc tuyet','Ô Đốc Tuyết'],

['be van cam','Bế Văn Cấm'],['duong ben nghe','Bến Nghé'],['binh thuan','Bình Thuận'], ['cao trieu phat','Cao Triều Phát'],
['bui van ba','Bùi Văn Ba'],['chuyen dung','Chuyên Đùng'],['dao tong nguyen','Đào Tông Nguyên'],
['dao tri','Đào Trí'],['go o moi','Gò Ô Môi'],['ha huy tap','Hà Huy Tập'],['Luther King','Luther King'],
['hoang quoc viet','Hoàng Quốc Việt'],['hung gia 2','Hưng Gia 2'],['hung gia 3','Hưng Gia 3'],
['huynh tan phat','Huỳnh Tấn Phát'],['kieu dam','Kiều Đàm'],['lam van ben','Lâm Văn Bền'],
['pham thieu','Phạm Thiều'],['phan huy thuc','Phan Huy Thực'],['phan khiem ich','Phan Khiêm Ích'],
['phan van chuong','Phan Văn Chương'],['rach doi','Rạch Dơi'],['sang tao','Sáng Tạo'],
['ta quang buu','Tạ Quang Bửu'],['tan an huy','Tân An Huy'],['tieu bac','Tiểu Bắc'],
['tieu dong','Tiểu Đông'],['tieu nam','Tiểu Nam'],
['le van luong','Lê Văn Lương'],['luu trong lu','Lưu Trọng Lư'],['ly long tuong','Lý Long Tường'],
['ly phuc man','Lý Phục Man'],['mai van vinh','Mai Văn Vĩnh'],['ngo thi nham','Ngô Thì Nhậm'],
['nguyen binh','Nguyễn Bính'],['nguyen cao','Nguyễn Cao'],['nguyen huu tho','Nguyễn Hữu Thọ'],
['nguyen luong bang','Nguyễn Lương Bằng'],['nguyen thi thap','Nguyễn Thị Thập'],['nguyen van linh','Nguyễn Văn Linh'],
['nguyen van quy','Nguyễn Văn Quỳ'],['nguyen van tuong','Nguyễn Văn Tưởng'],['duong pham huu lau','Phạm Hữu Lầu'],
['pham huu lau','Phạm Hữu Lầu'],['duong pham thai buong','Phạm Thái Bường'],['pham thai buong','Phạm Thái Bường'],
['pham van nghi','Phạm Văn Nghị'],['phu thuan','Phú Thuận'],
['tan my','Tân Mỹ'],['duong tan phu','Tân Phú'],['tan quy dong','Tân Quy Đông'],['tan quy','Tân Quy'],
['tan thuan tay','Tân Thuận Tây'],['tan thuan','Tân Thuận'], ['ton dat tien','Tôn Dật Tiên'],
['tran trong cung','Trần Trọng Cung'],['tran van khanh','Trần Văn Khánh'],['tran van tra','Trần Văn Trà'],
['tran xuan soan','Trần Xuân Soạn'],['ung long nam','Ưng Long Nam'],['xa la bac nam','Xa lộ Bắc Nam'],
#quan tan binh
['truong cong dinh','Trương Công Định'],['duong truong son','Trường Sơn'],['truong son','Trường Sơn'],['ngo thi thu minh','Ngô Thị Thu Minh'],
['hoang viet','Hoàng Việt'],['duong nguyen minh hoang','Nguyễn Minh Hoàng'],['nguyen minh hoang','Nguyễn Minh Hoàng'],['duong nui thanh','Núi Thành'],
['nui thanh', 'Núi Thành'],['duong thep moi','Thép Mới'],['thep moi','Thép Mới'],
#tan phu
['to hieu','Tô Hiệu'],
#quan go gap
['an hoi','An Hội'],['huynh van nghe','Huỳnh Văn Nghệ'],['nguyen van nghi','Nguyễn Văn Nghi'],
['an nhon','An Nhơn'],['le duc tho','Lê Đức Thọ'],['pham huy thong','Phạm Huy Thông'],
['bui quang la','Bùi Quang Là'],['le hoang phai','Lê Hoàng Phái'],['cay tram','Cây Trâm'],
['pham van bach','Phạm Văn Bạch'],['do phuc tinh','Đỗ Thúc Tịnh'],['pham van chieu','Phạm Văn Chiêu'],
['le quang dinh','Lê Quang Định'],['duong quang ham','Dương Quảng Hàm'],['le thi hong','Lê Thị Hồng'],	 
['phan duy ich','Phan Huy Ích'],['le van tho','Lê Văn Thọ'],['le van tri','Lê Văn Trị'],
['phung van cung','Phùng Văn Cung'],['duong quang trung','Quang Trung'],['quang trung','Quang Trung'],
['duong tan son','Tân Sơn'],['tan tho','Tân Thọ'],['thich buu dang','Thích Bửu Đăng'],
['thien ho duong','Thiên Hộ Dương'], ['nguyen hong','Nguyên Hồng'],	['thong tay hoi','Thông Tây Hội'],
['nguyen huy dien','Nguyễn Huy Điển'],['tran ba giao','Trần Bá Giao'],
['nguyen oanh','Nguyễn Oanh'],['tran phu cuong','Trần Phú Cương'],['tran quoc tuan','Trần Quốc Tuấn'],
['tran thi nghi','Trần Thị Nghĩ'],['nguyen tu gian','Nguyễn Tư Giản'],['trung nu vuong','Trưng Nữ Vương'],
['hanh thong tay','Hạnh Thông Tây'],['hanh thong','Hạnh Thông'],['nguyen tuan','Nguyễn Tuân'],
['nguyen van bao','Nguyễn Văn Bảo'],['truong minh giang','Trương Minh Giảng'],
['hoang hoa tham','Hoàng Hoa Thám'],['nguyen van cong','Nguyễn Văn Công'],['truong minh ky','Trương Minh Ký'],
['hoang minh giam','Hoàng Minh Giám'],['nguyen van dung','Nguyễn Văn Dung'],['tu mo','Tú Mỡ'],
['huynh khuong an','Huỳnh Khương An'],


 
#quan 8
['ba to','Ba Tơ'],['nguyen si co','Nguyễn Sĩ Cố'],['an tai','An Tài'],['nguyen thanh phuong','Nguyễn Thành Phương'],
['au duong lan','Âu Dương Lân'],['nguyen thi tan','Nguyễn Thị Tần'],['ba dinh','Ba Đình'],
['ben binh dong','Bến Bình Đông'],['ben can giuoc','Bến Cần Giuộc'],['nguyen van cua','Nguyễn Văn Của'],
['ben me coc','Bến Mễ Cốc'],['ben phu dinh','Bến Phú Định'],['ho hoc lam','Hồ Học Lãm'],
['ben u cay','Bến Ụ Cây'],['hoai thanh','Hoài Thanh'],['pham hung','Phạm Hùng'],
['ben xom cui','Bến Xóm Củi'],['hoang dao thuy','Hoàng Đạo Thúy'],['pham the hien','Phạm Thế Hiển'],
['binh dang','Bình Đăng'],['hoang minh dao','Hoàng Minh Đạo'],['phong phu','Phong Phú'],
['binh dong','Bình Đông'],['hoang si khai','Hoàng Sĩ Khải'],['phu dinh','Phú Định'],
['binh duc','Bình Đức'],['duong ba trac','Dương Bá Trạc'],['duong hung phu','Hưng Phú'],
['phu loi','Phú Lợi'],['binh hung','Bình Hưng'],['huynh thi phung','Huỳnh Thị Phụng'],	 
['quoc lo 50','Quốc Lộ 50'],['bong sao','Bông Sao'],['le quang kim','Lê Quang Kim'],	 
['rach cat','Rạch Cát'],['bui huy bich','Bùi Huy Bích'],['le thanh phuong','Lê Thành Phương'],
['rach cung','Rạch Cùng'],['bui minh truc','Bùi Minh Trực'],['rach long den','Rạch Lồng Đèn'],
['can giuoc','Cần Giuộc'],['luong ngoc quyen','Lương Ngọc Quyến'],['cao lo','Cao Lỗ'],
['luong van can','Lương Văn Can'],['tran nguyen han','Trần Nguyên Hãn'],
['cao xuan duc','Cao Xuân Dục'],['luu huu phuoc','Lưu Hữu Phước'],['tran van thanh','Trần Văn Thành'],
['cay sung','Cây Sung'],['luu quy ky','Lưu Quý Kỳ'],['trinh quang nghi','Trịnh Quang Nghị'],
['chanh hung','Chánh Hưng'],['ly chieu hoang','Lý Chiêu Hoàng'],['truong dinh hoi','Trương Đình Hội'],
['da nam','Dạ Nam'],['ly dao thanh','Lý Đạo Thành'],['tung thien vuong','Tùng Thiện Vương'],
['da tuong','Dã Tượng'],['mac van','Mạc Vân'],['tuy ly vuong','Tuy Lý Vương'],
['dang chat','Đặng Chất'],['mai am','Mai Am'],['uu long','Ưu Long'],
['dao cam moc','Đào Cam Mộc'],['mai hac de','Mai Hắc Đế'],
['dinh an tai','Đình An Tài'],['me coc','Mễ Cốc'],['van than','Văn Thân'],
['dinh hoa','Đinh Hòa'],['ngo sy lien','Ngô Sỹ Liên'],['vinh nam','Vĩnh Nam'],
['dong dieu','Đồng Diều'],['nguyen che nghia','Nguyễn Chế Nghĩa'],['vo tru','Võ Trứ'],
['dong ho','Đông Hồ'],['nguyen duy','Nguyễn Duy'],['vo van kiet','Võ Văn Kiệt'],
['nguyen nhuoc thi','Nguyễn Nhược Thị'],['nguyen quyen','Nguyễn Quyền'],['duong nguyen du','Nguyễn Du'],
['nguyen du','Nguyễn Du'],	

# thu duc
['ba giang', "Bà Giang"],["duong pham van dong","Phạm Văn Đồng"],["pham van dong","Phạm Văn Đồng"],
["nguyen khuyen","Nguyễn Khuyến"], ["bac ai","Bác Ái"], ["nguyen van ba","Nguyễn Văn Bá"], 
["binh chieu","Bình Chiểu"],["nguyen van lich","Nguyễn Văn Lịch"], ["boi hoan","Bồi Hoàn"],
["duong van cam","Dương Văn Cam"],	["phu chau","Phú Châu"],["cay keo","Cây Keo"],["einstein","Einstein"],	 
["phuong vi","Phượng Vĩ"],["chan ly","Chân Lý"],["go dua","Gò Dưa"],
["chu manh trinh","Chu Mạnh Trinh"],["han thuyen","Hàn Thuyên"],["quoc lo 1a","Quốc Lộ 1A"], 
["chuong duong","Chương Dương"],["hiep binh", "Hiệp Bình"],["quoc lo 1k","Quốc Lộ 1K"],["cong ly","Công Lý"],	 
["ho van tu","Hồ Văn Tư"],	 ["quy duc","Quy Đức"],["dan chu","Dân Chủ"],["hoa binh","Hòa Bình"],
["rach lung","Rạch Lùng"],["dang thi ranh","Đặng Thị Rành"],["hoang dieu 2","Hoàng Diệu 2"],	 
["tam binh","Tam Bình"],["dang van bi","Đặng Văn Bi"],["hoang dieu","Hoàng Diệu"], 	 
["tam chau","Tam Châu"], ["dao trinh nhat","Đào Trinh Nhất"],["hong duc","Hồng Đức"], 
["tam ha","Tam Hà"], ["doan cong hon","Đoàn Công Hớn"],["huu nghi","Hữu Nghị"],
["tam tam xa","Tâm Tâm Xã"],["doan ket","Đoàn Kết"],["kha van can","Kha Vạn Cân"],["thong nhat","Thống Nhất"],
["khong tu","Khổng Tử"],["tinh lo 42","Tỉnh lộ 42"],["lang dai hoc","Khu làng Đại Học"],	 
["tinh lo 43","Tỉnh lộ 43"],["lam son","Lam Sơn"],["tinh lo 44","Tỉnh Lộ 44"],['binh phu',"Bình Phú"],
['le quy don','Lê Quý Đôn'],['to ngoc van','Tô Ngọc Vân'],['le thi hoa','Lê Thị Hoa'],	 
['to vinh dien','Tô Vĩnh Diện'],['le van chi','Lê Văn Chí'],['tran van nua','Trần Văn Nữa'], 
['duong so 147','Đường số 147'],['le van ninh','Lê Văn Ninh'], 
['trinh van phong dan','Trịnh Phong Đán'],  ['le van tach','Lê Văn Tách'],	 
['truong tho','Trường Thọ'], ['duong linh dong','Linh Đông'],	 
['truong tre','Truông Tre'], ['duong linh trung','Linh Trung'],	 
['truong van ngu','Trương Văn Ngư'],['duong linh xuan','Linh Xuân'],['u ghe','Ụ Ghe'],
['luong khai sieu','Lương Khải Siêu'],['vo tien su','Võ Tiên Sư'], ['ly te xuyen','Lý Tế Xuyên'],
['vo van ngan','Võ Văn Ngân'],['ngo chi quoc','Ngô Chí Quốc'],['xa lo ha noi','Xa Lộ Hà Nội'],
['xuan hiep','Xuân Hiệp'],['nguyen ba luat','Nguyễn Bá Luật'],
#binh tan
['ao doi','Ao Đôi'],['ao sen','Ao Sen'],['ap chien luoc','Ấp Chiến Lược'],['ba hom','Bà Hom'],['ben loi','Bến Lội'],
['lo te','Lộ Tẻ'],['lo tu','Lô Tư'],['duong binh thanh','Bình Thành'],['binh hanh','Bình Hành'],['binh long','Bình Long'],
['duong ly thanh tong','Lý Thánh Tông'],['ly thanh tong','Lý Thánh Tông'],['ma lo','Mã Lò'],
['binh tri dong','Bình Trị Đông'],['mieu binh dong','Miếu Bình Đông'],['bo song','Bờ sông'],
['mieu go xoai','Miếu Gò Xoài'],['nghi xuan','Nghi Xuân'],['ngo y linh','Ngô Y Linh'],
['bui duong lich','Bùi Dương Lịch'],['nguyen cuu phu','Nguyễn Cửu Phú'],['bui huu dien','Bùi Hữu Diên'],
['nguyen dinh kien','Nguyễn Đình Kiên'],['bui tu toan','Bùi Tư Toàn'],['nguyen hoi','Nguyễn Hới'],
['cao toc trung luong','Cao Tốc Trung Lương'],['nguyen huu canh','Nguyễn Hữu Cảnh'],
['nguyen quy yem','Nguyễn Quý Yêm'],['nguyen son','Nguyễn Sơn'],['nguyen thi tu','Nguyễn Thị Tú'],
['nguyen thuc duong','Nguyễn Thức Đường'],['dai lo dong tay','Đại lộ Đông Tây'],
['nguyen thuc tu','Nguyễn Thức Tự'],['nguyen trieu luat','Nguyễn Triệu Luật'],
['dinh nghi xuan','Đình Nghi Xuân'],['nguyen trong chi','Nguyễn Trọng Chí'],
['dinh tan khai','Đình Tân Khai'],['nguyen trong tri','Nguyễn Trọng Trí'],['do bi','Đỗ Bí'],
['do nang te','Đỗ Năng Tế'],['pham banh','Phạm Bành'],['doan phu tu','Đoàn Phú Tứ'],
['pham dang giang','Phạm Đăng Giảng'],['duong 26 thang 3','Đường 26 Tháng 3'],['duong 26/3','Đường 26 Tháng 3'],
['phan cat tuu','Phan Cát Tựu'],['phan dinh thong','Phan Đình Thông'],['phan van nam','Phan Văn Năm'],
['duong ba cung','Dương Bá Cung'],['duong tu quan','Dương Tự Quán'],['phung ta chu','Phùng Tá Chu'],
['ho hoc lam','Hồ Học Lãm'],['ho van long','Hồ Văn Long'],['hoang hung','Hoàng Hưng'],
['ta my duat','Tạ Mỹ Duật'],['hoang van hop','Hoàng Văn Hợp'],['tan hoa dong','Tân Hòa Đông'],
['tan khai','Tân Khai'],['duong tan son nhi','Tân Sơn Nhì'],['tran dai nghia','Trần Đại Nghĩa'],
['xa lo dai han','Xa Lộ Đại Hàn'],['duong B','Đường B'], ['duong c','Đường C'], ['duong 66','Đường số 66'], ['duong 65','Đường số 65'], ['duong 64','Đường số 64'],
['duong 63','Đường số 63'], ['duong 62','Đường số 62'], ['duong 61','Đường số 61'],
['duong 60','Đường số 60'],['duong 59','Đường số 59'],['duong 58','Đường số 58'],
['duong 57','Đường số 57'],['duong 56','Đường số 56'],['duong 55','Đường số 55'],
['duong 54','Đường số 54'],['duong 53','Đường số 53'],['duong 52','Đường số 52'],
['duong 51','Đường số 51'],['duong 50','Đường số 50'],['duong 49','Đường số 49'],
['duong 48','Đường số 48'],['duong 47','Đường số 47'],['duong 46','Đường số 46'],
['duong 45','Đường số 45'],['duong 44','Đường số 44'],['duong 43','Đường số 43'],
['duong 42','Đường số 42'],['duong 41','Đường số 41'],['duong 40','Đường số 40'],
['duong 39','Đường số 39'],['duong 38','Đường số 38'],['duong 37','Đường số 37'],
['duong 36','Đường số 36'],['duong 35','Đường số 35'],['duong 34','Đường số 34'],
['duong 33','Đường số 33'],['duong 32','Đường số 32'],['duong 31','Đường số 31'],
['duong 30','Đường số 30'],['duong 29','Đường số 29'],['duong 28','Đường số 28'],
['duong 27','Đường số 27'],['duong 26','Đường số 26'],['duong 25','Đường số 25'],
['duong 24','Đường số 24'],['duong 23','Đường số 23'],['duong 22','Đường số 22'],
['duong 21','Đường số 21'],['duong 20','Đường số 20'],['duong 19','Đường số 19'],
['duong 18','Đường số 18'],['duong 17','Đường số 17'],['duong 16','Đường số 16'],
['duong 15','Đường số 15'],['duong 14','Đường số 14'],['duong 13','Đường số 13'],
['duong 12','Đường số 12'],['duong 11','Đường số 11'],['duong 10','Đường số 10'],
['duong 9','Đường số 9'],['duong 8','Đường số 8'],['duong 7','Đường số 7'],
['duong 6','Đường số 6'],['duong 5','Đường số 5'],['duong 4','Đường số 4'],
['duong 3','Đường số 3'],['duong 2','Đường số 2'],['duong 1','Đường số 1']] 


def detect_district_index(address):
    """
    Detect district position in address
    :param address: raw text address
    :return: index
    """
    for j in range(0, len(districtListHCM)):
        index = re.search(districtListHCM[j][0], address, re.IGNORECASE)
        if index:
            return index.span()[0]
    return -1


def detect_district(address):
    """
    Detect district in address
    :param address: raw text address
    :return: district detected in address
    """
    for j in range(0, len(districtListHCM)):
        index = re.search(districtListHCM[j][0], address, re.IGNORECASE)
        if index:
                return districtListHCM[j][1]
    return ""

def detect_ward_index(address):
    """
    Detect ward position in address
    :param address: raw text address
    :return: index
    """
    for k in range(0, len(wardListHCM)):
        index = re.search(wardListHCM[k][0], address, re.IGNORECASE)
        if index:
            return index.span()[0]
    return -1

def detect_ward(address):
    """
    Detect ward in address
    :param address: raw text address
    :return: ward detected in address
    """
    for k in range(0, len(wardListHCM)):
        index = re.search(wardListHCM[k][0], address, re.IGNORECASE)
        if index:
            return wardListHCM[k][1]
    return ""


def detect_street_index(address):
    """
    Detect street position in address
    :param address: raw text address
    :return: index
    """
    for k in range(0, len(streetListHCM)):
        index = re.search(streetListHCM[k][0], address, re.IGNORECASE)
        if index:
                return index.span()[0]
    return -1

def detect_street(address):
    """
    Detect street in address
    :param address: raw text address
    :return: street detected in address
    """
    for k in range(0, len(streetListHCM)):
        index = re.search(streetListHCM[k][0], address, re.IGNORECASE)
        if index:
            return streetListHCM[k][1]
    return ""

def detect_num(address, streetIndex):
    """
    Detect numberHourse in address
    :param address: raw text address, index street of address numberhourse
    :return: numberHourse detected in address
    """
    #print(streetIndex)
    if(streetIndex != -1):
        if(streetIndex == 0): return address[0:streetIndex]
        return address[0:streetIndex-1].rstrip('-')
    return ""