import string
import re
import unicodedata
import sys

patterns = {
    '[àáảãạăắằẵặẳâầấậẫẩ]': 'a',
    '[đ]': 'd',
    '[èéẻẽẹêềếểễệ]': 'e',
    '[ìíỉĩị]': 'i',
    '[òóỏõọôồốổỗộơờớởỡợ]': 'o',
    '[ùúủũụưừứửữự]': 'u',
    '[ỳýỷỹỵ]': 'y'
}


def remove_accent(text):
    """
    Convert from 'Tiếng Việt' into 'Tieng Viet'
    :param text: input string to be converted
    :return Return: string converted
    """
    output = text
    for regex, replace in patterns.items():
        output = re.sub(regex, replace, output)
        # deal with upper case
        output = re.sub(regex.upper(), replace.upper(), output)
    return output

districtListHCM = [["q10", "Quận 10"],
                   ["q 10", "Quận 10"],
                   ["q\.10", "Quận 10"],
                   ["q\. 10", "Quận 10"],
                   ["quan 10", "Quận 10"],
                   ["quan\.10", "Quận 10"],
                   ["quan\. 10", "Quận 10"],
                   ["q11", "Quận 11"],
                   ["q 11", "Quận 11"],
                   ["q\.11", "Quận 11"],
                   ["q\. 11", "Quận 11"],
                   ["quan 11", "Quận 11"],
                   ["quan\.11", "Quận 11"],
                   ["quan\. 11", "Quận 11"],
                   ["q12", "Quận 12"],
                   ["q 12", "Quận 12"],
                   ["q\.12", "Quận 12"],
                   ["q\. 12", "Quận 12"],
                   ["quan 12", "Quận 12"],
                   ["quan\.12", "Quận 12"],
                   ["quan\. 12", "Quận 12"],
                   ["q1", "Quận 1"],
                   ["q 1", "Quận 1"],
                   ["q\.1", "Quận 1"],
                   ["q\. 1", "Quận 1"],
                   ["quan 1", "Quận 1"],
                   ["quan\.1", "Quận 1"],
                   ["quan\. 1", "Quận 1"],
                   ["q2", "Quận 2"],
                   ["q 2", "Quận 2"],
                   ["q\.2", "Quận 2"],
                   ["q\. 2", "Quận 2"],
                   ["quan 2", "Quận 2"],
                   ["quan\.2", "Quận 2"],
                   ["quan\. 2", "Quận 2"],
                   ["q3", "Quận 3"],
                   ["q 3", "Quận 3"],
                   ["q\.3", "Quận 3"],
                   ["q\. 3", "Quận 3"],
                   ["quan 3", "Quận 3"],
                   ["quan\.3", "Quận 3"],
                   ["quan\. 3", "Quận 3"],
                   ["q4", "Quận 4"],
                   ["q 4", "Quận 4"],
                   ["q\.4", "Quận 4"],
                   ["q\. 4", "Quận 4"],
                   ["quan 4", "Quận 4"],
                   ["quan\.4", "Quận 4"],
                   ["quan\. 4", "Quận 4"],
                   ["q5", "Quận 5"],
                   ["q 5", "Quận 5"],
                   ["q\.5", "Quận 5"],
                   ["q\. 5", "Quận 5"],
                   ["quan 5", "Quận 5"],
                   ["quan\.5", "Quận 5"],
                   ["quan\. 5", "Quận 5"],
                   ["q6", "Quận 6"],
                   ["q 6", "Quận 6"],
                   ["q\.6", "Quận 6"],
                   ["q\. 6", "Quận 6"],
                   ["quan 6", "Quận 6"],
                   ["quan\.6", "Quận 6"],
                   ["quan\. 6", "Quận 6"],
                   ["q7", "Quận 7"],
                   ["q 7", "Quận 7"],
                   ["q\.7", "Quận 7"],
                   ["q\. 7", "Quận 7"],
                   ["quan 7", "Quận 7"],
                   ["quan\.7", "Quận 7"],
                   ["quan\. 7", "Quận 7"],
                   ["q8", "Quận 8"],
                   ["q 8", "Quận 8"],
                   ["q\.8", "Quận 8"],
                   ["q\. 8", "Quận 8"],
                   ["quan 8", "Quận 8"],
                   ["quan\.8", "Quận 8"],
                   ["quan\. 8", "Quận 8"],
                   ["q9", "Quận 9"],
                   ["q 9", "Quận 9"],
                   ["q\.9", "Quận 9"],
                   ["q\. 9", "Quận 9"],
                   ["quan 9", "Quận 9"],
                   ["quan\.9", "Quận 9"],
                   ["quan\. 9", "Quận 9"],
                   ["GV", "Quận Gò Vấp"],
                   ["Go Vap", "Quận Gò Vấp"],
                   ["qGo Vap", "Quận Gò Vấp"],
                   ["qGV", "Quận Gò Vấp"],
                   ["q Go Vap", "Quận Gò Vấp"],
                   ["q GV", "Quận Gò Vấp"],
                   ["q\.Go Vap", "Quận Gò Vấp"],
                   ["q\.Gv", "Quận Gò Vấp"],
                   ["q\. Go Vap", "Quận Gò Vấp"],
                   ["q\. GV", "Quận Gò Vấp"],
                   ["quan Go Vap", "Quận Gò Vấp"],
                   ["quan Gv", "Quận Gò Vấp"],
                   ["quan\.Go Vap", "Quận Gò Vấp"],
                   ["quan\.Gv", "Quận Gò Vấp"],
                   ["quan\. Go Vap", "Quận Gò Vấp"],
                   ["quan\. Gv", "Quận Gò Vấp"],
                   ["BT", "Quận Bình Thạnh"],
                   ["Binh Thanh", "Quận Bình Thạnh"],
                   ["qBinh Thanh", "Quận Bình Thạnh"],
                   ["qBT", "Quận Bình Thạnh"],
                   ["q Binh Thanh", "Quận Bình Thạnh"],
                   ["q BT", "Quận Bình Thạnh"],
                   ["q\.Binh Thanh", "Quận Bình Thạnh"],
                   ["q\.BT", "Quận Bình Thạnh"],
                   ["q\. Binh Thanh", "Quận Bình Thạnh"],
                   ["q\. BT", "Quận Bình Thạnh"],
                   ["quan Binh Thanh", "Quận Bình Thạnh"],
                   ["quan BT", "Quận Bình Thạnh"],
                   ["quan\.Binh Thanh", "Quận Bình Thạnh"],
                   ["quan\.BT", "Quận Bình Thạnh"],
                   ["quan\. Binh Thanh", "Quận Bình Thạnh"],
                   ["quan\. BT", "Quận Bình Thạnh"],
                   ["Binh Tan", "Quận Bình Tân"],
                   ["BT", "Quận Bình Tân"],
                   ["qBinh Tan", "Quận Bình Tân"],
                   ["qBT", "Quận Bình Tân"],
                   ["q Binh Tan", "Quận Bình Tân"],
                   ["q BT", "Quận Bình Tân"],
                   ["q\.Binh Tan", "Quận Bình Tân"],
                   ["q\.BT", "Quận Bình Tân"],
                   ["q\. Binh Tan", "Quận Bình Tân"],
                   ["q\. BT", "Quận Bình Tân"],
                   ["quan Binh Tan", "Quận Bình Tân"],
                   ["quan BT", "Quận Bình Tân"],
                   ["quan\.Binh Tan", "Quận Bình Tân"],
                   ["quan\.BT", "Quận Bình Tân"],
                   ["quan\. Binh Tan", "Quận Bình Tân"],
                   ["quan\. BT", "Quận Bình Tân"],
                   ["Tan Binh", "Quận Tân Bình"],
                   ["qTan Binh", "Quận Tân Bình"],
                   ["q Tan Binh", "Quận Tân Bình"],
                   ["q\.Tan Binh", "Quận Tân Bình"],
                   ["q\. Tan Binh", "Quận Tân Bình"],
                   ["quan Tan Binh", "Quận Tân Bình"],
                   ["quan\.Tan Binh", "Quận Tân Bình"],
                   ["quan\. Tan Binh", "Quận Tân Bình"],
                   ["PN", "Quận Phú Nhuận"],
                   ["qPN", "Quận Phú Nhuận"],
                   ["q PN", "Quận Phú Nhuận"],
                   ["q\.PN", "Quận Phú Nhuận"],
                   ["q\. PN", "Quận Phú Nhuận"],
                   ["quan PN", "Quận Phú Nhuận"],
                   ["quan\.PN", "Quận Phú Nhuận"],
                   ["quan\. PN", "Quận Phú Nhuận"],
                   ["Phu Nhuan", "Quận Phú Nhuận"],
                   ["qPhu Nhuan", "Quận Phú Nhuận"],
                   ["q Phu Nhuan", "Quận Phú Nhuận"],
                   ["q\.Phu Nhuan", "Quận Phú Nhuận"],
                   ["q\. Phu Nhuan", "Quận Phú Nhuận"],
                   ["quan Phu Nhuan", "Quận Phú Nhuận"],
                   ["quan\.Phu Nhuan", "Quận Phú Nhuận"],
                   ["quan\. Phu Nhuan", "Quận Phú Nhuận"],
                   ["PN", "Quận Phú Nhuận"],
                   ["qPN", "Quận Phú Nhuận"],
                   ["q PN", "Quận Phú Nhuận"],
                   ["q\.PN", "Quận Phú Nhuận"],
                   ["q\. PN", "Quận Phú Nhuận"],
                   ["quan PN", "Quận Phú Nhuận"],
                   ["quan\.PN", "Quận Phú Nhuận"],
                   ["quan\. PN", "Quận Phú Nhuận"],
                   ["Nha Be", "Huyện Nhà Bè"],
                   ["qNha Be", "Huyện Nhà Bè"],
                   ["q Nha Be", "Huyện Nhà Bè"],
                   ["q\.Nha Be", "Huyện Nhà Bè"],
                   ["q\. Nha Be", "Huyện Nhà Bè"],
                   ["quan Nha Be", "Huyện Nhà Bè"],
                   ["quan\.Nha Be", "Huyện Nhà Bè"],
                   ["quan\. Nha Be", "Huyện Nhà Bè"],
                   ["Nha Be", "Huyện Nhà Bè"],
                   ["hNha Be", "Huyện Nhà Bè"],
                   ["h Nha Be", "Huyện Nhà Bè"],
                   ["h\.Nha Be", "Huyện Nhà Bè"],
                   ["h\. Nha Be", "Huyện Nhà Bè"],
                   ["quan Nha Be", "Huyện Nhà Bè"],
                   ["huyen\.Nha Be", "Huyện Nhà Bè"],
                   ["huyen\. Nha Be", "Huyện Nhà Bè"],
                   ["NB", "Huyện Nhà Bè"],
                   ["qNB", "Huyện Nhà Bè"],
                   ["q NB", "Huyện Nhà Bè"],
                   ["q\.NB", "Huyện Nhà Bè"],
                   ["q\. NB", "Huyện Nhà Bè"],
                   ["quan NB", "Huyện Nhà Bè"],
                   ["quan\.NB", "Huyện Nhà Bè"],
                   ["quan\. NB", "Huyện Nhà Bè"],
                   ["NB", "Huyện Nhà Bè"],
                   ["hNB", "Huyện Nhà Bè"],
                   ["h NB", "Huyện Nhà Bè"],
                   ["h\.NB", "Huyện Nhà Bè"],
                   ["h\. NB", "Huyện Nhà Bè"],
                   ["huyen NB", "Huyện Nhà Bè"],
                   ["huyen\.NB", "Huyện Nhà Bè"],
                   ["huyen\. NB", "Huyện Nhà Bè"],
                   ["Thu Duc", "Quận Thủ Đức"],
                   ["qThu Duc", "Quận Thủ Đức"],
                   ["q Thu Duc", "Quận Thủ Đức"],
                   ["q\.Thu Duc", "Quận Thủ Đức"],
                   ["q\. Thu Duc", "Quận Thủ Đức"],
                   ["quan Thu Duc", "Quận Thủ Đức"],
                   ["quan\.Thu Duc", "Quận Thủ Đức"],
                   ["quan\. Thu Duc", "Quận Thủ Đức"],
                   ["TD", "Quận Thủ Đức"],
                   ["qTD", "Quận Thủ Đức"],
                   ["q TD", "Quận Thủ Đức"],
                   ["q\.TD", "Quận Thủ Đức"],
                   ["q\. TD", "Quận Thủ Đức"],
                   ["quan TD", "Quận Thủ Đức"],
                   ["quan\.TD", "Quận Thủ Đức"],
                   ["quan\. TD", "Quận Thủ Đức"],
                   ["Binh Chanh", "Huyện Bình Chánh"],
                   ["qBinh Chanh", "Huyện Bình Chánh"],
                   ["q Binh Chanh", "Huyện Bình Chánh"],
                   ["q\.Binh Chanh", "Huyện Bình Chánh"],
                   ["q\. Binh Chanh", "Huyện Bình Chánh"],
                   ["quan Binh Chanh", "Huyện Bình Chánh"],
                   ["quan\.Binh Chanh", "Huyện Bình Chánh"],
                   ["quan\. Binh Chanh", "Huyện Bình Chánh"],
                   ["Binh Chanh", "Huyện Bình Chánh"],
                   ["hBinh Chanh", "Huyện Bình Chánh"],
                   ["h Binh Chanh", "Huyện Bình Chánh"],
                   ["h\.Binh Chanh", "Huyện Bình Chánh"],
                   ["h\. Binh Chanh", "Huyện Bình Chánh"],
                   ["huyen Binh Chanh", "Huyện Bình Chánh"],
                   ["huyen\.Binh Chanh", "Huyện Bình Chánh"],
                   ["huyen\. Binh Chanh", "Huyện Bình Chánh"],
                   ["BC", "Huyện Bình Chánh"],
                   ["qBC", "Huyện Bình Chánh"],
                   ["q BC", "Huyện Bình Chánh"],
                   ["q\.BC", "Huyện Bình Chánh"],
                   ["q\. BC", "Huyện Bình Chánh"],
                   ["quan BC", "Huyện Bình Chánh"],
                   ["quan\.BC", "Huyện Bình Chánh"],
                   ["quan\. BC", "Huyện Bình Chánh"],
                   ["BC", "Huyện Bình Chánh"],
                   ["hBC", "Huyện Bình Chánh"],
                   ["h BC", "Huyện Bình Chánh"],
                   ["h\.BC", "Huyện Bình Chánh"],
                   ["h\. BC", "Huyện Bình Chánh"],
                   ["huyen BC", "Huyện Bình Chánh"],
                   ["huyen\.BC", "Huyện Bình Chánh"],
                   ["huyen\. BC", "Huyện Bình Chánh"],
                   ["Binh Chanh", "Huyện Bình Chánh"],
                   ["qBinh Chanh", "Huyện Bình Chánh"],
                   ["q Binh Chanh", "Huyện Bình Chánh"],
                   ["q\.Binh Chanh", "Huyện Bình Chánh"],
                   ["q\. Binh Chanh", "Huyện Bình Chánh"],
                   ["quan Binh Chanh", "Huyện Bình Chánh"],
                   ["quan\.Binh Chanh", "Huyện Bình Chánh"],
                   ["quan\. Binh Chanh", "Huyện Bình Chánh"],
                   ["Cu Chi", "Huyện Củ Chi"],
                   ["hCu Chi", "Huyện Củ Chi"],
                   ["h Cu Chi", "Huyện Củ Chi"],
                   ["h\.Cu Chi", "Huyện Củ Chi"],
                   ["h\. Cu Chi", "Huyện Củ Chi"],
                   ["huyen Cu Chi", "Huyện Củ Chi"],
                   ["huyen\.Cu Chi", "Huyện Củ Chi"],
                   ["huyen\. Cu Chi", "Huyện Củ Chi"],
                   ["CC", "Huyện Củ Chi"],
                   ["qCC", "Huyện Củ Chi"],
                   ["q CC", "Huyện Củ Chi"],
                   ["q\.CC", "Huyện Củ Chi"],
                   ["q\. CC", "Huyện Củ Chi"],
                   ["quan CC", "Huyện Củ Chi"],
                   ["quan\.CC", "Huyện Củ Chi"],
                   ["quan\. CC", "Huyện Củ Chi"],
                   ["CC", "Huyện Củ Chi"],
                   ["hCC", "Huyện Củ Chi"],
                   ["h CC", "Huyện Củ Chi"],
                   ["h\.CC", "Huyện Củ Chi"],
                   ["h\. CC", "Huyện Củ Chi"],
                   ["huyen CC", "Huyện Củ Chi"],
                   ["huyen\.CC", "Huyện Củ Chi"],
                   ["huyen\. CC", "Huyện Củ Chi"],
                   ["Hoc Mon", "Huyện Hóc Môn"],
                   ["hHoc Mon", "Huyện Hóc Môn"],
                   ["h Hoc Mon", "Huyện Hóc Môn"],
                   ["h\.Hoc Mon", "Huyện Hóc Môn"],
                   ["h\. Hoc Mon", "Huyện Hóc Môn"],
                   ["huyen Hoc Mon", "Huyện Hóc Môn"],
                   ["huyen\.Hoc Mon", "Huyện Hóc Môn"],
                   ["huyen\. Hoc Mon", "Huyện Hóc Môn"],
                   ["HM", "Huyện Hóc Môn"],
                   ["qHM", "Huyện Hóc Môn"],
                   ["q HM", "Huyện Hóc Môn"],
                   ["q\.HM", "Huyện Hóc Môn"],
                   ["q\. HM", "Huyện Hóc Môn"],
                   ["quan HM", "Huyện Hóc Môn"],
                   ["quan\.HM", "Huyện Hóc Môn"],
                   ["quan\. HM", "Huyện Hóc Môn"],
                   ["HM", "Huyện Hóc Môn"],
                   ["hHM", "Huyện Hóc Môn"],
                   ["h HM", "Huyện Hóc Môn"],
                   ["h\.HM", "Huyện Hóc Môn"],
                   ["h\. HM", "Huyện Hóc Môn"],
                   ["huyen HM", "Huyện Hóc Môn"],
                   ["huyen\.HM", "Huyện Hóc Môn"],
                   ["huyen\. HM", "Huyện Hóc Môn"],
                   ["Tan Phu", "Quận Tân Phú"],
                   ["qTan Phu", "Quận Tân Phú"],
                   ["q Tan Phu", "Quận Tân Phú"],
                   ["q\.Tan Phu", "Quận Tân Phú"],
                   ["q\. Tan Phu", "Quận Tân Phú"],
                   ["quan Tan Phu", "Quận Tân Phú"],
                   ["quan\.Tan Phu", "Quận Tân Phú"],
                   ["quan\. Tan Phu", "Quận Tân Phú"],
                   ["qTP", "Quận Tân Phú"],
                   ["q TP", "Quận Tân Phú"],
                   ["q\.TP", "Quận Tân Phú"],
                   ["q\. TP", "Quận Tân Phú"],
                   ["quan TP", "Quận Tân Phú"],
                   ["quan\.TP", "Quận Tân Phú"],
                   ["quan\. TP", "Quận Tân Phú"]]


wardListHCM = [["Tan Dinh","Phường Tân Định"],
["Da Kao","Phường Đa Kao"],
["Dakao","Phường Đa Kao"],
["P. Tan Thoi Hiep", "Phường Tân Thới Hiệp"],
["Tan Thoi Hiep", "Phường Tân Thới Hiệp"],
["Ben Nghe","Phường Bến Nghé"],
["Ben Thanh","Phường Bến Thành"],
["phuong Nguyen Thai Binh","Phường Nguyễn Thái Bình"],
["P. Nguyen Thai Binh","Phường Nguyễn Thái Bình"],
["NGUYEN THAI BINH WARD","Phường Nguyễn Thái Bình"],
["Pham Ngu Lao","Phường Phạm Ngũ Lão"],
["Ong Lanh","Phường Cầu Ông Lãnh"],
["phuong Co Giang","Phường Cô Giang"],
["Co Giang","Phường Cô Giang"],
["Nguyen Cu Trinh","Phường Nguyễn Cư Trinh"],
["Cau Kho","Phường Cầu Kho"],
["Tan Son Nhi","Phường Tân Sơn Nhì"],
["p.10", "Phường 10"],
["p\.10", "Phường 10"],
["p.\ 10", "Phường 10"],
["phuong 10", "Phường 10"],
["ward 10", "Phường 10"],
["10 ward", "Phường 10"],
["p.11", "Phường 11"],
["p\.11", "Phường 11"],
["p.\ 11", "Phường 11"],
["phuong 11", "Phường 11"],
["Ward 11", "Phường 11"],
["11 Ward", "Phường 11"],
["p.12", "Phường 12"],
["p\.12", "Phường 12"],
["p.\ 12", "Phường 12"],
["phuong 12", "Phường 12"],
["ward 12", "Phường 12"],
["12 ward", "Phường 12"],
["p.13", "Phường 13"],
["p\.13", "Phường 13"],
["p.\ 13", "Phường 13"],
["phuong 13", "Phường 13"],
["Ward 13", "Phường 13"],
["13 ward", "Phường 13"],
["p.14", "Phường 14"],
["p\.14", "Phường 14"],
["p.\ 14", "Phường 14"],
["phuong 14", "Phường 14"],
["ward 14", "Phường 14"],
["14 ward", "Phường 14"],
["p.15", "Phường 15"],
["p\.15", "Phường 15"],
["p.\ 15", "Phường 15"],
["phuong 15", "Phường 15"],
["ward 15", "Phường 15"],
["15 ward", "Phường 15"],
["p.16", "Phường 16"],
["p\.16", "Phường 16"],
["p.\ 16", "Phường 16"],
["phuong 16", "Phường 16"],
["ward 16", "Phường 16"],
["16 ward", "Phường 16"],
["p.17", "Phường 17"],
["p\.17", "Phường 17"],
["p.\ 17", "Phường 17"],
["phuong 17", "Phường 17"],
["ward 17", "Phường 17"],
["17 ward", "Phường 17"],
["p.18", "Phường 18"],
["p\.18", "Phường 18"],
["p.\ 18", "Phường 18"],
["phuong 18", "Phường 18"],
["ward 18", "Phường 18"],
["18 ward", "Phường 18"],
["p.19", "Phường 19"],
["p\.19", "Phường 19"],
["p.\ 19", "Phường 19"],
["phuong 19", "Phường 19"],
["ward 19", "Phường 19"],
["19 ward", "Phường 19"],
["p.20", "Phường 20"],
["p\.20", "Phường 20"],
["p.\ 20", "Phường 20"],
["phuong 20", "Phường 20"],
["ward 20", "Phường 20"],
["20 ward", "Phường 20"],
["p.21", "Phường 21"],
["p\.21", "Phường 21"],
["p.\ 21", "Phường 21"],
["phuong 21", "Phường 21"],
["ward 21", "Phường 21"],
["21 ward", "Phường 21"],
["p.22", "Phường 22"],
["p\.22", "Phường 22"],
["p.\ 22", "Phường 22"],
["phuong 22", "Phường 22"],
["ward 22", "Phường 22"],
["22 ward", "Phường 22"],
["p.23", "Phường 23"],
["p\.23", "Phường 23"],
["p.\ 23", "Phường 23"],
["phuong 23", "Phường 23"],
["ward 23", "Phường 23"],
["23 ward", "Phường 23"],
["p.24", "Phường 24"],
["p\.24", "Phường 24"],
["p.\ 24", "Phường 24"],
["phuong 24", "Phường 24"],
["ward 24", "Phường 24"],
["24 ward", "Phường 24"],
["p.25", "Phường 25"],
["p\.25", "Phường 25"],
["p.\ 25", "Phường 25"],
["phuong 25", "Phường 25"],
["ward 25", "Phường 25"],
["25 ward", "Phường 25"],
["p.26", "Phường 26"],
["p\.26", "Phường 26"],
["p.\ 26", "Phường 26"],
["phuong 26", "Phường 26"],
["ward 26", "Phường 26"],
["26 ward", "Phường 26"],
["p.27", "Phường 27"],
["p\.27", "Phường 27"],
["p.\ 27", "Phường 27"],
["phuong 27", "Phường 27"],
["ward 27", "Phường 27"],
["27 ward", "Phường 27"],
["p.28", "Phường 28"],
["p\.28", "Phường 28"],
["p.\ 28", "Phường 28"],
["phuong 28", "Phường 28"],
["ward 28", "Phường 28"],
["28 ward", "Phường 28"],
["p.29", "Phường 29"],
["p\.29", "Phường 29"],
["p.\ 29", "Phường 29"],
["phuong 29", "Phường 29"],
["ward 29", "Phường 29"],
["29 ward", "Phường 29"],
["p.30", "Phường 30"],
["p\.30", "Phường 30"],
["p.\ 30", "Phường 30"],
["phuong 30", "Phường 30"],
["ward 30", "Phường 30"],
["30 ward", "Phường 30"],
["p.1", "Phường 1"],
["p\.1", "Phường 1"],
["p.\ 1", "Phường 1"],
["phuong 01", "Phường 1"],
["phuong 1", "Phường 1"],
["ward 01", "Phường 1"],
["ward 1", "Phường 1"],
["01 ward", "Phường 1"],
["1 ward", "Phường 1"],
["p.2", "Phường 2"],
["p2", "Phường 2"],
["p\.2", "Phường 2"],
["p.\ 2", "Phường 2"],
["phuong 2", "Phường 2"],
["phuong 02", "Phường 2"],
["Ward 02", "Phường 2"],
["ward 2", "Phường 2"],
["2 ward", "Phường 2"],
["02 ward", "Phường 2"],
["p.3", "Phường 3"],
["p\.3", "Phường 3"],
["p.\ 3", "Phường 3"],
["phuong 3", "Phường 3"],
["phuong 03", "Phường 3"],
["3 Ward", "Phường 3"],
["ward 03", "Phường 3"],
["ward 3", "Phường 3"],
["03 ward", "Phường 3"],
["xa Binh Hung","Xã Bình Hưng"],
["p.4", "Phường 4"],
["p\.4", "Phường 4"],
["p.\ 4", "Phường 4"],
["phuong 04", "Phường 4"],
["phuong 4", "Phường 4"],
["4 Ward", "Phường 4"],
["ward 04", "Phường 4"],
["ward 4", "Phường 4"],
["p.5", "Phường 5"],
["p\.5", "Phường 5"],
["p.\ 5", "Phường 5"],
["phuong 5", "Phường 5"],
["phuong 05", "Phường 5"],
["Ward 05", "Phường 5"],
["ward 5", "Phường 5"],
["5 ward", "Phường 5"],
["p.6", "Phường 6"],
["p\.6", "Phường 6"],
["p.\ 6", "Phường 6"],
["phuong 6", "Phường 6"],
["phuong 06", "Phường 6"],
["Ward 06", "Phường 6"],
["ward 6", "Phường 6"],
["6 ward", "Phường 6"],
["p.7", "Phường 7"],
["p\.7", "Phường 7"],
["p.\ 7", "Phường 7"],
["phuong 7", "Phường 7"],
["Ward 07", "Phường 7"],
["Ward 7", "Phường 7"],
["7 ward", "Phường 7"],
["p.8", "Phường 8"],
["p\.8", "Phường 8"],
["p.\ 8", "Phường 8"],
["phuong 8", "Phường 8"],
["phuong 08", "Phường 8"],
["Ward 08", "Phường 8"],
["Ward 8", "Phường 8"],
["8 ward", "Phường 8"],
["p.9", "Phường 9"],
["p\.9", "Phường 9"],
["p.\ 9", "Phường 9"],
["phuong 9", "Phường 9"],
["phuong 09", "Phường 9"],
["Ward 9", "Phường 9"],
["ward 09", "Phường 9"],
["9 ward", "Phường 9"],
["Thao Dien","Phường Thảo Điền"],
['phuong An Phu',"Phường An Phú"],
['An Phu ward',"Phường An Phú"],
["phuong Binh An","Phường Bình An"],
["Binh An","Phường Bình An"],
["phuong Binh Trung Dong","Phường Bình Trưng Đông"],
["phuong Binh Trung Dong","Phường Bình Trưng Đông"],
["Binh Trung Tay","Phường Bình Trưng Tây"],
["Binh Khanh","Phường Bình Khánh"],
["An Khanh","Phường An Khánh"],
["Cat Lai","Phường Cát Lái"],
["Thanh My Loi","Phường Thạnh Mỹ Lợi"],
["An Loi Dong","Phường An Lợi Đông"],
["Thu Thiem","Phường Thủ Thiêm"],
["Tay Thanh","Phường Tây Thạnh"],
["Son Ky","Phường Sơn Kỳ"],
["Tan Quy","Phường Tân Quý"],
["Tan Thanh","Phường Tân Thành"],
["Phu Tho Hoa","Phường Phú Thọ Hòa"],
["Phu Thanh","Phường Phú Thạnh"],
["Hoa Thanh","Phường Hòa Thạnh"],
["phuong Hiep Tan","Phường Hiệp Tân"],
["Tan Thoi Hoa","Phường Tân Thới Hòa"],
["Thanh Xuanh","Phường Thạnh Xuân"],
["Thanh Loc","Phường Thạnh Lộc"],
["Hiep Thanh","Phường Hiệp Thành"],
["Thoi An","Phường Thới An"],
["Tan Chanh Hiep","Phường Tân Chánh Hiệp"],
["An Phu Dong", "Phường An Phú Đông"],
["Trung My Tay","Phường Trung Mỹ Tây"],
["Tan Hung Thuan", "Phường Tân Hưng Thuận"],
["Dong Hung Thuan", "Phường Đông Hưng Thuận"],
["Tan Thoi Nhat","Phường Tân Thới Nhất"],
["Linh Xuan","Phường Linh Xuân"],
["Binh Chieu", "Phường Bình Chiểu"],
["Linh Trung","Phường Linh Trung"],
["Tam Binh","Phường Tam Bình"],
["Tam Phu","Phường Tam Phú"],
["phuong Hiep Binh Phuoc","Phường Hiệp Bình Phước"],
[" Hiep Binh Phuoc","Phường Hiệp Bình Phước"],
["Hiep Binh Chanh","Phường Hiệp Bình Chánh"],
["Linh Chieu", "Phường Linh Chiểu"],
["Linh Tay", "Phường Linh Tây"],
["Linh Dong", "Phường Linh Đông"],
["Binh Tho","Phường Bình Thọ"],
["Truong Tho","Phường Trường Thọ"],
["Long Binh","Phường Long Bình"],
["Phường Long","Thạnh Mỹ"],
["Hiep Phu","Phường Hiệp Phú"],
["Tang Nhon Phu A","Phường Tăng Nhơn Phú A"],
["Tang Nhon Phu B","Phường Tăng Nhơn Phú B"],
["Phuoc Long B","Phường Phước Long B"],
["Phuoc Long A","Phường Phước Long A"],
["Truong Thanh","Phường Trường Thạnh"],
["Long Phuoc", "Phường Long Phước"],
["Long Truong","Phường Long Trường"],
["Phuoc Binh","Phường Phước Bình"],
["Phu Huu","Phường Phú Hữu"],
["Binh Hung Hoa A","Phường Bình Hưng Hoà A"],
["Binh Hung Hoa B","Phường Bình Hưng Hoà B"],
["Binh Hung Hoa","Phường Bình Hưng Hòa"],
["xa Binh Hung","Xã Bình Hưng"],
["Binh Tri Dong A","Phường Bình Trị Đông A"],
["Binh Tri Dong B","Phường Bình Trị Đông B"],
["Binh Tri Dong","Phường Bình Trị Đông"],
["Tan Tao A","Phường Tân Tạo A"],
["Tan Tao","Phường Tân Tạo"],
["An Lac A","Phường An Lạc A"],
["An Lac","Phường An Lạc"],
["Tan Thuan Dong","Phường Tân Thuận Đông"],
["Tan Thuan Tay","Phường Tân Thuận Tây"],
["Tan Kieng","Phường Tân Kiểng"],
["Tan Hung","Phường Tân Hưng"],
["Binh Thuan","Phường Bình Thuận"],
["Tan Quy","Phường Tân Quy"],
["P.Phu Thuan","Phường Phú Thuận"],
["Tan Phong","Phường Tân Phong"],
['phu my hung','Khu đô thị Phú Mỹ Hưng'],
[" Phu My ","Phường Phú Mỹ"],
["TT.Cu Chi","Thị trấn Củ Chi"],
["xa Phu My Hung","Xã Phú Mỹ Hưng"],
["xa An Phu","Xã An Phú"],
["Trung Lap Thuong","Xã Trung Lập Thượng"],
["An Nhon Tay","Xã An Nhơn Tây"],
["Thuan Duc","Xã Nhuận Đức"],
["Pham Van Coi","Xã Phạm Văn Cội"],
["Phu Hoa","Xã Phú Hòa Đông"],
["Trung Lap Ha","Xã Trung Lập Hạ"],
["Trung An","Xã Trung An"],
["Phuoc Thanh","Xã Phước Thạnh"],
["Phuoc Hiep","Xã Phước Hiệp"],
["Tan An Hoi","Xã Tân An Hội"],
["Phuoc Vinh An","Xã Phước Vĩnh An"],
["Thai My","Xã Thái Mỹ"],
["Tan Thanh Tay","Xã Tân Thạnh Tây"],
["Hoa Phu","Xã Hòa Phú"],
["Tan Thanh Dong","Xã Tân Thạnh Đông"],
["Binh My","Xã Bình Mỹ"],
["Tan Phu Trung","Xã Tân Phú Trung"],
["Tan Thong Hoi","Xã Tân Thông Hội"],
["Hoc Mon","Thị trấn Hóc Môn"],
["Tan Hiep","Xã Tân Hiệp"],
["Nhi Binh","Xã Nhị Bình"],
["Dong Thanh","Xã Đông Thạnh"],
["Tan Thoi Nhi","Xã Tân Thới Nhì"],
["Thoi Tam Thon","Xã Thới Tam Thôn"],
["Xuan Thoi Son","Xã Xuân Thới Sơn"],
["Tan Xuan","Xã Tân Xuân"],
["Xuan Thoi Dong","Xã Xuân Thới Đông"],
["Trung Chanh","Xã Trung Chánh"],
["Xuan Thoi Thuong","Xã Xuân Thới Thượng"],
["Ba Diem","Xã Bà Điểm"],
["Tan Tuc","Thị trấn Tân Túc"],
["Pham Van Hai","Xã Phạm Văn Hai"],
["Vinh Loc A","Xã Vĩnh Lộc A"],
["Vinh Loc B","Xã Vĩnh Lộc B"],
["Binh Loi","Xã Bình Lợi"],
["Le Minh Xuan","Xã Lê Minh Xuân"],
["Tan Nhut","Xã Tân Nhựt"],
["Tan Kien","Xã Tân Kiên"],
["Phong Phu","Xã Phong Phú"],
["An Phu Tay","Xã An Phú Tây"],
["Hung Long","Xã Hưng Long"],
["Da Phuoc","Xã Đa Phước"],
["Tan Quy Tay","Xã Tân Quý Tây"],
["Quy Duc","Xã Quy Đức"],
["Phuoc Kien","Xã Phước Kiển"],
["Phuoc Loc","Xã Phước Lộc"],
["Nhon Duc","Xã Nhơn Đức"],
["Phu Xuan","Xã Phú Xuân"],
["Long Thoi","Xã Long Thới"],
["Hiep Phuoc","Xã Hiệp Phước"],
["Can Thanh","Thị trấn Cần Thạnh"],
["Binh Khanh","Xã Bình Khánh"],
["Tam Thon Hiep","Xã Tam Thôn Hiệp"],
["An Thoi Dong","Xã An Thới Đông"],
["Thanh An","Xã Thạnh An"],
["Long Hoa","Xã Long Hòa"],
["Binh Chanh","Xã Bình Chánh"],
["Ly Nhon","Xã Lý Nhơn"],
["Tan Phu","Phường Tân Phú"],
["Binh Hung","Xã Bình Hưng"],
["Phu Trung","Phường Phú Trung"],]

##---------------------------------------------------------------------------------------------------------------------##

streetListHCM = [
["tran dinh xu","Trần Đình Xu"],
["vo thi nho","Võ Thị Nhờ"],
["duong truong son","Đường Trường Sơn"],
["truong son","Đường Trường Sơn"],
["43 street","Đường số 43"],
["duong so7","Đường số 7"],
["thu khoa huan","Thủ Khoan Huân"],
["duong 10", "Đường số 10"],
["3/2 Street","Đường 3 tháng 2"],
["le van thiem","Phố Lê Văn Thiêm"],
["duong 3/2", "Đường 3 tháng 2"],
["song day","Sông Đáy"],
["No 6 St","Đường số 6"],
["Street 20", "Đường số 20"],
["Street 33", "Đường số 33"],
["Street Number 6", "Đường số 6"],
["Street No. 6", "Đường số 6"],
["Stress No. 4","Đường số 4"],
["Street No. 14", "Đường số 14"], 
["Street No 64","Đường số 64"],   
["Doan Nhu Hai","Đoàn Như Hải"],
["vo thi nhua","Võ Thị Nhúa"],
["Dinh Thi Thi","Đinh Thị Thi"],
["Bui Thi Lung","Bùi Thị Lùng"],
["Nguyen Thi Bup","Nguyễn Thị Búp"],
["Rach Long Den","Rạch Lồng Đèn"],
["Tan Hai","Tân Hải"],
["Duong Thi Giang","Dương Thị Giang"],
["Tran Thi Co","Trần Thị Cờ"],
["Ngo Thi Thu Minh","Ngô Thị Thu Minh"],
["Hoang Ke Viem","Hoàng Kế Viêm"],
["Tran Phu","Trần Phú"],
["Truong Van Da","Trương Văn Đa"],
["Cu Xa Dong Tien","Cư Xá Đồng Tiến"],
["Thoi Tam Thon 17","Thới Tam Thôn 17"],
["Nguyen Thi Nuoi","Nguyễn Thị Nuôi"],
["Trung My Tay 13","Trung Mỹ Tây 13"],
["Tac Xuat","Tắc Xuất"],
["Nguyen Thi Ngau","Nguyễn Thị Ngâu"],
["Tan Cang","Tân Cảng"],
["Nhi Binh 17","Nhị Bình 17"],
["Tran Thi Tro","Trần Thị Trò"],
["Nguyen Thi Thu Minh","Nguyễn Thị Thu Minh"],
["Nguyen Quang Dieu","Nguyễn Quang Diêu"],
["Le Canh Tuan","Lê Cảnh Tuân"],
["Tinh Lo 2","Tỉnh Lộ 2"],
["Nguyen Quang Bich","Nguyễn Quang Bích"],
["Cong Truong Tu Do","Công Trường Tự Do"],
["Tran Te Xuong","Trần Tế Xương"],
["Huong Lo 5","Hương Lộ 5"],
["Giong Ao","Giồng Ao"],
["Nhi Binh 18","Nhị Bình 18"],
["Lam Thi Ho","Lâm Thị Hố"],
["Huynh Thi Hai","Huỳnh Thị Hai"],
["Cau Xeo","Cầu Xéo"],
["Huynh Thi Mai","Huỳnh Thị Mài"],
["Le Van Huan","Lê Văn Huân"],
["Chu Manh Trinh","Chu Mạnh Trinh"],
["Cong Paris","Công Paris"],
["Cong Truong Dan chu","Công Trường Dân chủ"],
["Cong Truong Quoc Te","Công Trường Quốc Tế"],
["Truong Cong Dinh","Trương Công Định"],
["Dinh Tien Hoang","Đinh Tiên Hoàng"],
["Dong Du","Đông Du"],
["vanh dai phia dong","Vành đai phía đông"],
["Nguyen Duy Trinh","Nguyễn Duy Trinh"],
["Dong Khoi","Đồng Khởi"],
["goc pho Hai Ba Trung","Hai Bà Trưng"],
["Hai Ba Trung","Hai Bà Trưng"],
["Hai Trieu","Hải Triều"],
["Ham Nghi","Hàm Nghi"],
["Han Thuyen","Hàn Thuyên"],
["Ho Tung Mau","Hồ Tùng Mậu"],
["Huynh Thuc Khang","Huỳnh Thúc Kháng"],
["Le Loi","Lê Lợi"],
["Dam Van Le","Đàm Văn Lễ"],
["Le Hien Mai","Lê Hiến Mai"],
["Pham Don Le","Phạm Đôn Lễ"],
["Vo Huu Loi","Võ Hữu Lợi"],
["Le Thanh Ton","Lê Thánh Tôn"],
["Le Van Huu","Lê Văn Hưu"],
["Ly Tu Trong","Lý Tự Trọng"],
["Mac Dinh Chi","Mạc Đĩnh Chi"],
["Mac Thi Buoi","Mạc Thị Bưởi"],
["Nam Ky Khoi Nghia","Nam Kỳ Khởi Nghĩa"],
["Ngo Duc Ke","Ngô Đức Kế"],
["Ngo Van Nam","Ngô Văn Năm"],
["Nguyen Binh Khiem","Nguyễn Bỉnh Khiêm"],
["Nguyen Du","Nguyễn Du"],
["Nguyen Duy Hieu","Nguyễn Duy Hiệu"],
["Nguyen Duy Duong","Nguyễn Duy Dương"],
["Nguyen Duc Canh","Nguyễn Đức Cảnh"],
["Nguyen Duy","Nguyễn Duy"],
["Pho Duc Chinh","Phó Đức Chính"],
["Ton Duc Thang","Tôn Đức Thắng"],
["Nguyen Quy Duc","Nguyễn Quý Đức"],
["Nguyen Van Dung","Nguyễn Văn Đừng"],
["dai lo Nguyen Hue","Nguyễn Huệ"],
["Nguyen Hue","Nguyễn Huệ"],
["Nguyen Huu Canh","Nguyễn Hữu Cảnh"],
["Nguyen Thiep","Nguyễn Thiệp"],
["Pasteur","Pasteur"],
["Tran Xuan Soan","Trần Xuân Soạn"],
["Thai Van Lung","Thái Văn Lung"],
["Thi Sach","Thi Sách"],
["Ton That Dam","Tôn Thất Đạm"],
["Ton That Hiep","Tôn Thất Hiệp"],
["Ton That Thuyet","Tôn Thất Thuyết"],
["Ton That Thiep","Tôn Thất Thiệp"],
["Bui Thi Xuan","Bùi Thị Xuân"],
["Cach Mang Thang 8","Cách Mạng Tháng 8"],
["Dang Tran Con","Đặng Trần Côn"],
["Le Anh Xuan","Lê Anh Xuân"],
["Le Lai","Lê Lai"],
["Le Dinh Quan","Lê Đình Quản"],
["Le Phung Hieu","Lê Phụng Hiểu"],
["Le Van Thinh","Lê Văn Thịnh"],
["Le Thi Rieng","Lê Thị Riêng"],
["Luu Van Lang","Lưu Văn Lang"],
["Nguyen An Ninh","Nguyễn An Ninh"],
["Nguyen Thi Nghia","Nguyễn Thị Nghĩa"],
["Nguyen Trai","Nguyễn Trãi"],
["Nguyen Trung Truc","Nguyễn Trung Trực"],
["Nguyen Van Trang","Nguyễn Văn Tráng"],
["Pham Hong Thai","Phạm Hồng Thái"],
["Phan Boi Chau","Phan Bội Châu"],
["Phan Chu Trinh","Phan Chu Trinh"],
["Suong Nguyet Anh","Sương Nguyệt Ánh"],
["Thu Khoa Huan","Thủ Khoa Huân"],
["Ton That Tung","Tôn Thất Tùng"],
["Ben Chuong Duong","Bến Chương Dương"],
["Dinh Cong Trang","Đinh Công Tráng"],
["Nguyen Canh Chan","Nguyễn Cảnh Chân"],
["Nguyen Van Cu","Nguyễn Văn Cừ"],
["Nguyen Van Cua","Nguyễn Văn Của"],
["Nguyen Van Cu","Nguyễn Văn Cự"],
["Nguyen Cuu Van","Nguyễn Cửu Vân"],
["Nguyen Van Kha","Nguyễn Văn Khạ"],
["Nguyen Van Ni","Nguyễn Văn Ni"],
["Nguyen Van On","Nguyễn Văn On"],
["Nguyen Van Ty","Nguyễn Văn Tỳ"],
["Nguyen Van Xo","Nguyễn Văn Xơ"],
["Nguyen Van Tiep","Nguyễn Văn Tiệp"],
["Tran Hung Dao B","Trần Hưng Đạo B"],
["Tran Hung Dao A","Trần Hưng Đạo A"],
["Tran Hung Dao","Trần Hưng Đạo"],
["Vo Van Kiet","Võ Văn Kiệt"],
["Co Bac","Cô Bắc"],
["Co Giang","Cô Giang"],
["De Tham","Đề Thám"],
["Ho Hao Hon","Hồ Hảo Hớn"],
["Nguyen Khac Nhu","Nguyễn Khắc Nhu"],
["Tran Dinh Xu","Trần Đình Xu"],
["Le Thi Hong Gam","Lê Thị Hồng Gấm"],
["Nguyen Cong Tru","Nguyễn Công Trứ"],
["Cong Truong Quach Thi Trang","Công Trường Quách Thị Trang"],
["Nguyen Phi Khanh","Nguyễn Phi Khanh"],
["Calmette","Calmette"],
["Dang Thi Nhu","Đặng Thị Nhu"],
["Ky Con","Ký Con"],
["Ki Con","Ký Con"],
["Le Cong Kieu","Lê Công Kiều"],
["Yersin","Yersin"],
["Nguyen Thai Hoc","Nguyễn Thái Học"],
["Trinh Van Can","Trịnh Văn Cấn"],
["Dang Van Kieu","Đặng Văn Kiều"],
["Luong Van Nho","Lương Văn Nho"],
["Hoa Hao","Hoà Hảo"],
["Hoa Hao","Hòa Hảo"],
["Nguyen Huu Hao","Nguyễn Hữu Hào"],
["Phan Van Hon","Phan Văn Hớn"],
["Nguyen Khac Vien","Nguyễn Khắc Viện"],
["Cay Diep","Cây Điệp"],
["Cay Sung","Cây Sung"],
["Dien Bien Phu","Điện Biên Phủ"],
["Hoang Sa","Hoàng Sa"],
["Huynh Khuong Ninh","Huỳnh Khương Ninh"],
["Huynh Khuong An","Huỳnh Khương An"],
["Mai Thi Luu","Mai Thị Lựu"],
["Nguyen Dinh Chieu","Nguyễn Đình Chiểu"],
["Nguyen Huy Tu","Nguyễn Huy Tự"],
["Nguyen Huy Tuong","Nguyễn Huy Tưởng"],
["Nguyen Thanh Y","Nguyễn Thành Ý"],
["Nguyen Thi Minh Khai","Nguyễn Thị Minh Khai"],
["Nguyen Van Giai","Nguyễn Văn Giai"],
["Nguyen Dang Giai","Nguyễn Đăng Giai"],
["Nguyen Van Thu","Nguyễn Văn Thủ"],
["Nguyen Van Linh","Nguyễn Văn Linh"],
["Nguyen Van Quy","Nguyễn Văn Quỳ"],
["Nguyen Van Qua","Nguyễn Văn Quá"],
["Nguyen Van Ba","Nguyễn Văn Bá"],
["Nguyen Van Lich","Nguyễn Văn Lịch"],
["Nguyen Van Ba","Nguyễn Văn Ba"],
["Nguyen Van Bua","Nguyễn Văn Bứa"],
["Phan Ke Binh","Phan Kế Bính"],
["Phan Liem","Phan Liêm"],
["Phan Ngu","Phan Ngữ"],
["Nguyen Phan Chanh","Nguyễn Phan Chánh"],
["Nguyen Phan Vinh","Nguyễn Phan Vinh"],
["Phan Ton","Phan Tôn"],
["Vu Tong Phan","Vũ Tông Phan"],
["Phung Khac Khoan","Phùng Khắc Khoan"],
["Tran Cao Van","Trần Cao Vân"],
["Tran Doan Khanh","Trần Doãn Khanh"],
["Truong Han Sieu","Trương Hán Siêu"],
["Vo Thi Sau","Võ Thị Sáu"],
["Cao Ba Nha","Cao Bá Nhạ"],
["Ba Ca Ho","Bà Cà Hổ"],
["Cong Quynh","Cống Quỳnh"],
["Nguyen Cu Trinh","Nguyễn Cư Trinh"],
["Bui Vien","Bùi Viện"],
["Nguyen Thien Thuat","Nguyễn Thiện Thuật"],
["Pham Viet Chanh","Phạm Viết Chánh"],
["Pham Hung","Phạm Hùng"],
["Thanh Nien","Thanh Niên"],
["Vinh Loc","Vĩnh Lộc"],
["Pham Tan Muoi","Phạm Tấn Mười"],
["Mai Ba Huong","Mai Bá Hương"],
["Phan Van Giau","Phan Văn Giàu"],
["Tran Van Giau","Trần Văn Giàu"],
["Vo Van Van","Võ Văn Vân"],
["Pham Van Sang","Phạm Văn Sáng"],
["Pham Van Dong","Phạm Văn Đồng"],
["Tinh Lo 10","Tỉnh Lộ 10"],
["Lang Le Bau Co","Láng Le Bàu Cò"],
["Dang Nhu Lam","Đặng Nhữ Lâm"],
["Dang Nhu Mai","Đặng Như Mai"],
["Nhu Tien Hien","Nhữ Tiến Hiến"],
["Do Quang Dau","Đỗ Quang Đẩu"],
["Luong Huu Khanh","Lương Hữu Khánh"],
["Nam Quoc Cang","Nam Quốc Cang"],
["Nguyen Thuong Hien","Nguyễn Thượng Hiền"],
["Do Quang","Đỗ Quang"],
["Ba Le Chan","Bà Lê Chân"],
["Dang Dung","Đặng Dung"],
["Dang Tat","Đặng Tất"],
["Huyen Quang","Huyền Quang"],
["Trinh Quang Nghi","Trịnh Quang Nghị"],
["Ha Quang Voc","Hà Quang Vóc"],
["Tran Quang Dao","Trần Quang Đạo"],
["Tran Quang Nhon","Trần Quang Nhơn"],
["Quang Trung","Quang Trung"],
["Ly Van Phuc","Lý Văn Phức"],
["Ma Lo","Mã Lộ"],
["hung phuoc 4","Hưng Phước 4"],
["hung phuoc4","Hưng Phước 4"],
["hung phuoc 3","Hưng Phước 3"],
["Ma Lo","Mã Lò"],
["Nguyen Huu Cau","Nguyễn Hữu Cầu"],
["Nguyen Van Nguyen","Nguyễn Văn Nguyễn"],
["Thach Thi Thanh","Thạch Thị Thanh"],
["Tran Khac Chan","Trần Khắc Chân"],
["Tran Khanh Du","Trần Khánh Dư"],
["Tran Nhat Duat","Trần Nhật Duật"],
["Tran Quang Khai","Trần Quang Khải"],
["Tran Quy Khoach","Trần Quý Khoách"],
["Tran Quy","Trần Quý"],
["Luong Dinh Cua","Lương Định Của"],
["Bui Ta Han","Bùi Tá Hán"],
["Ta Uyen","Tạ Uyên"],
["Cao Duc Lan","Cao Đức Lân"],
["Ngoc Lan","Ngọc Lan"],
["Cao Xuan Duc","Cao Xuân Dục"],
["Do Phap Thuan","Đỗ Pháp Thuận"],
["Do Xuan Hop","Đỗ Xuân Hợp"],
["Doan Huu Trung","Đoàn Hữu Trung"],
["duong so 100 Binh Thoi","Đường số 100 Bình Thới"],
["duong so 154","Đường số 154"],
["duong so 10B","Đường số 10B"],
["duong so 10C","Đường số 10C"],
["duong so 10E","Đường số 10E"],
["duong so 10F","Đường số 10F"],
["duong so 10G","Đường số 10G"],
["duong so 12A","Đường số 12A"],
["duong so 12B","Đường số 12B"],
["duong so 12C","Đường số 12C"],
["duong so 17A","Đường số 17A"],
["duong so 17B","Đường số 17B"],
["duong so 176","Đường số 176"],
["duong so 179","Đường số 179"],
["duong so 18B","Đường số 18B"],
["duong so 185","Đường số 185"],
["duong so 182","Đường số 182"],
["duong so 197","Đường số 197"],
["duong so 19A","Đường số 19A"],
["duong so 19B","Đường số 19B"],
["duong so 19C","Đường số 19C"],
["duong so 34A","Đường số 34A"],
["duong so 34B","Đường số 34B"],
["duong so 379","Đường số 379"],
["duong so 10A","Đường số 10A"],
["Duong Van An","Dương Văn An"],
["Giang Van Minh","Giang Văn Minh"],
["Lien tinh lo 25B","Liên tỉnh lộ 25B"],
["Mai Chi Tho","Mai Chí Thọ"],
["Nhat Chi Mai","Nhất Chi Mai"],
["Nguyen Hoang","Nguyễn Hoàng"],
["Nguyen Minh Hoang","Nguyễn Minh Hoàng"],
["Nguyen Quy Canh","Nguyễn Quý Cảnh"],
["Doan Nguyen Tuan","Đoàn Nguyễn Tuân"],
["Nguyen Van Long","Nguyễn Văn Long"],
["Nguyen Van The","Nguyễn Văn Thê"],
["Nguyen Van Thoi","Nguyễn Văn Thời"],
["Hung Long","Hưng Long"],
["Nguyen Quy Anh","Nguyễn Quý Anh"],
["Hoc Huu","Hóc Hữu"],
["Nguyen Thi Dinh","Nguyễn Thị Định"],
["Nguyen Dinh Huan","Nguyễn Đình Huân"],
["song Hanh","Đường Song Hành"],
["duong song hanh QL 22","Đường song hành QL 22"],
["Thai Thuan","Thái Thuận"],
["Van Than","Văn Thân"],
["Tran Luu","Trần Lựu"],
["Luu Khai Hong","Lưu Khai Hồng"],
["Tran Nao","Trần Não"],
["Vo Truong Toan","Võ Trường Toản"],
["Vu Ngoc Phan","Vũ Ngọc Phan"],
["Xa Lo Ha Noi","Xa Lộ Hà Nội"],
["duong D22","D22"],
["duong D2","D2"],
["duong so 14A","Đường số 14A"],
["duong so 148","Đường số 148"],
["duong so 147","Đường số 147"],
["duong so 144","Đường số 144"],
["duong so 30A","Đường số 30A"],
["duong so 332","Đường số 332"],
["duong so 339","Đường số 339"],
["duong so 33A","Đường số 33A"],
["duong so 33B","Đường số 33B"],
["Vanh Dai","Vành Đai"],
["Nguyen Van Kinh","Nguyễn Văn Kinh"],
["Binh Trung","Bình Trưng"],
["Nguyen Trung Nguyet","Nguyễn Trung Nguyệt"],
["duong so 168","Đường số 168"],
["duong so 160","Đường số 160"],
["duong so 236","Đường số 236"],
["duong so 23A","Đường số 23A"],
["duong so 23B","Đường số 23B"],
["duong so 318","Đường số 318"],
["duong so 311","Đường số 311"],
["duong so 319","Đường số 319"],
["duong so 31A","Đường số 31A"],
["duong so 400","Đường số 400"],
["duong so 40A","Đường số 40A"],
["duong so 40B","Đường số 40B"],
["duong so 429","Đường số 429"],
["duong so 42A","Đường số 42A"],
["Hiep Thanh 42","Hiệp Thành 42"],
["Dong Hung Thuan 42","Đông Hưng Thuận 42"],
["duong so 46A","Đường số 46A"],
["duong so 46B","Đường số 46B"],
["duong so 494","Đường số 494"],
["duong so 49B","Đường số 49B"],
["duong so 49C","Đường số 49C"],
["Hiep Thanh 49","Hiệp Thành 49"],
["Ca Van Thinh","Ca Văn Thỉnh"],
["Nguyen Don Tiet","Nguyễn Đôn Tiết"],
["Luong Minh Nguyet","Lương Minh Nguyệt"],
["Thich Minh Nguyet","Thích Minh Nguyệt"],
["Nguyen Van Giap","Nguyễn Văn Giáp"],
["Tran Van Giap","Trần Văn Giáp"],
["Bat Nan","Bát Nàn"],
["duong so 24A","Đường số 24A"],
["duong so 26A","Đường số 26A"],
["duong so 28A","Đường số 28A"],
["duong so 245","Đường số 245"],
["duong so 244","Đường số 244"],
["duong so 359","Đường số 359"],
["duong so 385","Đường số 385"],
["duong so 38A","Đường số 38A"],
["duong 10","Đường số 10"],
["Le Huu Kieu","Lê Hữu Kiều"],
["Nguyen Tu Nghiem","Nguyễn Tư Nghiêm"],
["Nguyen Nghiem","Nguyễn Nghiêm"],
["Nguyen Tuyen","Nguyễn Tuyển"],
["Nguyen Trong Tuyen","Nguyễn Trọng Tuyển"],
["Nguyen Ba Tuyen","Nguyễn Bá Tuyển"],
["Nguyen Thanh Tuyen","Nguyễn Thanh Tuyền"],
["Truong Van Bang","Trương Văn Bang"],
["Dong Van Cong","Đồng Văn Cống"],
["Nguyen Van Cong","Nguyễn Văn Công"],
["duong so 25A","Đường số 25A"],
["duong so 266","Đường số 266"],
["duong so 265","Đường số 265"],
["duong so 26B","Đường số 26B"],
["duong so 297","Đường số 297"],
["duong so 295","Đường số 295"],
["Dinh Le","Đinh Lễ"],
["Le Quang Dinh","Lê Quang Định"],
["Le Dinh Can","Lê Đình Cẩn"],
["Le Trung Dinh","Lê Trung Đình"],
["Le Dinh Tham","Lê Đình Thám"],
["Le Dinh Thu","Lê Đình Thụ"],
["Nguyen Thi Nho","Nguyễn Thị Nhỏ"],
["Nguyen Thi Tan","Nguyễn Thị Tần"],
["Vanh Dai Trong","Vành Đai Trong"],
["Dang Thai Mai","Đặng Thai Mai"],
["Lam Quang Ky","Lâm Quang Ky"],
["Pham Cong Tru","Phạm Công Trứ"],
["Pham Hy Luong","Phạm Hy Lượng"],
["Pham Nhat Duat","Phạm Nhật Duật"],
["Phan Van Dang","Phan Văn Đáng"],
["Phan Dang Luu","Phan Đăng Lưu"],
["Su Huy Nhan","Sư Huy Nhan"],
["Ta Hien","Tạ Hiện"],
["Thich Mat The","Thích Mật Thể"],
["Thich Buu Quang","Thích Bửu Quang"],
["Thich Quang Duc","Thích Quảng Đức"],
["Thich Thien Hoa","Thích Thiện Hòa"],
["Pham Quy Thich","Phạm Quý Thích"],
["Trinh Khac Lap","Trịnh Khắc Lập"],
["Truong Gia Mo","Trương Gia Mô"],
["Dang Huu Pho","Đặng Hữu Phổ"],
["Hiep Thanh 43","Hiệp Thành 43"],
["Thanh Xuan 43","Thạnh Xuân 43"],
["duong so 440","Đường số 440"],
["duong so 441","Đường số 441"],
["duong so 442","Đường số 442"],
["duong so 449","Đường số 449"],
["Hiep Thanh 44","Hiệp Thành 44"],
["duong so 546","Đường số 546"],
["Thanh Loc 54","Thạnh Lộc 54"],
["Le Thuoc","Lê Thước"],
["Cam Ba Thuoc","Cầm Bá Thước"],
["Le Van Mien","Lê Văn Miến"],
["Ngo Quang Huy","Ngô Quang Huy"],
["Nguyen Ba Huan","Nguyễn Bá Huân"],
["Hoang Ba Huan","Hoàng Bá Huân"],
["Nguyen Ba Lan","Nguyễn Bá Lân"],
["Hau Lan-Ba Diem","Hậu Lân-Bà Điểm"],
["Nam Lan","Nam Lân"],
["Hau Lan 18","Hậu Lân 18"],
["Nguyen Cu","Nguyễn Cừ"],
["Cu Lao Nguyen Kieu","Cù Lao Nguyễn Kiệu"],
["Nguyen Giao","Nguyễn Giao"],
["Nguyen Dai Nang","Nguyễn Đại Năng"],
["Nguyen Phong Sac","Nguyễn Phong Sắc"],
["Nguyen Phu Tru","Nguyễn Phú Trú"],
["Nguyen Thi Lam","Nguyễn Thị Lâm"],
["Nguyen Thi Lua","Nguyễn Thị Lừa"],
["Nguyen Thi Ru","Nguyễn Thị Rư"],
["Nguyen Thi Trieu","Nguyễn Thị Triệu"],
["Nguyen Van Huong","Nguyễn Văn Hưởng"],
["Quoc Huong","Quốc Hương"],
["Nguyen U Di","Nguyễn Ư Dĩ"],
["Tran Ngoc Dien","Trần Ngọc Diện"],
["Truc Duong","Trúc Đường"],
["duong Truc","Đường Trục"],
["Xuan Thuy","Xuân Thủy"],
["Dai Lo Vong Cung","Đại Lộ Vòng Cung"],
["Ly Thai To","Lý Thái Tổ"],
["Ly Thai Tong","Lý Thái Tông"],
["Nguyen Phuc Nguyen","Nguyễn Phúc Nguyên"],
["Rach Bung Binh","Rạch Bùng Binh"],
["Bung Ong Thoan","Bưng Ông Thoàn"],
["Tran Van Dang","Trần Văn Đang"],
["Dang Van Suu","Đặng Văn Sửu"],
["Le Van Sy","Lê Văn Sỹ"],
["Truong Sa","Trường Sa"],
["Tran Quang Dieu","Trần Quang Diệu"],
["Cao Thang","Cao Thắng"],
["duong Ban Co","Bàn Cờ"],
["Ban Co","Bàn Cờ"],
["Nguyen Hien Le","Nguyễn Hiến Lê"],
["Nguyen Hien","Nguyễn Hiền"],
["Nguyen Than Hien","Nguyễn Thần Hiến"],
["Vuon Chuoi","Vườn Chuối"],
["Nguyen son Ha","Nguyễn Sơn Hà"],
["Vo Van Tan","Võ Văn Tần"],
["Vo Van Dung","Võ Văn Dũng"],
["Vo Van Bich","Võ Văn Bích"],
["Ba Thanh Quan","Bà Thanh Quan"],
["Ho Xuan Huong","Hồ Xuân Hương"],
["Le Quy Don","Lê Quý Đôn"],
["Ngo Thoi Nhiem","Ngô Thời Nhiệm"],
["Ngo Quyen","Ngô Quyền"],
["Nguyen Gia Thieu","Nguyễn Gia Thiều"],
["Nguyen Thi Dieu Huong","Nguyễn Thị Diệu Hương"],
["Nguyen Thi Dieu","Nguyễn Thị Diệu"],
["Nguyen Thong","Nguyễn Thông"],
["Pham Dinh Toai","Phạm Đình Toái"],
["Huyen Toai","Huyền Toại"],
["Pham Ngoc Thach","Phạm Ngọc Thạch"],
["Su Thien Chieu","Sư Thiện Chiếu"],
["Quan Su","Quân Sự"],
["Tran Quoc Thao","Trần Quốc Thảo"],
["Truong Dinh Hoi","Trương Đình Hợi"],
["Truong Dinh Hoi","Trương Đình Hội"],
["Truong Dinh","Trương Định"],
["Truong Quyen","Trương Quyền"],
["Le Ngo Cat","Lê Ngô Cát"],
["Ly Chinh Thang","Lý Chính Thắng"],
["Tran Quoc Toan","Trần Quốc Toản"],
["Tu Xuong","Tú Xương"],
["tu cau vuot xuong","Từ cầu vượt xuống"],
["Huynh Tinh Cua","Huỳnh Tịnh Của"],
["Nguyen Van Mai","Nguyễn Văn Mai"],
["Nguyen Van Mai","Nguyễn Văn Mại"],
["Mai Van Ngoc","Mai Văn Ngọc"],
["Ky Dong","Kỳ Đồng"],
["Ben Van Don","Bến Vân Đồn"],
["Nguyen Khoai","Nguyễn Khoái"],
["Doan Van Bo","Đoàn Văn Bơ"],
["Hoang Dieu 2","Hoàng Diệu 2"],
["Hoang Dieu","Hoàng Diệu"],
["Le Quoc Hung","Lê Quốc Hưng"],
["Le Thach","Lê Thạch"],
["Nguyen Truong To","Nguyễn Trường Tộ"],
["Le Van Linh","Lê Văn Linh"],
["Le Van Chi","Lê Văn Chí"],
["Le Van Ninh","Lê Văn Ninh"],
["Le Van Tach","Lê Văn Tách"],
["Nguyen Tat Thanh","Nguyễn Tất Thành"],
["Ton Dan","Tôn Đản"],
["Xom Chieu","Xóm Chiếu"],
["Xom Dat","Xóm Đất"],
["Xom Chi","Xóm Chỉ"],
["Xom Voi","Xóm Vôi"],
["Ben Xom Cui","Bến Xóm Củi"],
["Khanh Hoi","Khánh Hội"],
["Vinh Hoi","Vĩnh Hội"],
["Cu xa Vinh Hoi","Cư xá Vĩnh Hội"],
["Tan Vinh","Tân Vĩnh"],
["Mai Van Vinh","Mai Văn Vĩnh"],
["Chau Vinh Te","Châu Vĩnh Tế"],
["Nguyen Van Vinh","Nguyễn Văn Vinh"],
["Loc Vinh","Lộc Vinh"],
["Nguyen Van Vinh","Nguyễn Văn Vịnh"],
["Le Vinh Hoa","Lê Vĩnh Hòa"],
["Nguyen Hao Vinh","Nguyễn Hảo Vĩnh"],
["Truong Vinh Ky","Trương Vĩnh Ký"],
["Luong The Vinh","Lương Thế Vinh"],
["Tan Hiep Vinh Loc","Tân Hiệp Vĩnh Lộc"],
["Cao Dat","Cao Đạt"],
["Huynh Man Dat","Huỳnh Mẫn Đạt"],
["Nguyen Bieu","Nguyễn Biểu"],
["Tran Binh Trong","Trần Bình Trọng"],
["Tran Trong Khiem","Trần Trọng Khiêm"],
["An Diem","An Điềm"],
["Ba Diem 12","Bà Điểm 12"],
["Ba Diem 5","Bà Điểm 5"],
["Chau Van Liem","Châu Văn Liêm"],
["Hai Thuong Lan Ong","Hải Thượng Lãn Ông"],
["Hung Vuong","Hùng Vương"],
["Pham Don","Phạm Đôn"],
["Pham Van Coi","Phạm Văn Cội"],
["Phan Phu Tien","Phan Phú Tiên"],
["Tan Da","Tản Đà"],
["Dao Tan","Đào Tấn"],
["Dang Dai Do","Đặng Đại Độ"],
["Dang Duc Thuat","Đặng Đức Thuật"],
["Ton Dat Tien","Tôn Dật Tiên"],
["dan cau Phu My","dẫn cầu Phú Mỹ"],
["Xa Lo Dai Han","Xa Lộ Đại Hàn"],
["Pham Dang Giang","Phạm Đăng Giảng"],
["Tan Hang","Tân Hàng"],
["Trieu Quang Phuc","Triệu Quang Phục"],
["Hong Bang","Hồng Bàng"],
["Ky Hoa","Ký Hòa"],
["Tan Ky Tan Quy","Tân Kỳ Tân Quý"],
["Lao Tu","Lão Tử"],
["Mac Thien Tich","Mạc Thiên Tích"],
["Mac Hien Tich","Mạc Hiển Tích"],
["Phu Dong Thien Vuong","Phù Đổng Thiên Vương"],
["Ba Trieu","Bà Triệu"],
["Nguyen Chi Thanh","Nguyễn Chí Thanh"],
["Nguyen An","Nguyễn An"],
["Nguyen Dia Lo","Nguyễn Địa Lô"],
["Nguyen Khoa Dang","Nguyễn Khoa Đăng"],
["Nguyen Quang Bat","Nguyễn Quang Bật"],
["Nguyen Thai duong son","Nguyễn Thái Sơn"],
["Nguyen Trong Quan","Nguyễn Trọng Quản"],
["Pham Huu Chi","Phạm Hữu Chí"],
["Pham Huu Lau","Phạm Hữu Lầu"],
["Pham Huu Tam","Phạm Hữu Tâm"],
["Pho Co Dieu","Phó Cơ Điều"],
["Le Van Luong","Lê Văn Lương"],
["Nguyen Huu Tho","Nguyễn Hữu Thọ"],
["Nguyen Thi Thap","Nguyễn Thị Thập"],
["Phan Huy Thuc","Phan Huy Thực"],
["Tran Xuan duong soan","Trần Xuân duong soạn"],
["Hung Long Nam","Hưng Long Nam"],
["duong D4","Đường D4"],
["duong DD71","Đường DD71"],
["duong DD10","Đường DD10"],
["duong DD12","Đường DD12"],
["duong DD1","Đường DD1"],
["duong DD5","Đường DD5"],
["duong DD6","Đường DD6"],
["duong DD7","Đường DD7"],
["duong D1","Đường D1"],
["Tan Thanh","Tân Thành"],
["Tan Thoi Hiep 22","Tân Thới Hiệp 22"],
["Tan Chanh Hiep 21","Tân Chánh Hiệp 21"],
["Tan Chanh Hiep 7","Tân Chánh Hiệp 7"],
["Tan Chanh Hiep 8","Tân Chánh Hiệp 8"],
["Hiep Thanh 37","Hiệp Thành 37"],
["Ly Thanh Tong","Lý Thánh Tông"],
["Tran Thanh Mai","Trần Thanh Mại"],
["Vu Huy Tan","Vũ Huy Tấn"],
["Vo Thanh Trang","Võ Thành Trang"],
["Truong Hoang Thanh","Trương Hoàng Thanh"],
["Nui Thanh","Núi Thành"],
["Tran Thanh Tong","Trần Thánh Tông"],
["Dat Thanh","Đất Thánh"],
["Tan Huong","Tân Hương"],
["Thanh Cong","Thành Công"],
["Tan duong son Nhi","Tân Sơn Nhì"],
["Tang Bat Ho","Tăng Bạt Hổ"],
["Thuan Kieu","Thuận Kiều"],
["Phan Van Khoe","Phan Văn Khỏe"],
["Phan Van Tri","Phan Văn Trị"],
["Phung Hung","Phùng Hưng"],
["Trinh Hoai Duc","Trịnh Hoài Đức"],
["Vu Chi Hieu","Vũ Chí Hiếu"],
["Luu Chi Hieu","Lưu Chí Hiếu"],
["Vu Duy Chi","Vũ Duy Chí"],
["Vu Tu","Vũ Tụ"],
["To Hieu","Tô Hiệu"],
["Duong Tu Giang","Dương Tử Giang"],
["Hoc Lac","Học Lạc"],
["Ho Hoc Lam","Hồ Học Lãm"],
["To Ky","Tô Ký"],
["Tuyen 2","Tuyến 2"],
["Tran Chanh Chieu","Trần Chánh Chiếu"],
["Tran Thien Chanh","Trần Thiện Chánh"],
["Trang Tu","Trang Tử"],
["Do Ngoc Thanh","Đỗ Ngọc Thạnh"],
["Ha Ton Quyen","Hà Tôn Quyền"],
["Nguyen Thi Ranh","Nguyễn Thị Rành"],
["Le Hong Phong","Lê Hồng Phong"],
["An Duong Vuong","An Dương Vương"],
["Kinh Duong Vuong","Kinh Dương Vương"],
["Ngo Gia Tu","Ngô Gia Tự"],
["lo M chung cu Ngo Gia Tu","lô M chung cư Ngô Gia Tự"],
["lo T chung cu Ngo Gia Tu","lô T chung cư Ngô Gia Tự"],
["lo X chung cu Ngo Gia Tu","lô X chung cư Ngô Gia Tự"],
["lo Y chung cu Ngo Gia Tu","lô Y chung cư Ngô Gia Tự"],
["lo Y-M chung cu Ngo Gia Tu","lô Y-M chung cư Ngô Gia Tự"],
["Huyen Tran Cong Chua","Huyền Trân Công Chúa"],
["Bach Van","Bạch Vân"],
["Pham Van Bach","Phạm Văn Bạch"],
["Bach Ma","Bạch Mã"],
["Ben Bai Say","Bến Bãi Sậy"],
["duong 5","Đường 5"],
["duong D3","Đường D3"],
["Lien Phuong","Liên Phường"],
["Bui Huu Nghia","Bùi Hữu Nghĩa"],
["Nghia Thuc","Nghĩa Thục"],
["Nhieu Tam","Nhiêu Tâm"],
["Nhieu Tu","Nhiêu Tứ"],
["Tam Chau","Tam Châu"],
["Tam Binh","Tam Bình"],
["Tam Ha","Tam Hà"],
["Tran Tuan Khai","Trần Tuấn Khải"],
["Tran Quoc Tuan","Trần Quốc Tuấn"],
["Nguyen Thoi Trung","Nguyễn Thới Trung"],
["Kinh Trung Uong","Kinh Trung Ương"],
["Xuan Thoi duong son - Xuan Thoi Dong","Xuân Thới Sơn-Xuân Thới Đông"],
["Nguyen Van Tao","Nguyễn Văn Tạo"],
["Nguyen Tri Phuong","Nguyễn Tri Phương"],
["Nga Sau Nguyen Tri Phuong","Ngã Sáu Nguyễn Tri Phương"],
["Nguyen Trong Tri","Nguyễn Trọng Trí"],
["Nguyen Van Dung","Nguyễn Văn Dung"],
["Su Van Hanh","Sư Vạn Hạnh"],
["Tran Nhan Ton","Trần Nhân Tôn"],
["Nguyen Dang Dao","Nguyễn Đăng Đạo"],
["Cao Van Lau","Cao Văn Lâu"],
["Cao Van Lau","Cao Văn Lầu"],
["Pham Van Chi","Phạm Văn Chí"],
["Pham Van Chieu","Phạm Văn Chiêu"],
["Khu Dinh Cu Pham Van Chi","Khu Định Cư Phạm Văn Chí"],
["Pham Van Nghi","Phạm Văn Nghị"],
["Pham Van Cheo","Phạm Văn Chèo"],
["Ba Thien","Bà Thiên"],
["Bau Lach","Bàu Lách"],
["Bui Thi Diet","Bùi Thị Điệt"],
["Nguyen Van Binh","Nguyễn Văn Bình"],
["Cu Xa Phu Lam D","Cư Xá Phú Lâm D"],
["Cu Xa Phu Lam","Cư Xá Phú Lâm"],
["lo C-D chung cu An Quang","lô C-D chung cư Ấn Quang"],
["lo D-E chung cu An Quang","lô D-E chung cư Ấn Quang"],
["Cu Xa Phu Lam A","Cư Xá Phú Lâm A"],
["duong so 212","Đường số 212"],
["duong so 215","Đường số 215"],
["duong so 210","Đường số 210"],
["duong so 21D","Đường số 21D"],
["duong so 21A","Đường số 21A"],
["duong so 21B","Đường số 21B"],
["duong so 21C","Đường số 21C"],
["duong so 320","Đường số 320"],
["duong so 32 Tieu khu 1","Đường số 32 Tiểu khu 1"],
["duong so 32B","Đường số 32B"],
["duong so 53A","Đường số 53A"],
["duong so 53C","Đường số 53C"],
["duong so 53D","Đường số 53D"],
["duong so 72A","Đường số 72A"],
["Hau Giang","Hậu Giang"],
["Ly Chieu Hoang","Lý Chiêu Hoàng"],
["Nguyen Van Luong","Nguyễn Văn Luông"],
["Nguyen Van Luong","Nguyễn Văn Lượng"],
["Tran Van Kieu","Trần Văn Kiểu"],
["Cho Lon","Chợ Lớn"],
["Rach Ba Lon","Rạch Bà Lớn"],
["duong so 207","Đường số 207"],
["Ba Hom","Bà Hom"],
["lo A-B chung cu An Quang","lô A-B chung cư Ấn Quang"],
["lo B-C chung cu An Quang","lô B-C chung cư Ấn Quang"],
["Dang Nguyen Can","Đặng Nguyên Cẩn"],
["Tan Hoa Dong","Tân Hòa Đông"],
["Mieu Binh Dong","Miếu Bình Đông"],
["Hoa Binh","Hòa Bình"],
["Dong Den","Đồng Đen"],
["Tan Hoa","Tân Hóa"],
["Tan Hoa 2","Tân Hòa 2"],
["Hoang Van Thai","Hoàng Văn Thái"],
["Hoang Huu Nam","Hoàng Hữu Nam"],
["Lam Hoanh","Lâm Hoành"],
["Hoang Van Hop","Hoàng Văn Hợp"],
["26 Thang 3","26 Tháng 3"],
["Binh Long","Bình Long"],
["Bui Duong Lich","Bùi Dương Lịch"],
["duong M1","Đường M1"],
["Huong Lo 3","Hương Lộ 3"],
["Kenh 19 Thang 5","Kênh 19 Tháng 5"],
["Kenh Nuoc Den","Kênh Nước Đen"],
["Le Trong Tan","Lê Trọng Tấn"],
["Kenh Tan Hoa","Kênh Tân Hoá"],
["Kenh Tan Hoa Bau Cat","Kênh Tân Hóa Bàu Cát"],
["Pham Dinh Ho","Phạm Đình Hổ"],
["Binh Tien","Bình Tiên"],
["Tien Giang","Tiền Giang"],
["Tan Tien","Tân Tiến"],
["Dong Tien","Đồng Tiến"],
["Pham Phu Thu","Phạm Phú Thứ"],
["Pham Van Xao","Phạm Văn Xảo"],
["Le Tuan Mau","Lê Tuấn Mậu"],
["duong noi khu","Đường Nội Khu"],
["Mai Xuan Thuong","Mai Xuân Thường"],
["Mai Xuan Thuong","Mai Xuân Thưởng"],
["Buu Dinh","Bửu Đình"],
["Buu Long","Bửu Long"],
["Doan Cong Buu","Đoàn Công Bửu"],
["Ta Quang Buu","Tạ Quang Bửu"],
["Ben Lo Gom","Bến Lò Gốm"],
["Hem 970 Ben Lo Gom","Hểm 970 Bến Lò Gốm"],
["Minh Phung","Minh Phụng"],
["Nguyen Xuan Phung","Nguyễn Xuân Phụng"],
["Phan Dinh Phung","Phan Đình Phùng"],
["Phung Ta Chu","Phùng Tá Chu"],
["Phung Van Cung","Phùng Văn Cung"],
["Le Quang Sung","Lê Quang Sung"],
["Ba Lai","Bà Lài"],
["Tran Van Thanh","Trần Văn Thành"],
["Truong Van Thanh","Trương Văn Thành"],
["Le Van Viet","Lê Văn Việt"],
["Nguyen Van Tang","Nguyễn Văn Tăng"],
["Nguyen Van Thanh","Nguyễn Văn Thạnh"],
["Vo Van Hat","Võ Văn Hát"],
["Le Van Khuong","Lê Văn Khương"],
["To Ngoc Van","Tô Ngọc Vân"],
["Chu Van An","Chu Văn An"],
["Nguyen Van Dau","Nguyễn Văn Đậu"],
["Ba Ky","Bà Ký"],
["Ben Phu Lam","Bến Phú Lâm"],
["Lam Van Ben","Lâm Văn Bền"],
["duong so 455","Đường số 455"],
["Hiep Thanh 45","Hiệp Thành 45"],
["Ho Huan Nghiep","Hồ Huấn Nghiệp"],
["duong so 475","Đường số 475"],
["Thanh Loc 47","Thạnh Lộc 47"],
["Thanh Xuan 47","Thạnh Xuân 47"],
["Huynh Tan Phat","Huỳnh Tấn Phát"],
["Cong Truong Lam duong son","Công Trường Lam Sơn"],
["Ly Phuc Man","Lý Phục Man"],
["Nguyen Van Duong","Nguyễn Văn Dưỡng"],
["Tan Thuan Tay","Tân Thuận Tây"],
["Chan cau Tan Thuan","Chân cầu Tân Thuận"],
["Chan cau Tan Thuan 2","Chân cầu Tân Thuận 2"],
["Luu Trong Lu","Lưu Trọng Lư"],
["duong so 11N","Đường số 11N"],
["Tan Thuan","Tân Thuận"],
["Tan My","Tân Mỹ"],
["Dao Tri","Đào Trí"],
["Dao Trinh Nhat","Đào Trinh Nhất"],
["duong D5A","Đường D5A"],
["duong D5B","Đường D5B"],
["Hoang Quoc Viet","Hoàng Quốc Việt"],
["Nguyen Luong Bang","Nguyễn Lương Bằng"],
["Phu Thuan","Phú Thuận"],
["Go O Moi","Gò Ô Môi"],
["Khu 2","Khu 2"],
["Dam Thuan Huy","Đàm Thuận Huy"],
["Road 64","Đường số 64"],
["duong O ","Đường O"],
["duong O-","Đường O"],
["duong D11B","Đường D11B"],
["duong D10","Đường D10"],
["duong D11","Đường D11"],
["duong D12","Đường D12"],
["duong D13","Đường D13"],
["duong D14A","Đường D14A"],
["duong D14B","Đường D14B"],
["duong D16","Đường D16"],
["duong so D400","Đường số D400"],
["Be Van Cam","Bế Văn Cấm"],
["Be Van Cam","Bế Văn Cẩm"],
["Be Van Dan","Bế Văn Đàn"],
["Phan Thuc Duyen","Phan Thúc Duyên"],
["Phan Thuc Duyen","Phan Thúc Duyện"],
["Phan Huy Chu","Phan Huy Chú"],
["Bui Bang Doan","Bùi Bằng Đoàn"],
["Cao Trieu Phat","Cao Triều Phát"],
["Do Dang Do","Đỗ Đăng Độ"],
["Ben do Long Dai","Bến đò Long Đại"],
["Do Dang Tuyen","Đỗ Đăng Tuyến"],
["Do Doc Tuyet","Đô Đốc Tuyết"],
["Do Doc Chan","Đô Đốc Chấn"],
["Do Doc Loc","Đô Đốc Lộc"],
["Do Doc Long","Đô Đốc Long"],
["Do Doc Thu","Đô Đốc Thủ"],
["trong nha may Intel","trong nhà máy Intel"],
["duong so 102","Đường số 102"],
["duong so 106","Đường số 106"],
["duong so 278","Đường số 278"],
["Ong Ich Duong","Ông Ích Đường"],
["duong so 27","Đường số 27"],
["duong so 275","Đường số 275"],
["duong so 52A","Đường số 52A"],
["duong so 52B","Đường số 52B"],
["Thanh Xuan 52","Thạnh Xuân 52"],
["duong so 671","Đường số 671"],
["duong so 71","Đường số 71"],
["duong so 79","Đường số 79"],
["Ha Huy Tap","Hà Huy Tập"],
["Gia Phu","Gia Phú"],
["Dong Hung Thuan 3","Đông Hưng Thuận 3"],
["Thu Thiem","Thủ Thiêm"],
["Nha Tho","Nhà Thờ"],
["Cau Thu Thiem","Cầu Thủ Thiêm"],
["Ly Long Tuong","Lý Long Tường"],
["Nguyen Cao-Bac","Nguyễn Cao-Bắc"],
["Nguyen Cao-Nam","Nguyễn Cao-Nam"],
["Pham Thai Buong","Phạm Thái Bường"],
["Phan Khiem Ich","Phan Khiếm Ích"],
["Ong Ich Khiem","Ông Ích Khiêm"],
["Tran Van Tra","Trần Văn Trà"],
["dan cau Rach Chiec","dẫn cầu Rạch Chiếc"],
["duong G","Đường G"],
["Thien Ho Duong","Thiên Hộ Dương"],
["Nguyen Dong Chi","Nguyễn Đổng Chi"],
["Nguyen Thi Bang","Nguyễn Thị Bẳng"],
["Nguyen Thi Ne","Nguyễn Thị Nê"],
["Nguyen Kim Cuong","Nguyễn Kim Cương"],
["Nguyen Thi duong soc","Nguyễn Thị Sóc"],
["My Giang 1A","Mỹ Giang 1A"],
["My Giang 1B","Mỹ Giang 1B"],
["My Giang 2A","Mỹ Giang 2A"],
["My Giang 2B","Mỹ Giang 2B"],
["Tan Chanh Hiep 18","Tân Chánh Hiệp 18"],
["Ta My Duat","Tạ Mỹ Duật"],
["Bui The My","Bùi Thế Mỹ"],
["Thanh My","Thành Mỹ"],
["Nguyen My Ca","Nguyễn Mỹ Ca"],
["Tham My","Thẩm Mỹ"],
["Cong My Phu","Cống Mỹ Phú"],
["Tam Tan","Tam Tân"],
["Trung My","Trung Mỹ"],
["duong so 36A","Đường số 36A"],
["duong so 77","Đường số 77"],
["duong so 85","Đường số 85"],
["Alexandre De Rhodes","Alexandre De Rhodes"],
["Cao Ba Quat","Cao Bá Quát"],
["Cong Truong Me Linh","Công Trường Mê Linh"],
["Le Duan","Lê Duẩn"],
["Nguyen Sieu","Nguyễn Siêu"],
["Bui Van Ba","Bùi Văn Ba"],
["Lu Gia","Lữ Gia"],
["Tran Trong Cung","Trần Trọng Cung"],
["Tran Van Khanh","Trần Văn Khánh"],
["Dong Hung Thuan 2","Đông Hưng Thuận 2"],
["Trung My Tay 14A","Trung Mỹ Tây 14A"],
["Duong Ba Trac","Dương Bá Trạc"],
["Pham The Hien","Phạm Thế Hiển"],
["Khu nha o Thanh Nhat Pham The Hien","Khu nhà ở Thanh Nhật Phạm Thế Hiển"],
["Ba Dinh","Ba Đình"],
["Ben Ba Dinh","Bến Ba Đình"],
["Ben Binh Dong","Bến Bình Đông"],
["Nguyen Quyen","Nguyễn Quyền"],
["Nguyen Trong Quyen","Nguyễn Trọng Quyền"],
["Tung Thien Vuong","Tùng Thiện Vương"],
["Nguyen Che Nghia","Nguyễn Chế Nghĩa"],
["Hoai Thanh","Hoài Thanh"],
["Me Coc","Mễ Cốc"],
["Binh Duc","Bình Đức"],
["Binh Chieu","Bình Chiểu"],


["Dai Lo Doc Lap","Đại Lộ Độc Lập"],
["Le Thi Hoa","Lê Thị Hoa"],
["Ngo Chi Quoc","Ngô Chí Quốc"],
["Hong Duc","Hồng Đức"],
["Luong Van Can","Lương Văn Can"],
["Luu Huu Phuoc","Lưu Hữu Phước"],
["Dai Lo Dong Tay","Đại Lộ Đông Tây"],
["Phu Dinh","Phú Định"],
["Khai Dinh","Khải Định"],
["Dinh Phong Phu","Đình Phong Phú"],
["Duong Dinh Hoi","Dương Đình Hội"],
["Nguyen Dinh Chinh","Nguyễn Đình Chính"],
["Phan Dinh Giot","Phan Đình Giót"],
["Trinh Dinh Thao","Trịnh Đình Thảo"],
["Au Duong Lan","Âu Dương Lân"],
["Da Nam","Dạ Nam"],
["Dang Chat","Đặng Chất"],
["Nguyen Thi Tu","Nguyễn Thị Tú"],
["Nguyen Cuu Phu","Nguyễn Cửu Phú"],
["Nguyen Huu Tri","Nguyễn Hữu Trí"],
["Nguyen Thi Lang","Nguyễn Thị Lắng"],
["394 Ta Quang Buu","394 Tạ Quang Bửu"],
["817 Ta Quang Buu","817 Tạ Quang Bửu"],
["817A Ta Quang Buu","817A Tạ Quang Bửu"],
["882 Ta Quang Buu","882 Tạ Quang Bửu"],
["Ta Quang Buu","Tạ Quang Bửu"],
["Cao Lo","Cao Lỗ"],
["An Phu Tay - Hung Long","An Phú Tây-Hưng Long"],
["duong C5/22","Đường C5/22"],
["duong C7B","Đường C7B"],
["duong C7C","Đường C7C"],
["Khu dan cu HimLam","Khu dân cư HimLam"],
["Lien Ap","Liên Ấp"],
["Quoc lo 50","Quốc lộ 50"],
["duong so 11A","Đường số 11A"],
["Hung Long - Qui Duc","Hưng Long - Qui Đức"],
["Hung Long - Qui Duc","Hưng Long - Quy Đức"],
["Tan Lieu","Tân Liễu"],
["Hung Nhon","Hưng Nhơn"],
["Dong Ho","Đông Hồ"],
["Dang Tien Dong","Đặng Tiến Đông"],
["Linh Dong","Linh Đông"],
["Dong Thanh 2","Đông Thạnh 2"],
["Dong Thanh 3","Đông Thạnh 3"],
["Dong Thanh 4","Đông Thạnh 4"],
["Dong Thanh 5","Đông Thạnh 5"],
["Dong Thanh 6","Đông Thạnh 6"],
["Thoi Dong","Thới Đông"],
["duong so 1 Khu Pham Hung","Đường số 1 Khu Phạm Hùng"],
["duong so 2 Khu Pham Hung","Đường số 2 Khu Phạm Hùng"],
["duong so 3 Khu Pham Hung","Đường số 3 Khu Phạm Hùng"],
["duong so 4 Khu Pham Hung","Đường số 4 Khu Phạm Hùng"],
["duong so 6 Khu Pham Hung","Đường số 6 Khu Phạm Hùng"],
["320A Bong Sao","320A Bông Sao"],
["320B Bong Sao","320B Bông Sao"],
["320 Bong Sao","320 Bông Sao"],
["Bong Sao","Bông Sao"],
["Cay Sao","Cây Sao"],
["Sao Mai","Sao Mai"],
["Bui Huu Dien","Bùi Hữu Diện"],
["Bui Minh Truc","Bùi Minh Trực"],
["Le Truc","Lê Trực"],
["Lien Ap 4-5","Liên Ấp 4-5"],
["Lien Ap 3-4-5","Liên Ấp 3-4-5"],
["Ba To","Ba Tơ"],
["Nguyen Ba Tong","Nguyễn Bá Tòng"],
["Le Quang Kim","Lê Quang Kim"],
["Nguyen Duy Cung","Nguyễn Duy Cung"],
["Vo Tru","Võ Trứ"],
["Vo Van Ngan","Võ Văn Ngân"],
["Vo Thi Hong","Võ Thị Hồng"],
["Vo Van Dieu","Võ Văn Điều"],
["Dan Chu","Dân Chủ"],
["Khong Tu","Khổng Tử"],
["Nhanh cau vuot Quang Trung","Nhánh cầu vượt Quang Trung"],
["Nhom III - KDT Vinh Loc","Nhóm III-KĐT Vĩnh Lộc"],
["Doc Lap","Độc Lập"],
["Truong Van Hai","Trương Văn Hải"],
["Nguyen Xien","Nguyễn Xiển"],
["Phuoc Thien","Phước Thiện"],
["Thien Phuoc","Thiên Phước"],
["Long Thuan","Long Thuận"],
["Hang Tre","Hàng Tre"],
["La Xuan Oai","Lã Xuân Oai"],
["Ho Van Tang","Hồ Văn Tăng"],
["Lang Tang Phu","Làng Tăng Phú"],
["Tang Nhon Phu","Tăng Nhơn Phú"],
["Tam Da","Tam Đa"],
["Tam Dao","Tam Đảo"],
["Tam Dat","Tâm Đạt"],
["Dang Thuc Vinh","Đặng Thúc Vịnh"],
["Truong Luu","Trường Lưu"],
["Luu Xuan Tin","Lưu Xuân Tín"],
["Luu Quy Ky","Lưu Quý Kỳ"],
["Ba Hat","Bà Hạt"],
["Hat Giang","Hát Giang"],
["duong so 836","Đường số 836"],
["duong so 990","Đường số 990"],
["Go Cat","Gò Cát"],
["Ngo Sy Lien","Ngô Sỹ Liên"],
["Lien Khu 2-5","Liên Khu 2-5"],
["Lien Khu 8-9","Liên Khu 8-9"],
["Lien Khu 4-5","Liên Khu 4-5"],
["Lien Khu 5-6","Liên Khu 5-6"],
["Lien khu 10-11","Liên khu 10-11"],
["Lien Khu 1-6","Liên Khu 1-6"],
["Lien Khu 16-18","Liên Khu 16-18"],
["Ni Su Huynh Lien","Ni Sư Huỳnh Liên"],
["Lien to 40-43","Liên tổ 40-43"],
["Vanh Dai 2","Vành Đai 2"],
["Vo Cong Ton","Võ Công Tồn"],
["Dai Lo 2","Đại Lộ 2"],
["Dai Lo 3","Đại Lộ 3"],
["Trung My Tay 18A","Trung Mỹ Tây 18A"],
["duong so 6B","Đường số 6B"],
["duong so 6C","Đường số 6C"],
["Dinh Cung Vien","Đinh Củng Viên"],
["duong so 109","Đường số 109"],
["duong so 99","Đường số 99"],
["Ho Ba Phan","Hồ Bá Phấn"],
["Phan Ba Phien","Phan Bá Phiến"],
["Phan Van Doi","Phan Văn Đối"],
["Nam Hoa","Nam Hòa"],
["Tay Hoa","Tây Hòa"],
["Hoang Tang Bi","Hoàng Tăng Bí"],
["Hoang Dao Thuy","Hoàng Đạo Thúy"],
["Thuy Loi","Thủy Lợi"],
["Thuy Loi ap 04","Thủy Lợi ấp 04"],
["De Thuy Loi Ap 3","Đê Thủy Lợi Ấp 3"],
["339","339"],
["Hi-Tech Park","Hi-Tech Park"],
["Khu Canh Ve","Khu Cảnh Vệ"],
["Man Thien","Man Thiện"],
["Cho Cau Chuoi","Chợ Cầu Chuối"],
["duong so 100","Đường số 100"],
["duong so 138","Đường số 138"],
["Nam Cao","Nam Cao"],
["Lo Lu","Lò Lu"],
["Ho Thi Ky","Hồ Thị Kỷ"],
["Tan Phuoc","Tân Phước"],
["Truong Phuoc Phan","Trương Phước Phan"],
["Doan Hong Phuoc","Đoàn Hồng Phước"],
["Tran Minh Quyen","Trần Minh Quyền"],
["Do Quyen","Đỗ Quyên"],
["Hoa Hung","Hòa Hưng"],
["duong M10","Đường M10"],
["duong M12","Đường M12"],
["duong M14","Đường M14"],
["duong M3","Đường M3"],
["duong M4","Đường M4"],
["duong M5","Đường M5"],
["duong M6","Đường M6"],
["duong M7","Đường M7"],
["duong M8","Đường M8"],
["Hoang Du Khuong","Hoàng Dư Khương"],
["Thanh Thai","Thành Thái"],
["Bui Quoc Thai","Bùi Quốc Thái"],
["To Hien Thanh","Tô Hiến Thành"],
["Thien Giang","Thiên Giang"],
["Dinh Duc Thien","Đinh Đức Thiện"],
["Tan Tuc","Tân Túc"],
["Tran Dai Nghia","Trần Đại Nghĩa"],
["Bac Hai","Bắc Hải"],
["Ly Thuong Kiet","Lý Thường Kiệt"],
["Nguyen Ngoc Loc","Nguyễn Ngọc Lộc"],
["Ba Vi","Ba Vì"],
["Cuu Long","Cửu Long"],
["Mac Cuu","Mạc Cửu"],
["Dong Nai","Đồng Nai"],
["Ho Ba Kien","Hồ Bá Kiện"],
["Ba Thau","Bà Thau"],
["Huynh Ba Chanh","Huỳnh Bá Chánh"],
["Hong Linh","Hồng Lĩnh"],
["Huong Giang","Hương Giang"],
["Giang Huong","Giáng Hương"],
["Nguyen Gian Thanh","Nguyễn Giản Thanh"],
["Nguyen Tu Gian","Nguyễn Tư Giản"],
["That duong son","Thất Sơn"],
["Truong duong son","Trường Sơn"],
["Truong Chinh","Trường Chinh"],
["Truong Van Linh","Trương Vân Lĩnh"],
["Vinh Vien","Vĩnh Viễn"],
["Nhat Tao","Nhật Tảo"],
["Dao Duy Tu","Đào Duy Từ"],
["Nguyen Tieu La","Nguyễn Tiểu La"],
["Nguyen Kim","Nguyễn Kim"],
["Nguyen Lam","Nguyễn Lâm"],
["Nguyen Nhu Lam","Nguyễn Nhữ Lãm"],
["Le Dai Hanh","Lê Đại Hành"],
["Han Hai Nguyen","Hàn Hải Nguyên"],
["Lac Long Quan","Lạc Long Quân"],
["Le Thi Bach Cat","Lê Thị Bạch Cát"],
["Phu Tho","Phú Thọ"],
["Phu Tho Hoa","Phú Thọ Hòa"],
["Thoai Ngoc Hau","Thoại Ngọc Hầu"],
["Dinh Liet","Đinh Liệt"],
["Do Duc Duc","Đỗ Đức Dục"],
["Hoang Ngoc Phach","Hoàng Ngọc Phách"],
["Le Canh Tuan","Lê Cảnh Tuấn"],
["Le Dai","Lê Đại"],
["Le Lang","Lê Lăng"],
["Le Lu","Lê Lư"],
["Le Quoc Trinh","Lê Quốc Trinh"],
["Binh Thoi","Bình Thới"],
["Tan Thoi Nhat 1","Tân Thới Nhất 1"],
["Tan Thoi Nhat 8","Tân Thới Nhất 8"],
["Thoi Hoa","Thới Hòa"],
["Doi Cung","Đội Cung"],
["Lanh Binh Thang","Lãnh Binh Thăng"],
["Do Van Suu","Đỗ Văn Sửu"],
["duong song Suoi","Sông Suối"],
["Hoa Su","Hoa Sứ"],
["Cong Chua Ngoc Han","Công Chúa Ngọc Hân"],
["Lo Sieu","Lò Siêu"],
["Tue Tinh","Tuệ Tĩnh"],
["Tong Lung","Tổng Lung"],
["Au Co","Âu Cơ"],
["Phan Xich Long","Phan Xich Long"],
["Phan Xich Long","Phan Xích Long"],
["Thai Phien","Thái Phiên"],
["Duong Dinh Nghe","Dương Đình Nghệ"],
["Tan Khai","Tân Khai"],
["Dinh Tan Khai","Đình Tân Khai"],
["Tran Quy Cap","Trần Quý Cáp"],
["Tong Van Tran","Tống Văn Trân"],
["Tong Van Hien","Tống Văn Hiên"],
["Trinh Dinh Trong","Trịnh Đình Trọng"],
["Ly Nam De","Lý Nam Đế"],
["An Phu Dong 1","An Phú Đông 1"],
["An Phu Dong 10","An Phú Đông 10"],
["An Phu Dong 12","An Phú Đông 12"],
["An Phu Dong 13","An Phú Đông 13"],
["An Phu Dong 27","An Phú Đông 27"],
["An Phu Dong 3","An Phú Đông 3"],
["An Phu Dong 9","An Phú Đông 9"],
["Bo huu duong song Sai Gon","Bờ hữu sông Sài Gòn"],
["Thanh Loc 13","Thạnh Lộc 13"],
["Thanh Loc 14","Thạnh Lộc 14"],
["Vuon Lai","Vườn Lài"],
["Dong Hung Thuan 27","Đông Hưng Thuận 27"],
["Phu Dong","Phù Đổng"],
["Quoc lo 1A","Quốc lộ 1A"],
["Vuon Lan","Vườn Lan"],
["Vuon Thom","Vườn Thơm"],
["Dong Hung Thuan 10","Đông Hưng Thuận 10"],
["Dong Hung Thuan 10B","Đông Hưng Thuận 10B"],
["Dong Hung Thuan 11","Đông Hưng Thuận 11"],
["Dong Hung Thuan 13","Đông Hưng Thuận 13"],
["Dong Hung Thuan 14B","Đông Hưng Thuận 14B"],
["Dong Hung Thuan 15","Đông Hưng Thuận 15"],
["Dong Hung Thuan 16","Đông Hưng Thuận 16"],
["Dong Hung Thuan 17","Đông Hưng Thuận 17"],
["Dong Hung Thuan 18","Đông Hưng Thuận 18"],
["Dong Hung Thuan 19","Đông Hưng Thuận 19"],
["Dong Hung Thuan 20","Đông Hưng Thuận 20"],
["Dong Hung Thuan 21","Đông Hưng Thuận 21"],
["Dong Hung Thuan 22","Đông Hưng Thuận 22"],
["Dong Hung Thuan 23","Đông Hưng Thuận 23"],
["Dong Hung Thuan 30","Đông Hưng Thuận 30"],
["Dong Hung Thuan 5","Đông Hưng Thuận 5"],
["Dong Hung Thuan 8","Đông Hưng Thuận 8"],
["Dong Hung Thuan","Đông Hưng Thuận"],
["Nguyen Van Chiem","Nguyễn Văn Chiêm"],
["Tran Quang Qua","Trần Quang Quá"],
["Bui Van Ngu","Bùi Văn Ngữ"],
["Thap Muoi","Tháp Mười"],
["Hiep Thanh 11","Hiệp Thành 11"],
["Hiep Thanh 12","Hiệp Thành 12"],
["Hiep Thanh 13","Hiệp Thành 13"],
["Hiep Thanh 16","Hiệp Thành 16"],
["Hiep Thanh 17","Hiệp Thành 17"],
["Hiep Thanh 18","Hiệp Thành 18"],
["Hiep Thanh 19","Hiệp Thành 19"],
["Hiep Thanh 22","Hiệp Thành 22"],
["Hiep Thanh 23","Hiệp Thành 23"],
["Hiep Thanh 26","Hiệp Thành 26"],
["Hiep Thanh 27","Hiệp Thành 27"],
["Hiep Thanh 31","Hiệp Thành 31"],
["Hiep Thanh 35","Hiệp Thành 35"],
["Tan Chanh Hiep 10","Tân Chánh Hiệp 10"],
["Tan Thoi Hiep 10","Tân Thới Hiệp 10"],
["Hiep Thanh 1","Hiệp Thành 1"],
["Hiep Thanh 2","Hiệp Thành 2"],
["Bach Duong","Bạch Dương"],
["duong D5","Đường D5"],
["duong D6","Đường D6"],
["Hai Au","Hải Âu"],
["Tan Chanh Hiep 13","Tân Chánh Hiệp 13"],
["Tan Thoi Hiep 13","Tân Thới Hiệp 13"],
["Quoc Lo 13","Quốc Lộ 13"],
["Tan Chanh Hiep 17","Tân Chánh Hiệp 17"],
["Thanh Loc 17","Thạnh Lộc 17"],
["Phan Van Han","Phan Văn Hân"],
["Thanh Loc 18","Thạnh Lộc 18"],
["Tan Chanh Hiep 26","Tân Chánh Hiệp 26"],
["Thanh Loc 26","Thạnh Lộc 26"],
["Nguyen Xi","Nguyễn Xí"],
["Tam Vu","Tầm Vu"],
["duong thep moi","Thép Mới"],
["Bui Dinh Tuy","Bùi Đình Túy"],
["Dinh Bo Linh","Đinh Bộ Lĩnh"],
["Tan Chanh Hiep 35","Tân Chánh Hiệp 35"],
["Hiep Thanh 6","Hiệp Thành 6"],
["duong so 6 Khu Hiep An","Đường số 6 Khu Hiệp Ân"],
["Nguyen Anh Thu","Nguyễn Ảnh Thủ"],
["Tan Thoi Hiep 15","Tân Thới Hiệp 15"],
["Tan Thoi Hiep 21","Tân Thới Hiệp 21"],
["Tan Thoi Hiep 7","Tân Thới Hiệp 7"],
["Tan Thoi Hiep 20","Tân Thới Hiệp 20"],
["duong Tan Thoi Hiep","Tân Thới Hiệp"],
["Le Duc Tho","Lê Đức Thọ"],
["KP2", "Khu phố 2"],
["Thoi An 4","Thới An 4"],
["Thoi Tay Tan Hiep","Thới Tây Tân Hiệp"],
["Tuyen 7 Tan Thoi duong son","Tuyến 7 Tân Thới Sơn"],
["Bui Thi He","Bùi Thị He"],
["Tran Thi Ngan","Trần Thị Ngần"],
["Huynh Dinh Hai","Huỳnh Đình Hai"],
["Huynh Thi Phuong","Huỳnh Thị Phương"],
["Nguyen Thi Huynh","Nguyễn Thị Huỳnh"],
["Bui Lam","Bùi Lâm"],
["Tan Chanh Hiep 16","Tân Chánh Hiệp 16"],
["Tan Chanh Hiep 24","Tân Chánh Hiệp 24"],
["Tan Chanh Hiep 25","Tân Chánh Hiệp 25"],
["Tan Chanh Hiep 33","Tân Chánh Hiệp 33"],
["Tan Chanh Hiep 34","Tân Chánh Hiệp 34"],
["Tan Chanh Hiep 36","Tân Chánh Hiệp 36"],
["Tan Chanh Hiep 4","Tân Chánh Hiệp 4"],
["Tan Chanh Hiep 5","Tân Chánh Hiệp 5"],
["Quoc lo 22","Quốc lộ 22"],
["Can Thanh","Cần Thạnh"],
["Tan Thoi Nhat 13","Tân Thới Nhất 13"],
["Tan Thoi Nhat 21","Tân Thới Nhất 21"],
["Thoi An 21","Thới An 21"],
["Thoi An 22","Thới An 22"],
["Tan Thoi Nhat 6","Tân Thới Nhất 6"],
["Thoi An 6","Thới An 6"],
["Tan Thoi Nhat 11","Tân Thới Nhất 11"],
["Tan Thoi Nhat 12","Tân Thới Nhất 12"],
["Tan Thoi Nhat 13B","Tân Thới Nhất 13B"],
["Tan Thoi Nhat 14","Tân Thới Nhất 14"],
["Tan Thoi Nhat 15","Tân Thới Nhất 15"],
["Tan Thoi Nhat 17","Tân Thới Nhất 17"],
["Tan Thoi Nhat 18","Tân Thới Nhất 18"],
["Tan Thoi Nhat 1B","Tân Thới Nhất 1B"],
["duong A3","Đường A3"],
["duong C1","Đường C1"],
["duong C4","Đường C4"],
["Tan Thoi Nhat 25","Tân Thới Nhất 25"],
["Tan Thoi Nhat 2","Tân Thới Nhất 2"],
["Tan Thoi Nhat 3","Tân Thới Nhất 3"],
["Tan Thoi Nhat 4","Tân Thới Nhất 4"],
["Tan Thoi Nhat 5","Tân Thới Nhất 5"],
["Ha Huy Giap","Hà Huy Giáp"],
["Thanh Loc 15","Thạnh Lộc 15"],
["Thanh Loc 16","Thạnh Lộc 16"],
["Thanh Loc 19","Thạnh Lộc 19"],
["Thanh Loc 27","Thạnh Lộc 27"],
["Thanh Loc 29","Thạnh Lộc 29"],
["Thanh Loc 31","Thạnh Lộc 31"],
["Thanh Loc 48","Thạnh Lộc 48"],
["Ly Dao Thanh","Lý Đạo Thành"],
["Me Linh","Mê Linh"],
["Thanh Xuan 22","Thạnh Xuân 22"],
["Ngo Tat To","Ngô Tất Tố"],
["Thanh Xuan 37","Thạnh Xuân 37"],
["duong so 41","Đường số 41"],
["Thanh Xuan 48","Thạnh Xuân 48"],
["Binh Quoi","Bình Quới"],
["Thanh Da","Thanh Đa"],
["duong C27","Đường C27"],
["duong TX 38","Đường  TX 38"],
["duong so 21","Đường số 21"],
["Thanh Xuan 13","Thạnh Xuân 13"],
["Binh Loi","Bình Lợi"],
["Thanh Xuan 14","Thạnh Xuân 14"],
["Bach Dang","Bạch Đằng"],
["Nguyen Khuyen","Nguyễn Khuyến"],
["Thanh Xuan 21","Thạnh Xuân 21"],
["QL 22","QL 22"],
["Thanh Xuan 25","Thạnh Xuân 25"],
["Thoi An 10","Thới An 10"],
["Thoi An 11","Thới An 11"],
["Thoi An 12","Thới An 12"],
["Thoi An 15","Thới An 15"],
["Thoi An 16","Thới An 16"],
["Thoi An 17A","Thới An 17A"],
["Thoi An 17","Thới An 17"],
["Thoi An 18","Thới An 18"],
["Thoi An 19A","Thới An 19A"],
["Thoi An 19","Thới An 19"],
["Thoi An 20","Thới An 20"],
["Thoi An 29","Thới An 29"],
["Thoi An 32","Thới An 32"],
["Thoi An 35","Thới An 35"],
["Thoi An 5","Thới An 5"],
["Chau Thoi","Châu Thới"],
["Tuyen 11/2004 Xuan Thoi Thuong","Tuyến 11/2004 Xuân Thới Thượng"],
["Xo Viet Nghe Tinh","Xô Viết Nghệ Tĩnh"],
["Huynh Van Co","Huỳnh Văn Cọ"],
["Ha Chuong","Hà Chương"],
["Ha Dac","Hà Đặc"],
["Dac Lo","Đắc Lộ"],
["Ho Dac Di","Hồ Đắc Di"],
["Trung My Tay\ 16","Trung Mỹ Tây 16"],
["Trung My Tay\ 2A","Trung Mỹ Tây 2A"],
["Trung My Tay\ 1","Trung Mỹ Tây 1"],
["Trung My Tay\ 2","Trung Mỹ Tây 2"],
["Trung My Tay\ 3","Trung Mỹ Tây 3"],
["Trung My Tay\ 5","Trung Mỹ Tây 5"],
["Trung My Tay\ 6A","Trung Mỹ Tây 6A"],
["Trung My Tay\ 8","Trung Mỹ Tây 8"],
["Trung My Tay\ 9A","Trung Mỹ Tây 9A"],
["Bui Chu","Bùi Chu"],
["Dong Tam","Đồng Tâm"],
["duong T13A","Đường T13A"],
["duong T37","Đường T37"],
["Duong Van Hanh","Dương Vạn Hạnh"],
["xa lo Ha Noi","Xa Lộ Hà Nội"],
["Ha Noi","Hà Nội"],
["Quan Tre","Quán Tre"],
["Thuong Mai","Thương Mại"],
["Trung My 9","Trung Mỹ 9"],
["Trung Vuong 1","Trưng Vương 1"],
["Trung Vuong 2","Trưng Vương 2"],
["Bui Tu Toan","Bùi Tư Toàn"],
["Bui Tu Toan","Bùi Tự Toàn"],
["duong so 1A","Đường số 1A"],
["duong so 2D","Đường số 2D"],
["lien xa","liên xã"],
["Le Co","Lê Cơ"],
["Le Cong Phep","Lê Công Phép"],
["Cong kenh B","Cống kênh B"],
["Le Tan Be","Lê Tấn Bê"],
["Ngo Be","Ngô Bệ"],
["Nguyen Quy Yem","Nguyễn Quý Yêm"],
["Ten Lua","Tên Lửa"],
["Do Nang Te","Đỗ Năng Tế"],
["Duong Ba Cung","Dương Bá Cung"],
["Rach Cung","Rạch Cùng"],
["Nguyen Ngoc Cung","Nguyễn Ngọc Cung"],
["duong so 4C","Đường số 4C"],
["Khieu Nang Tinh","Khiếu Năng Tĩnh"],
["Nguyen Thuc Tu","Nguyễn Thức Tự"],
["Nguyen Thuc Duong","Nguyễn Thức Đường"],
["Nga Sau","Ngã Sáu"],
["Ba thang Hai","Đường 3 tháng 2"],
["Lam Vien","Lâm Viên"],
["Long duong son","Long Sơn"],
["Tan Quy","Tân Quý"],
["Ap Chien Luoc","Ấp Chiến Lược"],
["Chien Luoc","Chiến Lược"],
["Chien Thang","Chiến Thắng"],
["Ap Bac","Ấp Bắc"],
["duong so 16A","Đường số 16A"],
["duong so 1C","Đường số 1C"],
["Go Xoai","Gò Xoài"],
["Mieu Go Xoai","Miếu Gò Xoài"],
["Dong Xoai","Đồng Xoài"],
["Le Van Quoi","Lê Văn Quới"],
["duong C10","Đường C10"],
["duong C11","Đường C11"],
["duong C12","Đường C12"],
["duong C1A","Đường C1A"],
["duong C2A","Đường C2A"],
["duong C4A","Đường C4A"],
["duong C5A","Đường C5A"],
["duong so 1 Khu Hiep An","Đường số 1 Khu Hiệp Ân"],
["duong so 2 Khu Hiep An","Đường số 2 Khu Hiệp Ân"],
["duong so 4 Khu Hiep An","Đường số 4 Khu Hiệp Ân"],
["Mai Am","Mai Am"],
["Lo Tu","Lô Tư"],
["Dien Hong","Diên Hồng"],
["Ngo Nhan Tinh","Ngô Nhân Tịnh"],
["Vu Tung","Vũ Tùng"],
["Yen Do","Yên Đỗ"],
["Nguyen Hong","Nguyên Hồng"],
["No Trang Long","Nơ Trang Long"],
["Cay Cam","Cây Cám"],
["Cay Tram","Cây Trâm"],
["Ho Van Long","Hồ Văn Long"],
["Bui Van Su","Bùi Văn Sự"],
["Nguyen Van Manh","Nguyễn Văn Mạnh"],
["Huong Lo 80B","Hương Lộ 80B"],
["Huong Lo 80","Hương Lộ 80"],
["Dat Moi","Đất Mới"],
["Dinh Nghi Xuan","Đình Nghi Xuân"],
["Huong Lo 2","Hương Lộ 2"],
["Phan Anh","Phan Anh"],
["Ao Doi","Ao Đôi"],
["lang khu 6","làng khu 6"],
["Tay Lan","Tây Lân"],
["Che Lan Vien","Chế Lan Viên"],
["Lang The","Láng The"],
["Le Thuong","Lê Thương"],
["Le Hung Yen","Lê Hùng Yên"],
["Le Trong Man","Lê Trọng Mẫn"],
["Lo Te","Lộ Tẻ"],
["Nguyen Cuu Dam","Nguyễn Cửu Đàm"],
["Ap 1","Ấp 1"],
["Bia Truyen Thong","Bia Truyền Thống"],
["Bo Tuyen","Bờ Tuyến"],
["dan vao cao toc","dẫn vào cao tốc"],
["Nguyen Trieu Luat","Nguyễn Triệu Luật"],
["Nguyen Bac","Nguyễn Bặc"],
["Bac Ai","Bác Ái"],
["Yen Do","Yên Đổ"],
["Cu Xa Yen Do","Cư Xá Yên Đổ"],
["Nguyen Hong Dao","Nguyễn Hồng Đào"],
["Tan Kien - Binh Loi","Tân Kiên-Bình Lợi"],
["Nguyen Trong Loi","Nguyễn Trọng Lội"],
["An Ha","An Hạ"],
["Cong Truong Hoa Binh","Công Trường Hòa Bình"],
["Cong Hoa","Cộng Hòa"],
["Luong Ngoc Quyen","Lương Ngọc Quyến"],
["Nguyen Huy Luong","Nguyễn Huy Lượng"],
["Tran Van Ky","Trần Văn Kỷ"],
["Phan Huy On","Phan Huy Ôn"],
["Phan Huy Ich","Phan Huy Ích"],
["Ung Van Khiem","Ung Văn Khiêm"],
["Nguyen Ngoc Phuong","Nguyễn Ngọc Phương"],
["Nguyen Ngoc Nhut","Nguyễn Ngọc Nhựt"],
["Nguyen Van Ngoc","Nguyễn Văn Ngọc"],
["Nguyen Van Lac","Nguyễn Văn Lạc"],
["Dong Da","Đống Đa"],
["Dang Thi Ranh","Đặng Thị Rành"],
["Vo Duy Ninh","Võ Duy Ninh"],
["Dang Nghiem","Đặng Nghiêm"],
["Phan Dat Duc","Phan Đạt Đức"],
["Van Kiep","Vạn Kiếp"],
["Quach Vu","Quách Vũ"],
["Vu Trong Phung","Vũ Trọng Phụng"],
["Hoang Hoa Tham","Hoàng Hoa Thám"],
["Lam duong son","Lam Sơn"],
["Nguyen Van Nghi","Nguyễn Văn Nghi"],
["Truong Dang Que","Trương Đăng Quế"],
["Dang Van Bi","Đặng Văn Bi"],
["Nguyen Oanh","Nguyễn Oanh"],
["Thong Nhat","Thống Nhất"],
["Thong Tay Hoi","Thông Tây Hội"],
["Suoi Loi","Suối Lội"],
["Le Minh Nhut","Lê Minh Nhựt"],
["Le Thi Sieng","Lê Thị Siêng"],
["Lieu Binh Huong","Liêu Bình Hương"],
["Ngo Tri Hoa","Ngô Tri Hoá"],
["Le Van Tho","Lê Văn Thọ"],
["Le Van Phan","Lê Văn Phan"],
["Nguyen Dinh Khoi","Nguyễn Đình Khơi"],
["Bui Quang La","Bùi Quang Là"],
["Do Thuc Tinh","Đỗ Thúc Tịnh"],
["Huynh Van Nghe","Huỳnh Văn Nghệ"],
["Nguyen Do Cung","Nguyễn Đỗ Cung"],
["Tan duong son Hoa","Tân Sơn Hòa"],
["Tan duong son Nhat","Tân Sơn Nhất"],
["Tan duong son","Tân Sơn"],
["duong son Hung","Sơn Hùng"],
["duong son Cang","Sơn Cang"],
["duong song Day","Sông Đáy"],
["duong song Da","Sông Đà"],
["duong song Nhue","Sông Nhuệ"],
["duong song Thao","Sông Thao"],
["duong song Thuong","Sông Thương"],
["Do duong son","Đồ Sơn"],
["Tran Tan","Trần Tấn"],
["An Hoi","An Hội"],
["Nguyen Hoi","Nguyễn Hội"],
["Ba Lang","Ba Lăng"],
["Bau Tre","Bàu Tre"],
["Dang Chiem","Đặng Chiêm"],
["Do Ngoc Du","Đỗ Ngọc Du"],
["Giap Hai","Giáp Hải"],
["Nguyen Van Hoai","Nguyễn Văn Hoài"],
["Tuyen N2","Tuyến N2"],
["An Nhon","An Nhơn"],
["An Nhon Tay","An Nhơn Tây"],
["Ly Nhon","Lý Nhơn"],
["Ben Dinh","Bến Đình"],
["Cay Go","Cây Gõ"],
["Goc Chang","Góc Chàng"],
["Nhuan Duc","Nhuận Đức"],
["Tinh Lo 15","Tỉnh Lộ 15"],
["Tinh Lo 7","Tỉnh Lộ 7"],
["Le Hoang Phai","Lê Hoàng Phái"],
["Le Thi Hong","Lê Thị Hồng"],
["Hanh Thong","Hạnh Thông"],
["Nguyen Kiem","Nguyễn Kiệm"],
["Nguyen Tuan","Nguyễn Tuân"],
["Nguyen Pham Tuan","Nguyễn Phạm Tuân"],
["Nguyen Ba Tuan","Nguyễn Bá Tuân"],
["Nguyen Van Bao","Nguyễn Văn Bảo"],
["Duong Quang Ham","Dương Quảng Hàm"],
["Nguyen An Khuong","Nguyễn An Khương"],
["Tran Ba Giao","Trần Bá Giao"],
["Pham Huy Thong","Phạm Huy Thông"],
["Tran Thi Nghi","Trần Thị Nghỉ"],
["Tu Mo","Tú Mỡ"],
["Doan Thi Diem","Đoàn Thị Điểm"],
["Dang Van Ngu","Đặng Văn Ngữ"],
["Huynh Van Banh","Huỳnh Văn Bánh"],
["Banh Van Tran","Bành Văn Trân"],
["Huynh Van Chinh","Huỳnh Văn Chính"],
["Nguyen Van Troi","Nguyễn Văn Trỗi"],
["Tran Huu Trang","Trần Hữu Trang"],
["Truong Quoc Dung","Trương Quốc Dung"],
["Ho Bieu Chanh","Hồ Biểu Chánh"],
["duong T12","T12"],
["Binh Truong","Bình Trường"],
["Bo Kinh","Bờ Kinh"],
["Bo kinh T12","Bờ kinh T12"],
["Bo Nha Tho","Bờ Nhà Thờ"],
["Tran Huy Lieu","Trần Huy Liệu"],
["Duy Tan","Duy Tân"],
["Tong Duy Tan","Tống Duy Tân"],
["Le Duy Nhuan","Lê Duy Nhuận"],
["Hoang Van Thu","Hoàng Văn Thụ"],
["Cu Lao","Cù Lao"],
["Hoa Dao","Hoa Đào"],
["vao Dao Khi","vào Đảo Khỉ"],
["Hoa Hong","Hoa Hồng"],
["Hoa Lan","Hoa Lan"],
["Ca Lang","Cá Lăng"],
["Hoa Mai","Hoa Mai"],
["Hoa My","Hòa Mỹ"],
["Tran Hoa","Trần Hòa"],
["Tran Xuan Hoa","Trần Xuân Hòa"],
["Dinh Hoa","Đinh Hòa"],
["Hoa Sua","Hoa Sữa"],
["Hoa Cau","Hoa Cau"],
["Le Tu Tai","Lê Tự Tài"],
["An Tai","An Tài"],
["Tai Thiet","Tái Thiết"],
["Hoa Cuc","Hoa Cúc"],
["Duong Dinh Cuc","Dương Đình Cúc"],
["Hoa Hue","Hoa Huệ"],
["Hoang Thieu Hoa","Hoàng Thiều Hoa"],
["Huynh Thien Loc","Huỳnh Thiện Lộc"],
["Le Thiet","Lê Thiệt"],
["Huynh Thien Loc","Huỳnh Thiên Lộc"],
["Nguyen Cong Hoan","Nguyễn Công Hoan"],
["Phan Tay Ho","Phan Tây Hồ"],
["Tran Ke Xuong","Trần Kế Xương"],
["Le Van Them","Lê Văn Thêm"],
["Dao Duy Anh","Đào Duy Anh"],
["Do Tan Phong","Đỗ Tấn Phong"],
["Ho Van Hue","Hồ Văn Huê"],
["Hoang Minh Giam","Hoàng Minh Giám"],
["Hong Ha","Hồng Hà"],
["Pho Quang","Phổ Quang"],
["Binh Gia","Bình Giã"],
["Giai Phong","Giải Phóng"],
["Ba Gia","Ba Gia"],
["Hiep Nhat","Hiệp Nhất"],
["Nhat Linh","Nhất Linh"],
["Pham Van Hai","Phạm Văn Hai"],
["Tan Canh","Tân Cảnh"],
["Nguyen Canh Di","Nguyễn Cảnh Dị"],
["Go Cam Dem","Gò Cẩm Đệm"],
["Hong Lac","Hồng Lạc"],
["Lac Hong","Lạc Hồng"],
["Tan Trang","Tân Trang"],
["Thai Thi Nhan","Thái Thị Nhạn"],
["Tran Van Quang","Trần Văn Quang"],
["Bau Cat","Bàu Cát"],
["Bau Cat 4","Bàu Cát 4"],
["Bau Cat 6","Bàu Cát 6"],
["Bau Cat 7","Bàu Cát 7"],
["Bau Cat 9","Bàu Cát 9"],
["Bau Cat 1","Bàu Cát 1"],
["Bau Cat 2","Bàu Cát 2"],
["Bau Cat 3","Bàu Cát 3"],
["Bau Cat 5","Bàu Cát 5"],
["Truong Mam non Bau Cat","Trường Mầm non Bàu Cát"],
["Bay Hien","Bảy Hiền"],
["Le Trung Nghia","Lê Trung Nghĩa"],
["Nam Chau","Năm Châu"],
["Phan Sao Nam","Phan Sào Nam"],
["Tran Mai Ninh","Trần Mai Ninh"],
["Ben Cat","Bến Cát"],
["Cong Hoa 3","Cộng Hòa 3"],
["Hoang Ke Vien","Hoàng Kế Viên"],
["Le Ngan","Lê Ngân"],
["Nguyen Tu Nha","Nguyễn Tử Nha"],
["Dao Tong Nguyen","Đào Tông Nguyên"],
["Quach Van Tuan","Quách Văn Tuấn"],
["Trung Lang","Trung Lang"],
["Xuan Dieu","Xuân Diệu"],
["Xuan Hong","Xuân Hồng"],
["Bau Bang","Bầu Bàng"],
["Le Tan Quoc","Lê Tấn Quốc"],
["Le Than","Lê Thận"],
["Le Lieu","Lê Liễu"],
["ap rang","Ấp Ràng"],
["Le Sat","Lê Sát"],
["Mai Lao Bang","Mai Lão Bạng"],
["Nguyen Chanh Sat","Nguyễn Chánh Sắt"],
["Ben do Vam Sat-Tan Tap","Bến đò Vàm Sát-Tân Tập"],
["Phan Van Suu","Phan Văn Sửu"],
["Than Nhan Trung","Thân Nhân Trung"],
["Ba Van","Ba Vân"],
["Truong Van Ba","Trương Văn Ba"],
["Cong Lo","Cống Lở"],
["Bui Cong Trung","Bùi Công Trừng"],
["Cong Ba Thon","Cống Bà Thôn"],
["Duong Cong Khi","Dương Công Khi"],
["Nu Dan Cong","Nữ Dân Công"],
["Cong Nghe","Công Nghệ"],
["Hoang Bat Dat","Hoàng Bật Đạt"],
["Nguyen Phuc Chu","Nguyễn Phúc Chu"],
["Nguyen Sy Sach","Nguyễn Sỹ Sách"],
["Tan Tru","Tân Trụ"],
["Cong Cai Trung","Cống Cái Trung"],
["Trung Tam","Trung Tâm"],
["Tran Thai Tong","Trần Thái Tông"],
["Huynh Lan Khanh","Huỳnh Lan Khánh"],
["Ngo Thu Minh","Ngô Thu Minh"],
["Pham Phu Tiet","Phạm Phú Tiết"],
["Xom Day","Xóm Đầy"],
["Nguyen duong son","Nguyễn Sơn"],
["Hoa Bang","Hoa Bằng"],
["Tan Vien","Tản Viên"],
["Tra Khuc","Trà Khúc"],
["Tran Quoc Hoan","Trần Quốc Hoàn"],
["Yen The","Yên Thế"],
["Hoa Hiep","Hòa Hiệp"],
["Hoa Mi","Họa Mi"],
["Hoang Viet","Hoàng Việt"],
["Le Binh","Lê Bình"],
["Le Thuc Hoach","Lê Thúc Hoạch"],
["Le Ngung","Lê Ngung"],
["Lang Le","Láng Le"],
["Sam duong son","Sầm Sơn"],
["Thang Long","Thăng Long"],
["Tu Cuong","Tự Cường"],
["Tu Lap","Tự Lập"],
["Ut Tich","Út Tịch"],
["Luu Nhan Chu","Lưu Nhân Chú"],
["Pham Banh","Phạm Bành"],
["Chan Hung","Chấn Hưng"],
["Dai Nghia","Đại Nghĩa"],
["Dan Tri","Dân Trí"],
["Nguyen Huu Dat","Nguyễn Hữu Dật"],
["Nghia Hoa","Nghĩa Hòa"],
["Hoang Dinh Nghia","Hoàng Đình Nghĩa"],
["Nghia Hung","Nghĩa Hưng"],
["Nghia Phat","Nghĩa Phát"],
["Tu Hai","Tứ Hải"],
["Chu Dong Tu","Chử Đồng Tử"],
["Dang Lo","Đặng Lộ"],
["Dong duong son","Đông Sơn"],
["Le Minh Xuan","Lê Minh Xuân"],
["Kenh 2","Kênh 2"],
["Kinh A","Kinh A"],
["Le Dinh Chi","Lê Đình Chi"],
["The Lu","Thế Lữ"],
["Hoa Phuong","Hoa Phượng"],
["Van Coi","Vân Côi"],
["Tan Xuan","Tân Xuân"],
["Tan Xuan 1","Tân Xuân 1"],
["Tan Xuan 2","Tân Xuân 2"],
["Tan Xuan 6","Tân Xuân 6"],
["Hoang Xuan Hoanh","Hoàng Xuân Hoành"],
["Hoang Xuan Nhi","Hoàng Xuân Nhị"],
["Nguyen Xuan Khoat","Nguyễn Xuân Khoát"],
["Thanh My Loi","Thạnh Mỹ Lợi"],
["duong E1","Đường E1"],
["duong F2","Đường F2"],
["duong F3","Đường F3"],
["duong K1","Đường K1"],
["Tran Van Hoang","Trần Văn Hoàng"],
["Cay Keo","Cây Keo"],
["Chu Thien","Chu Thiên"],
["Duong Khue","Dương Khuê"],
["Le Quang Chieu","Lê Quang Chiểu"],
["Le Thanh Phuong","Lê Thành Phương"],
["Luong Truc Dam","Lương Trúc Đàm"],
["Luy Ban Bich","Lũy Bán Bích"],
["Quach Dieu","Quách Điêu"],
["Quach Dinh Bao","Quách Đình Bảo"],
["Quach Huu Nghiem","Quách Hữu Nghiêm"],
["Thach Lam","Thạch Lam"],
["Tran Quang Co","Trần Quang Cơ"],
["Y Lan","Ỷ Lan"],
["Kenh 10","Kênh 10"],
["Kenh 7","Kênh 7"],
["Tong Huu Dinh","Tống Hữu Định"],
["Do Bi","Đỗ Bí"],
["Do Thua Luong","Đỗ Thừa Luông"],
["Do Thua Tu","Đỗ Thừa Tự"],
["Cu xa Tu Do","Cư xá Tự Do"],
["Hien Vuong","Hiền Vương"],
["Le Cao Lang","Lê Cao Lãng"],
["Le Khoi","Lê Khôi"],
["Le Lam","Lê Lâm"],
["Le Niem","Lê Niệm"],
["Le Sao","Lê Sao"],
["Nguyen The Truyen","Nguyễn Thê Truyện"],
["Nguyen The Truyen","Nguyễn Thế Truyện"],
["Nguyen Van Sang","Nguyễn Văn Săng"],
["Nguyen Van To","Nguyễn Văn Tố"],
["Nguyen Thi Thu","Nguyễn Thị Thử"],
["Phan Van Nam","Phan Văn Năm"],
["Tay Thanh","Tây Thạnh"],
["duong C6A","C6A"],
["duong C8","C8"],
["duong CN13","CN13"],
["duong B3","B3"],
["duong CN10","CN10"],
["duong CN1","CN1"],
["duong CN2","CN2"],
["duong CN3","CN3"],
["Tran Thu Do","Trần Thủ Độ"],
["Van Cao","Văn Cao"],
["Cao Van Ngoc","Cao Văn Ngọc"],
["Quy hoach khu dan cu","Quy hoạch khu dân cư"],
["Pham Van","Phạm Vấn"],
["Trinh Loi","Trịnh Lôi"],
["Vo Hoanh","Võ Hoành"],
["Nhi Tan 1","Nhị Tần 1"],
["Dan Thang 1 - Nhi Tan 1","Dân Thắng 1 - Nhị Tân 1"],
["Khuong Viet","Khuông Việt"],
["Le Nga","Lê Ngã"],
["Nguyen Minh Chau","Nguyễn Minh Châu"],
["Bo Bao Tan Thang","Bờ Bao Tân Thắng"],
["Bo bao xom Ho","Bờ bao xóm Hồ"],
["Bo bao duong song Sai Gon","Bờ bao sông Sài Gòn"],
["Doan Gioi","Đoàn Giỏi"],
["duong N1","N1"],
["duong N2","N2"],
["duong N3","N3"],
["duong N9","N9"],
["duong CN11","CN11"],
["duong DC3","DC3"],
["duong DC5","DC5"],
["duong son Ky","Sơn Kỳ"],
["Do Nhuan","Đỗ Nhuận"],
["duong CC2","CC2"],
["duong CC3","CC3"],
["duong CC4","CC4"],
["duong CC5","CC5"],
["duong CN6","CN6"],
["duong DC1","DC1"],
["duong DC4","DC4"],
["duong DC7","DC7"],
["duong DC8","DC8"],
["duong DC9","DC9"],
["Duong Thieu Tuoc","Dương Thiệu Tước"],
["Do Cong Tuong","Đỗ Công Tường"],
["Tran Tuong Cong","Trần Tướng Công"],
["Do Thi Tam","Đỗ Thị Tâm"],
["Duong Van Duong","Dương Văn Dương"],
["Go Dau","Gò Dầu"],
["Hoang Van Hoe","Hoàng Văn Hòe"],
["Ly Tue","Lý Tuệ"],
["Nguyen Lo Trach","Nguyễn Lộ Trạch"],
["Nguyen Quang Dieu","Nguyễn Quang Diệu"],
["Nguyen Suy","Nguyễn Súy"],
["Pham Ngoc","Phạm Ngọc"],
["Phung Chi Kien","Phùng Chí Kiên"],
["Vuong Van Huong","Vương Văn Huống"],
["Huong Lo 11","Hương Lộ 11"],
["Huong Lo 65B","Hương Lộ 65B"],
["Dan toc","Dân tộc"],
["Dang The Phong","Đặng Thế Phong"],
["Diep Minh Chau","Diệp Minh Châu"],
["Doan Ket","Đoàn Kết"],
["Tu Quyet","Tự Quyết"],
["Tay duong son","Tây Sơn"],
["Luong Dac Bang","Lương Đắc Bằng"],
["Nguyen Sang","Nguyễn Sáng"],
["Tran Van On","Trần Văn Ơn"],
["Chan Ly","Chân Lý"],
["Nguyen Hau","Nguyễn Hậu"],
["Nguyen Van Huyen","Nguyễn Văn Huyên"],
["Truong Minh Ky","Trương Minh Ký"],
["Van Hanh","Vạn Hạnh"],
["Bui Cam Ho","Bùi Cẩm Hổ"],
["Bui Huy Bich","Bùi Huy Bích"],
["Tran Van Can","Trần Văn Cần"],
["duong D9","D9"],
["Duong Duc Hien","Dương Đức Hiền"],
["duong S11","S11"],
["duong S5","S5"],
["duong S9","S9"],
["duong T1","T1"],
["duong T4A","T4A"],
["duong T5","T5"],
["duong T6","T6"],
["Nguyen Huu Tien","Nguyễn Hữu Tiến"],
["Tinh Lo 43","Tỉnh Lộ 43"],
["Huu Nghi","Hữu Nghị"],
["duong so 48A","Đường số 48A"],
["duong so 48C","Đường số 48C"],
["duong so 50A","Đường số 50A"],
["duong so 50B","Đường số 50B"],
["duong so 50C","Đường số 50C"],
["duong so 50D","Đường số 50D"],
["duong A8","Đường A8"],
["duong G1","Đường G1"],
["duong G8","Đường G8"],
["duong so 1B","Đường số 1B"],
["duong so 5C","Đường số 5C"],
["A Trung Nhi","A Trưng Nhị"],
["Kha Van Can","Kha Vạn Cân"],
["trung tam thuong mai Binh Dien","Trung tâm thương mại Bình Điền"],
["Cach Mang Thang Tam","Cách Mạng Tháng Tám"],
["Go Dua","Gò Dưa"],
["Lo A1","Lô A1"],
["Lo A2","Lô A2"],
["Phu Chau","Phú Châu"],
["Chuong Duong","Chương Dương"],
["To Vinh Dien","Tô Vĩnh Diện"],
["Duong Van Cam","Dương Văn Cam"],
["Ly Te Xuyen","Lý Tế Xuyên"],
["Nga 5 Thu Duc","Ngã 5 Thủ Đức"],
["Tam Thon Hiep","Tam Thôn Hiệp"],
["Tuyen Ap Tam Dong","Tuyến Ấp Tam Đông"],
["Le Van Duyet","Lê Văn Duyệt"],
["Linh Trung","Linh Trung"],
["Quoc lo 1K","Quốc lộ 1K"],
["Ngo Tung Chau","Ngô Tùng Châu"],
["Chau Binh","Châu Bình"],
["U Ghe","Ụ Ghe"],
["Ho Van Tu","Hồ Văn Tư"],
["Van Tuong","Vạn Tượng"],
["Bui Thanh Khiet","Bùi Thanh Khiết"],
["An Phu Tay","An Phú Tây"],
["Sau Thien","Sáu Thiện"],
["Hoang Phan Thai","Hoàng Phan Thái"],
["Huynh Van Tri","Huỳnh Văn Trí"],
["Trinh Nhu Khue","Trịnh Như Khuê"],
["duong so 1E","Đường số 1E"],
["duong so 6A","Đường số 6A"],
["duong so 9A","Đường số 9A"],
["Da Phuoc","Đa Phước"],
["Linh Hoa Tu","Linh Hòa Tự"],
["duong so 4B","Đường số 4B"],
["Ap 2","Ấp 2"],
["Bo Hue","Bờ Huệ"],
["Duong vao trung tam thuong mai Binh Dien","Đường vào trung tâm thương mại Bình Điền"],
["Lien Ap 1-3","Liên Ấp 1-3"],
["Lien ap 2-3-4","Liên ấp 2-3-4"],
["Le Thi Ha","Lê Thị Hà"],
["Nam Thoi 2","Nam Thới 2"],
["Lien Ap 3-4","Liên Ấp 3-4"],
["Lien Ap 2","Liên Ấp 2"],
["Ap 3","Ấp 3"],
["Thanh Nien Xung Phong","Thanh Niên Xung Phong"],
["Tan Liem","Tân Liêm"],
["Nguyen Van Yen","Nguyễn Văn Yến"],
["Hung Nhon Bau Goc","Hưng Nhơn Bầu Gốc"],
["Bong Van Dia","Bông Văn Dĩa"],
["Cay Bang","Cây Bàng"],
["Long Hung","Long Hưng"],
["Lien Ap 6-2","Liên Ấp 6-2"],
["Lien Ap 5-6","Liên Ấp 5-6"],
["Le Quat","Lê Quát"],
["duong so 2E","Đường số 2E"],
["duong so 2F","Đường số 2F"],
["duong so 2G","Đường số 2G"],
["duong so P11 KCN Vinh Loc","Đường số P11 KCN Vĩnh Lộc"],
["Lai Hung Cuong","Lại Hùng Cường"],
["Duyen Hai","Duyên Hải"],
["Rung Sac","Rừng Sác"],
["Ba Xan","Bà Xán"],
["Nguyen Cong Bao","Nguyễn Công Bao"],
["Trinh Thi Mieng","Trịnh Thị Miếng"],
["Do Dinh Nhan","Đỗ Đình Nhân"],
["Tinh Lo 826","Tỉnh Lộ 826"],
["Tinh lo 8","Tỉnh lộ 8"],
["Ben Suc","Bến Súc"],
["Binh My","Bình Mỹ"],
["Ha Duy Phien","Hà Duy Phiên"],
["Huynh Minh Muong","Huỳnh Minh Mương"],
["duong song Lu","Sông Lu"],
["Tran Trung Lap","Trần Trung Lập"],
["Ba Sa","Ba Sa"],
["Trung Viet","Trung Viết"],
["Cay Trom My Khanh","Cây Trôm Mỹ Khánh"],
["Cay Bai","Cây Bài"],
["Tran Van Cham","Trần Văn Chẩm"],
["Tan Long","Tân Long"],
["Tan Nhat","Tân Nhật"],
["Vuon Thuoc","Vườn Thuốc"],
["Tran Tu Binh","Trần Tử Bình"],
["Bau Tram","Bàu Trâm"],
["Trung An","Trung An"],
["Ap Dinh","Ấp Đình"],
["Trung Nu Vuong","Trưng Nữ Vương"],
["Xuan Thoi Thuong 4-1","Xuân Thới Thượng 4-1"],
["Dong Thanh 2-3","Đông Thạnh 2-3"],
["Dong Thanh 2-6","Đông Thạnh 2-6"],
["Dong Thanh 2-7","Đông Thạnh 2-7"],
["Dong Thanh 4-2","Đông Thạnh 4-2"],
["Dong Thanh 4-1","Đông Thạnh 4-1"],
["Dong Thanh 3-4","Đông Thạnh 3-4"],
["Dong Thanh 7-5","Đông Thạnh 7-5"],
["Do Van Day","Đỗ Văn Dậy"],
["Lien Tan Hiep","Liên Tân Hiệp"],
["Tan Hiep","Tân Hiệp"],
["Tan Lap 1","Tân Lập 1"],
["Tan Lap 2","Tân Lập 2"],
["Van Tien Dung","Văn Tiến Dũng"],
["Ap moi My Hue","Ấp mới Mỹ Huề"],
["Tuyen Xuan Thoi 2","Tuyến Xuân Thới 2"],
["Tran Van Muoi","Trần Văn Mười"],
["Tuyen 1 2003 Xuan Thoi duong son","Tuyến 1 2003 Xuân Thới Sơn"],
["Tuyen Ap 4 Xuan Thoi duong son","Tuyến Ấp 4 Xuân Thới Sơn"],
["Pi O","Pi Ô"],
["Thoi An 8","Thới An 8"],
["Thoi An 9","Thới An 9"],
["Tan Thoi Nhat 9","Tân Thới Nhất 9"],
["Duong Cat Loi","Dương Cát Lợi"],
["Dao Su Tich","Đào Sư Tích"],
["Minh Phung","Minh Phung"],
["Dang Thuy Tram","Đặng Thùy Trâm"],
["An Phu Dong","An Phú Đông"],
["Ap 5","Ấp 5"],
["Ba Be","Ba Bê"],
["Ba Lang","Ba Làng"],
["Ba Trung","Ba Trung"],
["Binh Hoa","Bình Hòa"],
["Binh Phu 1","Bình Phú 1"],
["Binh Tri Dong","Bình Trị Đông"],
["Bo Bao","Bờ Bao"],
["Bo Xe Lam","Bờ Xe Lam"],
["Bui Van Them","Bùi Văn Thêm"],
["Cay Da","Cây Da"],
["Cu Xa Bac Hai","Cư Xá Bắc Hải"],
["Dao Van Thu","Đào Văn Thử"],
["De Bao","Đê Bao"],
["Doan Nguyen Tuan","Đoàn Nguyễn Tuấn"],
["Dong Thanh 8","Đông Thạnh 8"],
["Duong Thi Nam","Dương Thị Năm"],
["Giong Cat","Giồng Cát"],
["Hang Duong","Hàng Dương"],
["Ho Ngoc Lam","Hồ Ngọc Lãm"],
["Ho Thi Bung","Hồ Thị Bưng"],
["Ho Van Tang","Hồ Văn Tắng"],
["Hoang Kim Giao","Hoàng Kim Giao"],
["Hoang Ngan","Hoàng Ngân"],
["Hoc Huu","Hóc Hưu"],
["Huynh Huu Tri","Huỳnh Hữu Trí"],
["Huynh Van Mot","Huỳnh Văn Một"],
["Kenh 11","Kênh 11"],
["Kenh 9","Kênh 9"],
["Kenh B","Kênh B"],
["Kenh Tan Hoa","Kênh Tân Hóa"],
["Kim Bien","Kim Biên"],
["Le Minh Nhat","Lê Minh Nhật"],
["Lo Gom","Lò Gốm"],
["Long Phuoc","Long Phước"],
["Nguyen Binh","Nguyễn Bình"],
["Nguyen Dinh Kien","Nguyễn Đình Kiên"],
["Nguyen Thi Lang","Nguyễn Thị Lăng"],
["Nguyen Thi Mang","Nguyễn Thị Măng"],
["Nguyen Tien Hien","Nguyễn Tiến Hiến"],
["Nguyen Van Bay","Nguyễn Văn Bảy"],
["Nguyen Van Khoi","Nguyễn Văn Khối"],
["Phan Duc","Phan Đức"],
["Quang Ham","Quảng Hàm"],
["Rach Ong Do","Rạch Ông Đồ"],
["nguyen thai son","Nguyễn Thái Sơn"],
["Suoi Cai","Suối Cái"],
["Tan Nhut","Tân Nhựt"],
["Thanh Thoi","Thạnh Thới"],
["Tran Nhan Tong","Trần Nhân Tông"],
["Tran Van Can","Trần Văn Cẩn"],
["Tran Van Danh","Trần Văn Danh"],
["Tran Van Du","Trần Văn Dư"],
["Trinh Thi Doi","Trịnh Thị Dối"],
["Vinh Khanh","Vĩnh Khánh"],
["Vo Chi Cong","Võ Chí Công"],
["Vo Thi Hoi","Võ Thị Hồi"],
["Vo Thi Nghi","Võ Thị Nghỉ"],
["Vo Tran Chi","Võ Trần Chí"],
["Xa De","Xã Đê"],
["Xuan Thoi duong son 33","Xuân Thơi Sơn 33"],
["Xuan Thoi duong son 38","Xuân Thới Sơn 38"],
["Xuyen A","Xuyên Á"],
["Yet Kieu","Yết Kiêu"],
["Nhon Duc","Nhơn Đức"],
["duong C18","Đường C18"],
["duong so 19D","Đường số 19D"],
["duong so 19E","Đường số 19E"],
["duong 31E","Đường 31E"],
["duong ht45","Đường HT45"],
["duong so 21A","Đường so 21A"],
["duong so 24B","Đường số 24B"],
["duong so 48B","Đường số 48B"],
["duong so 55A","Đường số 55A"],
["duong A1","Đường A1"],
["duong A2","Đường A2"],
["duong A4","Đường A4"],
["duong A5","Đường A5"],
["duong A6","Đường A6"],
["duong B10","Đường B10"],
["duong B1","Đường B1"],
["duong B2","Đường B2"],
["duong B4","Đường B4"],
["duong B5","Đường B5"],
["duong B6","Đường B6"],
["duong B7","Đường B7"],
["duong B8","Đường B8"],
["duong B9","Đường B9"],
["duong C2","Đường C2"],
["duong C3","Đường C3"],
["duong so 4A","Đường số 4A"],
["duong so 8A","Đường số 8A"],
["duong so 11","Đường số 11"],
["duong so 10","Đường số 10"],
["duong so 15","Đường số 15"],
["duong so 12","Đường số 12"],
["duong so 13","Đường số 13"],
["duong so 16","Đường số 16"],
["duong so 19","Đường số 19"],
["duong so 14","Đường số 14"],
["duong so 18","Đường số 18"],
["duong so 60","Đường số 60"],
["duong so 63","Đường số 63"],
["duong so 67","Đường số 67"],
["duong so 61","Đường số 61"],
["duong so 22","Đường số 22"],
["duong so 23","Đường số 23"],
["duong so 17","Đường số 17"],
["duong so 50","Đường số 50"],
["duong so 53","Đường số 53"],
["duong so 54","Đường số 54"],
["duong so 56","Đường số 56"],
["duong so 57","Đường số 57"],
["duong so 55","Đường số 55"],
["duong so 45","Đường số 45"],
["duong so 48","Đường số 48"],
["duong so 49","Đường số 49"],
["duong so 46","Đường số 46"],
["duong so 40","Đường số 40"],
["duong so 42","Đường số 42"],
["duong so 39","Đường số 39"],
["duong so 31","Đường số 31"],
["duong so 35","Đường số 35"],
["duong so 33","Đường số 33"],
["duong so 21","Đường số 21"],
["duong so 8B","Đường số 8B"],
["duong so 80","Đường số 80"],
["duong so 82","Đường số 82"],
["duong so 81","Đường số 81"],
["duong so 3A","Đường số 3A"],
["duong so 5A","Đường số 5A"],
["duong so 30","Đường số 30"],
["duong so 32","Đường số 32"],
["duong so 36","Đường số 36"],
["duong so 7A","Đường số 7A"],
["duong so 70","Đường số 70"],
["duong so 72","Đường số 72"],
["duong so 74","Đường số 74"],
["duong so 76","Đường số 76"],
["duong so 37","Đường số 37"],
["duong so 18","Đường Số 18"],
["duong so 28","Đường số 28"],
["duong so 2A","Đường số 2A"],
["duong so 2B","Đường số 2B"],
["duong so 34","Đường số 34"],
["duong so 62","Đường số 62"],
["duong so 68","Đường số 68"],
["duong so 22","Đường số 22"],
["duong so 40","Đường số 40"],
["duong so 41","Đường số 41"],
["duong so 52","Đường số 52"],
["duong so 5B","Đường số 5B"],
["duong so 47","Đường số 47"],
["duong so 59","Đường số 59"],
["duong so 64","Đường số 64"],
["duong so 65","Đường số 65"],
["duong so 66","Đường số 66"],
["duong so 43","Đường số 43"],
["duong so 20","Đường số 20"],
["duong so 24","Đường số 24"],
["duong so 25","Đường số 25"],
["duong so 26","Đường số 26"],
["duong so 29","Đường số 29"],
["duong so 38","Đường số 38"],
["duong so 44","Đường số 44"],
["duong so 51","Đường số 51"],
["duong so 1H","Đường số 1H"],
["duong so 1I","Đường số 1I"],
["duong so 3J","Đường số 3J"],
["duong so 4F","Đường số 4F"],
["duong so 5K","Đường số 5K"],
["duong so 6E","Đường số 6E"],
["duong so 7L","Đường số 7L"],
["duong so 9M","Đường số 9M"],
["duong 36", "Đường 36"],
["duong C6","Đường C6"],
["duong C7","Đường C7"],
["duong C5","Đường C5"],
["duong A","Đường A"],
["duong B","Đường B"],
["duong C","Đường C"],
["duong D","Đường D"],
["duong E","Đường E"],
["duong F","Đường F"],
["duong H","Đường H"],
["duong K","Đường K"],
["duong N","Đường N"],
["duong U","Đường U"],
["duong so 4","Đường số 4"],
["duong so 8","Đường số 8"],
["duong so 7","Đường số 7"],
["duong so 3","Đường số 3"],
["duong so 2","Đường số 2"],
["duong so 9","Đường số 9"],
["duong so 1","Đường số 1"],
["duong so 5","Đường số 5"],
["duong so 6","Đường số 6"],
["Hung Phu","Hưng Phú"],
["Tan Tao","Tân Tạo"],
["duong Phu My","Phú Mỹ"],
[" Phu My ","Phú Mỹ"],
[" Phu My-","Phú Mỹ"],
["duong Nguyen Thai Binh","Nguyễn Thái Bình"],
["Nguyen Thai Binh","Nguyễn Thái Bình"],
["Thai Binh","Thái Bình"],
["duong Binh Thanh","Bình Thành"],
["Tan Phu","Tân Phú"],
["An Phu","An Phú"],
["hung gia 3","Hưng Gia 3"],
["duong Ben Than","Đường Bến Than"],
["Pham Ngu Lao","Phạm Ngũ Lão"],
["Binh Chanh","Bình Chánh"],
["duong Thao Dien","Thảo Điền"],
["Thao Dien","Thảo Điền"],
["Tan Hung","Tân Hưng"],
["duong an binh","An Bình"],
[" an binh","An Bình"],
["duong Trung Lap","Trung Lập"],
["Trung Lap","Trung Lập"],
["duong Mieu Noi","duong Miếu Nổi"],
["mieu noi","Miếu nổi"],
["Hung Gia 1","Hưng Gia 1"],
["Hung Gia 2","Hưng Gia 2"],
["Hung Gia 3","Hưng Gia 3"],
["Hung Gia 4","Hưng Gia 4"],
["Ben Nghe","Bến Nghé"],
["Nha Be","Thị trấn Nhà Bè"],
["Hiep Binh","Hiệp Bình"],
["Binh Phu","Bình Phú"]
]



def detect_district_index(address):
    """
    Detect district position in address
    :param address: raw text address
    :return: index
    """
    for j in range(0, len(districtListHCM)):
        index = address.find(districtListHCM[j][0].lower())
    return index


def detect_district(address):
    """
    Detect district in address
    :param address: raw text address
    :return: district detected in address
    """
    for j in range(0, len(districtListHCM)):
        if (districtListHCM[j][0].lower() in address.lower()):
                return districtListHCM[j][1]
    return ""

def detect_ward_index(address):
    """
    Detect ward position in address
    :param address: raw text address
    :return: index
    """
    for k in range(0, len(wardListHCM)):
        index = address.find(wardListHCM[k][0].lower())
    return index

def detect_ward(address):
    """
    Detect ward in address
    :param address: raw text address
    :return: ward detected in address
    """
    for k in range(0, len(wardListHCM)):
        if (wardListHCM[k][0].lower() in address.lower()):
            return wardListHCM[k][1]
    return ""


# def detect_street_index(address):
#     """
#     Detect street position in address
#     :param address: raw text address
#     :return: index
#     """
#     for k in range(0, len(streetListHCM)):
#         index = 
#     return index

def detect_street(address):
    """
    Detect street in address
    :param address: raw text address
    :return: street detected in address
    """
    for k in range(0, len(streetListHCM)):
        if (streetListHCM[k][0].lower() in address.lower()):
            return streetListHCM[k][1],streetListHCM[k][0] 
    return "",""

def detect_num(addressAccent,address, street):
    """
    Detect numberHourse in address
    :param address: raw text address, index street of address numberhourse
    :return: numberHourse detected in address
    """
    index = address.find(street)
    # print(index, " ", street)

    if index != -1:
        return addressAccent[0:index].strip(" ").strip("Đường").strip("đường").strip("- ")
    else:
        return ""
